### ISSUE TITLE
Duplicate --enable-avx options in configure scripts

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#100]
In files `.conf.win32-vcpp` and `.conf.win64-vcpp` `--enable-avx` option repeats twice.
Looks like second line is not needed, but if it is needed for some reason, it is better to add comment describing why.

https://github.com/bochs-emu/Bochs/blob/2928315646d2c13797297e7ee16ba5c654206767/bochs/.conf.win32-vcpp#L13
https://github.com/bochs-emu/Bochs/blob/2928315646d2c13797297e7ee16ba5c654206767/bochs/.conf.win32-vcpp#L27

**Comment by stlintel** [comment]
Thanks, fixed :)
