### ISSUE TITLE
Crash when Voodoo 3 guest resolution is higher than host resolution

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#121]
I tried to install [Sfft1.9.zip](https://github.com/bochs-emu/Bochs/files/13259426/Sfft1.9.zip) drivers for Voodoo 3 to Windows XP.
After restart, guest resolution for some reason changed to 1920x1200.
Because host resolution is 1280x1024, image not fits and Bochs crashes.
Crash also happens with default Windows XP drivers for Voodoo 3 if I set 1920x1200 resolution manually.
Crash most likely happens on this line:
https://github.com/bochs-emu/Bochs/blob/83c71dd7a27ef83785cb981bf35cb6cd09f77a79/bochs/iodev/display/voodoo.cc#L788
If I put `if (xc >= 1280 || yc >= 1024) continue;` earlier, no crash happen.
However it looks like SFFT drivers have some other problems, so fixing this particular issue won't be enough to make them work correctly.

<s>_To properly reproduce this problem, something should be done with https://github.com/bochs-emu/Bochs/discussions/120._</s> **upd.** _← this thing is solved._

**Comment by Vort** [comment]
With latest changes, Bochs crashes before reaching resolution change of Voodoo 3 adapter.
I'm not entirely sure about this recent problem, may be my mistake.
But it looks like with b54b135d this happens:
```
01384648913i[CPU0  ] MOV_EwSw: can't use this segment register 6
01384648955i[APIC0 ] warning: misaligned APIC access. addr=0x0000fee00081
01384648955p[APIC0 ] >>PANIC<< APIC read at address 0x0000fee00081 spans 32-bit boundary !
```
I also saw slightly different variation of this problem.
When with 1e92d9ee - no such problem.

**Comment by Vort** [comment]
Most likely, fresh problem was introduced with f5b54a4d336d84caf7eb744f6f97ae768c317f01.
Another variation of its effect:
`02866822160e[CPU0  ] interrupt(): TSS selector points to bad TSS - #GP(tss_selector)`

**Comment by stlintel** [comment]
Doesn't seem related. Are you sure it is this commit ?
Can you make me up-to-speed what are you doing exactly ?
I will try to reproduce and understand.

**Comment by stlintel** [comment]
the only 'suspicious' commit could be 32cab8f384656d88be2d69e3125957455bfaff6f
Can you check with it ?

**Comment by Vort** [comment]
> Doesn't seem related. Are you sure it is this commit ?

XP should not know about such fresh instruction, yeah.

> Can you make me up-to-speed what are you doing exactly ?

I'm trying to boot Windows XP with default Voodoo 3 drivers (and 1920x1200 resolution, but it may not matter).

With 620d0912646261c7e5b20fe69ef85823637abc85 I'm able to go up to resolution change and then get crash (which is "good").
With f5b54a4d336d84caf7eb744f6f97ae768c317f01 I'm getting either `misaligned APIC access` or `bad TSS` before resolution changes ("wrong").

If I revert f5b54a4d336d84caf7eb744f6f97ae768c317f01 all at once, then "good" operation is back.
But when I tried to revert it in several steps, then after all steps were complete, "wrong" operation was still in place.

Such strange problems are usually indication of either glitchy build system or memory corruptions.
Also may be sign of bugs in compiler or linker (however it is rare).
I do not know how to track this thing yet.
Maybe I will have some ideas tomorrow.

**Comment by stlintel** [comment]
go to latest master and do fresh recompile of everything
make all-clean; make

**Comment by Vort** [comment]
> go to latest master and do fresh recompile of everything

Does not help.
Problem is not that easy sadly.

> (and 1920x1200 resolution, but it may not matter)

It does not matter for `misaligned APIC access` / `bad TSS` problem.
I changed resolution back to 1024x768 and still having problem.

**Comment by Vort** [comment]
It is related to optimization settings somehow.
It appears with `-O3` and `--enable-all-optimizations`, but not with `-O0`.

**↑↑↑ I made separate report about fresh problem: #131 ↑↑↑**

**Comment by stlintel** [comment]
Did you fix resolved the issue ?

**Comment by Vort** [comment]
> Did you fix resolved the issue ?

No, resolution problem is separate from ROM access problem.
However, fixed ROM access allows to test resolution problem with clang made binaries.

**Comment by stlintel** [comment]
I suggest to open another clean item for this issue and close this one.
All the description is only about bug solved by ROM access fix. I don't understand what is the problem here now.

**Comment by Vort** [comment]
> I suggest to open another clean item for this issue and close this one.

I will do this, but later.

**Comment by Vort** [comment]
Superseded by #174.
