### ISSUE TITLE
Can't change CD while simulation is running

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#122]
Once operating system is loaded, it is not possible anymore to change CD.
Log message tells than new image is loaded, but OS still sees previous data in CD drive.
Here is test image with DOS: [CD.zip](https://github.com/bochs-emu/Bochs/files/13269076/CD.zip), but I also noticed the same behaviour with Windows XP.

https://github.com/bochs-emu/Bochs/assets/1242858/b8f1ecba-b5a9-4adb-87e4-42d2febb3aff

Version: e896e71618f6f5e6deab79c338b8701d57084a40 _(or very close to it, do not remember exactly)_

**Comment by stlintel** [comment]
Same some kind of 'EJECT' command should be send to CD-ROM while changing the file ?

**Comment by Vort** [comment]
If I eject cd1, change to cd2 and insert it - effect is the same.
So it may be some sort of eject, but not the one which can be triggered with UI.

**Comment by fysnet** [comment]
I can confirm the error.
Using WinXP as a Guest, if I start Bochs with a CD-ROM inserted, then using WinXP, eject the CD. All looks fine.
Then I change the CD using the Bochs CD button.
WinXP recognizes a CD has been inserted. However, WinXP thinks it is the same CD and continues to use the cache it had for that CD. The new CD-ROM image file is read from, but the cache of the old CD tells it to read from the wrong places.

Here is another indicator.
Start Bochs with a CD-ROM inserted. In the emulation, use WinXP Explorer, right click on the CD-ROM and choose Eject.
Wait for the entry to change from the CD-ROMs volume name to `CD Drive (D:)`.
Now left-click on the `CD Drive (D:)` entry. WinXP will try to read from the drive, finding out that it isn't there, showing an error of `Please insert a disc into drive D:.` Click on Cancel.
Now using the Bochs CD button, change to the new CD. Once you have done this, the new CD is used as expected, and correctly.

In harddrv.cc, at or around line 1368, we try to eject the CD. However, the only thing it does is close the file and update the CD Button in the GUIs status bar. Other than marking `cdrom.ready = 0`, it does nothing else. I am guessing that WinXP (and other Guests) are expecting the drive's status or other items to change as well. The Request Sense does get set to 02/3A/00/00 as expected, but this doesn't seem to be enough.

If I get a chance, I will investigate further.

**Comment by fysnet** [comment]
Add the line below at [line 1366](https://github.com/bochs-emu/Bochs/blob/master/bochs/iodev/harddrv.cc#L1366) in harddrv.cc
```
  SIM->get_param_enum("status", base)->set(BX_EJECTED);
  bx_gui->update_drive_status_buttons();
  atapi_cmd_error(channel, SENSE_UNIT_ATTENTION, ASC_MEDIUM_MAY_HAVE_CHANGED, 1);   // <-------- This one
}
raise_interrupt(channel);
```
This should fix the problem. Let me know if it does.

**Comment by fysnet** [comment]
In case you prefer patch style:
```
--- C:\bochs\bochs_org\iodev\harddrv.cc	2023-10-22 09:17:28.861410300 -0700
+++ C:\bochs\bochs\iodev\harddrv.cc	2023-11-06 21:42:48.282913300 -0700
@@ -1363,6 +1363,7 @@
                       bx_list_c *base = (bx_list_c*) SIM->get_param(ata_name);
                       SIM->get_param_enum("status", base)->set(BX_EJECTED);
                       bx_gui->update_drive_status_buttons();
+                      atapi_cmd_error(channel, SENSE_UNIT_ATTENTION, ASC_MEDIUM_MAY_HAVE_CHANGED, 1);
                     }
                     raise_interrupt(channel);
                   } else { // Load the disc
```

**Comment by Vort** [comment]
> This should fix the problem. Let me know if it does.

I see no changes - FreeDOS and Windows XP behaves the same as before this change.

**Comment by fysnet** [comment]
You are telling WinXP to eject the CD, correct? You are not simply changing the CD via BOCHS with no indication to WinXP that you have, correct?

Simply changing the CD via the CD ribbon-bar icon without indicating to the guest will create undefined results.

The above patch fixes the problem for me using a WinXP guest when I eject the CD using the Guest. I have not tried with FreeDOS.

I will do some more tests later this afternoon.

**Comment by Vort** [comment]
Ok, I see now - ejecting from guest works.
But ejecting from UI should work too.
In such case you can see that disk label disappear in Explorer, so guest is notified.
Also I think that switching without ejecting should emulate ejecting.
And most likely when ejecting will be fully fixed, this scenario will be fixed as well.
Switching CDs like I showed in video in FreeDOS works fine in VirtualBox.

**Comment by fysnet** [comment]
Okay, I think I have figured it out. Please see #125.
Please note that it is of the current harddrv.cc/.h files, which does not have the additional line I wrote about in previous comments. I changed that line to something else.

I checked with WinXP and FreeDOS as Guests and all change status worked as expected.  Please check yourself.

**Comment by Vort** [comment]
I confirm that change works correctly in Windows XP now, thank you.
As for FreeDOS, there is one small thing to note:
If you swap CD and try accessing it immediately, then old CD is shown.
For swapping to work correctly, you need to wait several seconds.
But it is, most likely, property of FreeDOS: I noticed the same thing also with VirtualBox.
So this issue is fixed.
