### ISSUE TITLE
Panic while formatting floppy in Windows 2000

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#123]
When I execute command `format a:` in Windows 2000 _(or Windows XP)_, Bochs shows error `could not perform lseek() to -512 on floppy image file`.

![bochs_format_panic](https://github.com/bochs-emu/Bochs/assets/1242858/ffdbddd7-52db-4efa-a970-c6e82fbadcd8)

Version: 75d076b990a5a8198b6bf9a8ee1e43a37483eba3.

**Comment by fysnet** [comment]
I had some issues with the FDC code on older Guests, so I went investigating. I found a few errors and one thing led to another and I have a considerable update for the FDC emulation. The Format function was my next focus. I will look into this.

Thanks.

**Comment by fysnet** [comment]
I can confirm this error. However, with my new updates, this error has been remedied. As soon as I do some more testing and verify that my new updates work on all disk types and sizes, I will post a PR.

**Comment by Vort** [comment]
@fysnet do you know about OmniFlop program? May be useful for testing.

**Comment by fysnet** [comment]
I had not. I will have a look. Thank you.

**Comment by fysnet** [comment]
@Vort, please have a look at PR #135. It drastically enhances the floppy emulation, which should fix the issue you show here.
While you are at it, please test the new emulation and let me know if you find any errors. 
I tested it with many guests in many instances and different types and disk sizes, however, since it is a drastic change, all the testing I can get will help.

**Comment by Vort** [comment]
> should fix the issue you show here

I confirm fix for `lseek() to -512` problem, thanks.

> please test the new emulation and let me know if you find any errors

I'm not that experienced to test properly such huge change.
But I made few tests and found two problems.
1. Not related to your changes, it was like that before. If I press Reset button in UI while floppy is accessed, "green light" stays on after restart.
2. Partially related to your changes. I tried to use 360K floppy in 1.2M drive. DOS was working fine with it, but when I booted to WinXP, and tried to access floppy, OS displayed controller error or something like that. Before your changes, it asked to format floppy - not better. I decided to check this scenario on real hardware: floppy drive was producing weird noises for quite time, but eventually WinXP showed correct files on disk.

**Comment by fysnet** [comment]
1. I can confirm this. It should be a quick fix in the gui code. I will see about adding a PR for it.
2. Disks of 360k and smaller never really worked well in WinXP and newer. Somewhere around WinXP SP1, Microsoft "divided" the floppy driver into two, a FDC driver and a floppy disk driver, to accommodate USB floppy drives. This is when 360k disks stopped working. Depending on the version of WinXP and the drive (a 1.2Meg drive or a 360k drive), you would either get a "format drive" response, as your 'before' note, or a 'disk i/o error', as the 'after'/current response.

I don't wish to find out why 360k disks don't work on WinXP. They work just fine in Win98 and before. (where the floppy driver was still a single driver)

Thank you though for the comments. I will look into the first one.
Ben

**Comment by Vort** [comment]
> This is when 360k disks stopped working.

Not in the best way, but they work on my real hardware.
I checked - XP SP3 is installed there, same as in virtual machine.
However, I'm not sure if original driver is used on real hardware or driver from OmniFlop.

> I don't wish to find out why 360k disks don't work on WinXP.

I can agree that this is low priority problem.

**Comment by fysnet** [comment]
I believe this issue can be closed? Thanks again for your efforts. They are appreciated.

**Comment by Vort** [comment]
Can be closed after merge of #135.
