### ISSUE TITLE
Defects in VMLOAD and VMSAVE

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#126]
When executing in the guest: (does not intercept VMLOAD and VMSAVE)
VMLOAD
VMRUN
or
VMSAVE
VMRUN
When VMEXIT occurs in VMRUN, , vmcbptr will be incorrect.

**Comment by stlintel** [comment]
Can you explain better what do you mean ?
What does it mean incorrect ? Where it has effect ? Do you have test case ?

In VMRUN you set vmcbptr according to VMRUN address:

```
  bx_address pAddr = RAX & i->asize_mask();
  if (! IsValidPageAlignedPhyAddr(pAddr)) {
    BX_ERROR(("VMRUN: invalid or not page aligned VMCB physical address !"));
    exception(BX_GP_EXCEPTION, 0);
  }
  set_VMCBPTR(pAddr);

```

**Comment by lgj1107** [comment]
My English is not good enough. Sorry.

void BX_CPP_AttrRegparmN(1) BX_CPU_C::VMLOAD(bxInstruction_c *i)

//The old vmcbptr should be kept here.

 set_VMCBPTR(pAddr);

  BX_CPU_THIS_PTR msr.sysenter_esp_msr = CanonicalizeAddress(vmcb_read64(SVM_GUEST_SYSENTER_ESP_MSR));
// Then restore the old vmcbptr
#endif

  BX_NEXT_INSTR(i);
}

VMSAVE should do the same.

**Comment by stlintel** [comment]
I have made PR for this
https://github.com/bochs-emu/Bochs/pull/128
Can you check if it works as expected and solves the problem ?

**Comment by lgj1107** [comment]
It's working properly now
