### ISSUE TITLE
Bochs sets the Pending_debug_ substitutions.BS bit.

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#132]
VMX guest executes the following instructions.

```assembly
push 0x102
popfq
cpuid
Jmp $+ 2
``` 
On the real machine, the BS  bit is 0.

**Comment by stlintel** [comment]
What is the BS bit you mean ? Where it is ?

**Comment by lgj1107** [comment]
BS bit of Pending_debug_exceptions, bit 14

(Table 25-4. Format of Pending-Debug-Exceptions (Contd.))

**Comment by stlintel** [comment]
Can you provide a binary/image which behaves differently between Bochs and real life ?
How did you check this ?
The main point is ability to run it on Bochs, ability to run it on real HW is secondary.
But I need clear instructions how to understand that you see a problem.

Meaning I need instructions like:
- load this image
- run to here
what is supposed to happen according to your opinion ?
- single step trap is expected / not expected but happens ?
- DR6 value is different ?
- tmp_DR6 (AKA debug_trap in Bochs) is different story -> these are bits which about to be set in DR6

Because I am not sure I understood what do you expect and what do you see

**Comment by stlintel** [comment]
Trying to guess...

<img width="490" alt="image" src="https://github.com/bochs-emu/Bochs/assets/77239907/68e06831-8e45-4dc5-a598-2c51a6d7b9b9">

Do you have IA32_DEBUGCTL involved ?
what is the EFLAGS.TF ? According to your example EFLAGS.TF=1.

**Comment by lgj1107** [comment]
![bochs](https://github.com/bochs-emu/Bochs/assets/3366897/19429b1c-5980-4a77-84d6-d81e46043bc0)

**Comment by lgj1107** [comment]
This is the i5-2400 test result:
![i52400](https://github.com/bochs-emu/Bochs/assets/3366897/834f9c99-d067-477f-bba5-817f44bd9720)

**Comment by lgj1107** [comment]
This is the i5-2400 test result:

![Uploading i52400.jpg…]()

**Comment by lgj1107** [comment]
This is the i5-6700 test result:
![Uploading i76700.png…]()

**Comment by lgj1107** [comment]
This is the i7-6700 test result:

![Uploading i76700.png…]()

**Comment by lgj1107** [comment]
This is the i7-6700 test result:

![Uploading i76700.gif…]()

**Comment by lgj1107** [comment]
This is the i5-2500 test result:

![i52400](https://github.com/bochs-emu/Bochs/assets/3366897/75443e93-9de1-42fb-bc1a-29d24297bef2)

**Comment by stlintel** [comment]
So what about IA32_DEBUGCTL.BTF=1 in your real HW ?
Bochs doesn't implement IA32_DEBUGCTL

**Comment by lgj1107** [comment]
IA32_DEBUGCTL.BTF=0

**Comment by stlintel** [comment]
Sounds weird because documentation says opposite.
Do you have a image to send s.t. I could reproduce it here on my HW and my Bochs version ?
Also how do you control the code there:

```
push 0x102
popfq
cpuid
Jmp $+ 2
```

Can you insert magic breakpoint just before it ?

**Comment by stlintel** [comment]
This is the exact definition from docs:

![image](https://github.com/bochs-emu/Bochs/assets/77239907/77821d45-4772-4c2d-8cf6-8843c571780b)

**Comment by stlintel** [comment]
What is your reason for VMEXIT ?
If this is not debug exception (did you quit because of CPUID intercept?) the bit14 (BS) is implementation specific.
In your case EFLAGS.TF=1 so it is legal to be 1.

**Comment by lgj1107** [comment]
Cpuid is an unconditional exit instruction.
Therefore, the above cases should follow the instructions in the Intel manual to clear the BS bit.

I think so.

28.3.4 Saving Non-Register State

The pending debug exceptions field is saved as clear for all VM exits except the following:
— A VM exit caused by an INIT signal, a machine-check exception, or a system-management interrupt (SMI).
— A VM exit with basic exit reason “TPR below threshold”,2 “virtualized EOI”, “APIC write”, “monitor trap flag,”
or “bus-lock detected.”
.......................

**Comment by stlintel** [comment]
good point, missed that 'clear' in the docs. you had to start from there.
will take a look on it deeper

**Comment by stlintel** [comment]
Can you check if the problem was resolved after push 60cc8020e89950fc72ef72a680054e563b9523c2 ?

**Comment by lgj1107** [comment]
It's working fine.

**Comment by stlintel** [comment]
Thanks for reporting and your help in cleaning it up !
