### ISSUE TITLE
Legacy BIOS and Cirrus Video

### ISSUE THREAD

**Issue by fysnet** [bochs-emu/Bochs#155]
When the `BIOS-bochs-legacy` BIOS and the `VGABIOS-lgpl-latest-cirrus` Video BIOS are specified together, Bochs will not boot the simulation correctly.

Sometimes there is information in the log file, usually not pertinent to the situation, most of the time there is nothing in the log file.

Bochsrc.txt lines:
```
romimage: file=C:/bochs/bochs/bios/BIOS-bochs-legacy
vgaromimage: file=C:/bochs/bochs/bios/VGABIOS-lgpl-latest-cirrus
vga: extension=cirrus, update_freq=10
pci: enabled=1, chipset=i440fx, slot1=cirrus
```
Nothing is displayed to the screen, i.e.: the Bochs output window is completely blank.
The Harddrive LED indicator lights up and then goes off after a short time.

Setting `debug: action=report` you can see that it looks like the OS continues to load, processing the different hardware tasks, etc. However, nothing is ever displayed to the screen.

I tried a MS-DOS simulation, and it seems to get to the prompt, though you can't see that. If you wait a minute to make sure it does get to the prompt, then type `a:`, the floppy LED lights up, then goes off. If you then type `dir`, the LED comes back on again. Obviously making it to the DOS prompt.

I tried a Win98 simulation, the HardDrive LED indicator flashes green and red, just like it does in a normal simulation, however, a little while latter, Bochs crashes/exits with:
```
08054393561i[HD    ] ata0-0: verify command : 0x40 !
08054400099i[KBD   ] wheel mouse mode disabled
08055089817p[UNMAP ] >>PANIC<< Shutdown port: shutdown requested
08055089817i[CMOS  ] Last time: 1701522338 tz=utc (Sat Dec  2 13:05:38   2023)
```
Something somewhere sent `Shutdown` to port `0x8900`.

Run the Win98 simulation again with no changes produces:
```
07572039315i[BIOS  ] Booting from 0000:7c00
  ... long wait, then I click "power icon" on ribbon
08056575000p[WINGUI] >>PANIC<< POWER button turned off.
```
However, I think this is because Win98 went to the "normal or safe-mode" boot option asking you to choose one or the other. So it is waiting for input.

I tried `VGABIOS-lgpl-latest-cirrus-debug` and `debug: action=ignore, cirrus=report` and nothing jumped out in the log file.

This does not happen with the `BIOS-bochs-latest` BIOS, nor with `SeaBIOS`, only with the Legacy BIOS.

If you run Win98 with the `BIOS-bochs-latest` BIOS, here is the log at the same point as above.
```
09225063707i[HD    ] ata0-0: verify command : 0x40 !
09225070029i[KBD   ] wheel mouse mode disabled
09309624651i[P2ISA ] write: ELCR2 = 0x02
09309625285i[P2ISA ] write: ELCR2 = 0x0a
09310689797i[P2ISA ] write: ELCR2 = 0x08
09310690317i[P2ISA ] write: ELCR2 = 0x0a
09317175000e[UHCI  ] UHCI Core: ISO bit is set...
09342030572i[BIOS  ] *** int 15h function AX=f963, BX=4954 not yet supported!
09342034792i[KBD   ] wheel mouse mode enabled
09382517492i[HD    ] ata0-0: verify command : 0x40 !
09390595642i[MEM0  ] Memory access handlers unregistered: 0x0000c2010000 - 0x0000c201ffff
09390595642i[MEM0  ] Register memory access handlers: 0x000020000000 - 0x00002000ffff
09390595642i[CIRRUS] new ROM address = 0x20000000
09390595810i[MEM0  ] Memory access handlers unregistered: 0x000020000000 - 0x00002000ffff
09390595810i[MEM0  ] Register memory access handlers: 0x0000c2010000 - 0x0000c201ffff
09390595810i[CIRRUS] new ROM address = 0xc2010000
09394922922i[SER   ] com1: FIFO enabled
09421341712i[HD    ] ata0-0: verify command : 0x40 !
09448716564i[CIRRUS] switched to 1024 x 768 x 8 @ 60.0 Hz
09448716564i[WINGUI] dimension update x=1024 y=768 fontheight=0 fontwidth=0 bpp=8
10301087213i[WINGUI] dimension update x=640 y=400 fontheight=0 fontwidth=0 bpp=8
10305497859p[UNMAP ] >>PANIC<< Shutdown port: shutdown requested
10305497859i[CMOS  ] Last time: 1701524388 tz=utc (Sat Dec  2 13:39:48   2023)
10305497859i[      ] restoring default signal behavior
10305497859i[SIM   ] quit_sim called with exit code 1
```

### Conclusion
After investigating further, the `legacy` bios doesn't call a suitable `pci_bios_init_optrom` procedure as the `latest` BIOS does. 
Therefore, the PCI address space starting at 0x000C0000 never gets initialized and will always return `0xFF` when read and will deny any writes.

I don't think it is worth the effort to update the `legacy` BIOS, but a note or statement in the user docs and possibly the `.bochsrc` file should be added.

**Comment by fysnet** [comment]
> The unusable combinations should cause a panic.

But they do not. Try:
```
romimage: file=C:/bochs/bochs/bios/BIOS-bochs-legacy
vgaromimage: file=C:/bochs/bochs/bios/VGABIOS-lgpl-latest-cirrus
vga: extension=cirrus, update_freq=10
pci: enabled=1, chipset=i440fx, slot1=cirrus
```
There is no panic, and nothing is displayed to the simulated screen.

**Comment by vruppert** [comment]
I have now added a panic in the legacy BIOS for this case (checking ROM signature). The only way to use a PCI VGA adapter with the legacy BIOS is to specify the VGABIOS additionally with one of the "optromimage" options.
