### ISSUE TITLE
Bochs does not support SVM's VM_ CR MSR and INIT redirect

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#163]
![截图_2023-12-09_12-22-03](https://github.com/bochs-emu/Bochs/assets/3366897/e6f38f87-158b-4ae5-907e-640c48af170e)

**Comment by stlintel** [comment]
If you want to use it for 'disable SVM' bit -> just disable SVM instead :)
If you want just not to fail on it -> why would we implement it ?
ignore_bad_msr will make it read always as zero which is fine, no ?

**Comment by lgj1107** [comment]
When all CPUs are in GUEST mode, BSP sends an INIT signal to AP. After AP CPU VMEXIT, it cannot redirect INIT to # SX. I don't know if it is related to VM_ CR has not been implemented.

**Comment by stlintel** [comment]
Don't see any relation ...
But pay into attention SVM support is experimental, no promise it works.
I will be happy to make it batter but I am clearly less expert about how AMD chips work

**Comment by stlintel** [comment]
Sorry, no plans to implement Subj unless there is clear reason that it helps somewhere (backed up with example)

**Comment by lgj1107** [comment]
I hope BOCHS can implement the INIT Redirect function of VM_CR in SVM. Without this MSR, the guest's INIT signal cannot be "consumed" and will remain in a pending state.  For more information, please see AMD manual (24593-340.PDF) 15.21.8 INIT Support.  Thank you.

**Comment by stlintel** [comment]
> I hope BOCHS can implement the INIT Redirect function of VM_CR in SVM. Without this MSR, the guest's INIT signal cannot be "consumed" and will remain in a pending state. For more information, please see AMD manual (24593-340.PDF) 15.21.8 INIT Support. Thank you.

INIT redirect was not always available. When I implemented SVM into Bochs it didn't exists yet. Why can't you pretend you are on CPU which doesn't support INIT Redirect and do INIT VMEXIT ?
<img width="254" alt="image" src="https://github.com/bochs-emu/Bochs/assets/77239907/04cbfff9-b149-463e-98d4-4c5ddadbbce7">
All modes but the last one are supported ?

I just not even sure Bochs supports #SX exception and many other things.

**Comment by lgj1107** [comment]
I haven't figured out how to do this test yet, because without INIT redirection, setting GIF to 1 will cause RESET in root. In guest, INIT VMEXIT will occur repeatedly.

**Comment by stlintel** [comment]
Please consider PR 
Implemented SVM VM_CR_MSR and INIT redirection feature #220

does it work ?
you can try to code review as well

**Comment by lgj1107** [comment]
>mov	ecx,VM_CR
	xor	edx,edx
	mov	eax,2            
	wrmsr

The WRMSR triggered #GP. Only the R_INIT bit was set here.

> 00197582262i[CPU1  ] CPU 1 started up at 5000:00000000 by APIC
00197582295i[APIC1 ] warning: write to read-only APIC register 0x20
_**00197582304e[CPU1  ] VM_CR_MSR: attempt to set SVMDIS when EFER.SVME=1
00197584605e[CPU0  ] VM_CR_MSR: attempt to set SVMDIS when EFER.SVME=1**_
00942450000p[XGUI  ] >>PANIC<< POWER button turned off.
00942450000i[CPU0  ] CPU is in protected mode (active)
00942450000i[CPU0  ] CS.mode = 32 bit
00942450000i[CPU0  ] SS.mode = 32 bit
00942450000i[CPU0  ] EFER   = 0x00001000
00942450000i[CPU0  ] | EAX=00000230  EBX=00000000  ECX=c0010114  EDX=00000000
00942450000i[CPU0  ] | ESP=0010efec  EBP=00000000  ESI=fee00020  EDI=000b8e70
00942450000i[CPU0  ] | IOPL=0 id vip vif ac vm rf nt of df if tf SF zf AF pf CF
00942450000i[CPU0  ] | SEG sltr(index|ti|rpl)     base    limit G D
00942450000i[CPU0  ] |  CS:0008( 0001| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU0  ] |  DS:0010( 0002| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU0  ] |  SS:0010( 0002| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU0  ] |  ES:0010( 0002| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU0  ] |  FS:0000( 0005| 0|  0) 00000000 0000ffff 0 0
00942450000i[CPU0  ] |  GS:0000( 0005| 0|  0) 00000000 0000ffff 0 0
00942450000i[CPU0  ] | EIP=00100698 (00100698)
00942450000i[CPU0  ] | CR0=0xe0000011 CR2=0x00000000
00942450000i[CPU0  ] | CR3=0x01000000 CR4=0x00000010
00942450000i[CPU0  ] 0x0000000000100698>> jmp .-2 (0x00100698) : EBFE
00942450000i[CPU1  ] CPU is in protected mode (active)
00942450000i[CPU1  ] CS.mode = 32 bit
00942450000i[CPU1  ] SS.mode = 32 bit
00942450000i[CPU1  ] EFER   = 0x00001000
00942450000i[CPU1  ] | EAX=01000230  EBX=01000000  ECX=c0010114  EDX=00000000
00942450000i[CPU1  ] | ESP=00117fe8  EBP=00000000  ESI=fee00020  EDI=000b8e70
00942450000i[CPU1  ] | IOPL=0 id vip vif ac vm rf nt of df if tf SF zf AF pf CF
00942450000i[CPU1  ] | SEG sltr(index|ti|rpl)     base    limit G D
00942450000i[CPU1  ] |  CS:0008( 0001| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU1  ] |  DS:0010( 0002| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU1  ] |  SS:0010( 0002| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU1  ] |  ES:0010( 0002| 0|  0) 00000000 ffffffff 1 1
00942450000i[CPU1  ] |  FS:0000( 0000| 0|  0) 00000000 0000ffff 0 0
00942450000i[CPU1  ] |  GS:0000( 0000| 0|  0) 00000000 0000ffff 0 0
00942450000i[CPU1  ] | EIP=00100698 (00100698)
00942450000i[CPU1  ] | CR0=0xe0000011 CR2=0x00000000
00942450000i[CPU1  ] | CR3=0x01000000 CR4=0x00000010
00942450000i[CPU1  ] 0x0000000000100698>> jmp .-2 (0x00100698) : EBFE

**Comment by lgj1107** [comment]
After masking the following code:
  if (BX_CPU_THIS_PTR efer.get_SVME()) {
    BX_ERROR(("VM_CR_MSR: attempt to set SVMDIS when EFER.SVME=1"));
    exception(BX_GP_EXCEPTION, 0);

In guest, BSP sends INIT signal to AP.AP CPU INIT-VMEXIT.
but The AP CPU is not redirected to #SX(After executing the STGI instruction, it should immediately redirect to #SX), and there should be no waiting for SIPI status here.  AMD is completely different from Intel.

> 01179150000i[CPU1  ] CPU is in real mode (waiting for SIPI)
01179150000i[CPU1  ] CS.mode = 16 bit
01179150000i[CPU1  ] SS.mode = 16 bit
01179150000i[CPU1  ] EFER   = 0x00000000
01179150000i[CPU1  ] | EAX=00000000  EBX=00000000  ECX=00000000  EDX=00000000
01179150000i[CPU1  ] | ESP=00000000  EBP=00000000  ESI=00000000  EDI=00000000
01179150000i[CPU1  ] | IOPL=0 id vip vif ac vm rf nt of df if tf sf zf af pf cf
01179150000i[CPU1  ] | SEG sltr(index|ti|rpl)     base    limit G D
01179150000i[CPU1  ] |  CS:f000( 1e00| 0|  0) ffff0000 0000ffff 0 0
01179150000i[CPU1  ] |  DS:0000( 0000| 0|  0) 00000000 0000ffff 0 0
01179150000i[CPU1  ] |  SS:0000( 0000| 0|  0) 00000000 0000ffff 0 0
01179150000i[CPU1  ] |  ES:0000( 0000| 0|  0) 00000000 0000ffff 0 0
01179150000i[CPU1  ] |  FS:0000( 0000| 0|  0) 00000000 0000ffff 0 0
01179150000i[CPU1  ] |  GS:0000( 0000| 0|  0) 00000000 0000ffff 0 0
01179150000i[CPU1  ] | EIP=0000fff0 (0000fff0)
01179150000i[CPU1  ] | CR0=0x60000010 CR2=0x00000000
01179150000i[CPU1  ] | CR3=0x00000000 CR4=0x00000000
01179150000i[CPU1  ] 0x000000000000fff0>> jmpf 0xf000:e05b : EA5BE000F0

**Comment by stlintel** [comment]
WAIT FOR SIPI state set immediately on reset for all application processors

```
#if BX_SUPPORT_SMP
  // notice if I'm the bootstrap processor.  If not, do the equivalent of
  // a HALT instruction.
  int apic_id = lapic->get_id();
  if (BX_BOOTSTRAP_PROCESSOR == apic_id) {
    // boot normally
    BX_CPU_THIS_PTR msr.apicbase |=  0x100; /* set bit 8 BSP */
    BX_INFO(("CPU[%d] is the bootstrap processor", apic_id));
  } else {
    // it's an application processor, halt until IPI is heard.
    BX_CPU_THIS_PTR msr.apicbase &= ~0x100; /* clear bit 8 BSP */
    BX_INFO(("CPU[%d] is an application processor. Halting until SIPI.", apic_id));
    enter_sleep_state(BX_ACTIVITY_STATE_WAIT_FOR_SIPI);
  }
#endif

```

You wanna set up of MP system is completely different between Intel and AMD. 
I doubt they are so different. 
Can you point me to the docs to explain how it should work ?

Current processor in WAIT_FOR_SIPI can't get any event:

```
  if (BX_CPU_THIS_PTR activity_state == BX_ACTIVITY_STATE_WAIT_FOR_SIPI) {
    // HALT condition remains, return so other CPUs have a chance
#if BX_DEBUGGER
    BX_CPU_THIS_PTR stop_reason = STOP_CPU_HALTED;
#endif
    return 1; // Return to caller of cpu_loop.
  }
```
but SIPI

```
void BX_CPU_C::deliver_SIPI(unsigned vector)
{
  if (BX_CPU_THIS_PTR activity_state == BX_ACTIVITY_STATE_WAIT_FOR_SIPI) {
#if BX_SUPPORT_VMX
    if (BX_CPU_THIS_PTR in_vmx_guest)
      VMexit(VMX_VMEXIT_SIPI, vector);
#endif
    BX_CPU_THIS_PTR activity_state = BX_ACTIVITY_STATE_ACTIVE;
    RIP = 0;
    load_seg_reg(&BX_CPU_THIS_PTR sregs[BX_SEG_REG_CS], vector*0x100);
    unmask_event(BX_EVENT_INIT | BX_EVENT_SMI | BX_EVENT_NMI);
    BX_INFO(("CPU %d started up at %04X:%08X by APIC",
                   BX_CPU_THIS_PTR bx_cpuid, vector*0x100, EIP));
  } else {
    BX_INFO(("CPU %d started up by APIC, but was not halted at that time", BX_CPU_THIS_PTR bx_cpuid));
  }
}
```

You say in AMD you send him INIT instead ?
Can you point me onto docs which explain that ?

**Comment by stlintel** [comment]
Just a guess -> WAIT_FOR_SIPI can be raised only in one place, from RESET method which is result of taking INIT.
So it means you just have taken the INIT signal instead of being redirected here:

```
  if (is_unmasked_event_pending(BX_EVENT_INIT) && SVM_GIF) {
#if BX_SUPPORT_SVM
    if (BX_CPU_THIS_PTR in_svm_guest) {
      if (SVM_INTERCEPT(SVM_INTERCEPT0_INIT)) Svm_Vmexit(SVM_VMEXIT_INIT); // INIT is still pending
      if (BX_CPU_THIS_PTR msr.svm_vm_cr & BX_VM_CR_MSR_INIT_REDIRECT_MASK) {
        clear_event(BX_EVENT_INIT);     // INIT is no longer pending
        BX_INFO(("SVM INIT Redirect to #SX"));
        exception(BX_SX_EXCEPTION, 1);  // The only error code is 1, and indicates redirection of INIT
      }
    }
#endif
```

Can you add some debug BX_INFO messages there and tell where did it go ?
What was the value of the MSR there (really 0x2?) ?
"SVM INIT Redirect to #SX" was not printed ?

**Comment by stlintel** [comment]
Do you have image working on real AMD HW ?
if yes - please attach it here and I will make it working in Bochs as well

**Comment by lgj1107** [comment]
What I mean by different is this:
The INTEL VMX decomposes INIT-SIPI into two parts for processing

<img width="1089" alt="intel-init" src="https://github.com/bochs-emu/Bochs/assets/3366897/2336ce28-4aee-4105-a0e2-21e4f6c46f74">
 

AMD SVM uses INIT intercept and R_INIT to process INIT signals. SIPI does not have an intercept option.

After INIT-VMEXIT occurs in VMX, the INIT signal is consumed.
After the SVM generates INIT-VMEXIT, the INIT signal will remain in the PENDING state, either being redirected to #SX (consumed) or becoming active (RESET CPU).
My English is a little bit poor.

**Comment by lgj1107** [comment]
Wait a minute.  I screwed up my hard drive.

**Comment by lgj1107** [comment]
[a.zip](https://github.com/bochs-emu/Bochs/files/13936793/a.zip)

2700x:
<img width="1250" alt="2700" src="https://github.com/bochs-emu/Bochs/assets/3366897/dafbb4e4-6d9c-4272-8fac-5b0383277bdf">

**Comment by stlintel** [comment]
Fixed in the PR
Now it looks like this on my Bochs:

<img width="541" alt="image" src="https://github.com/bochs-emu/Bochs/assets/77239907/480c9a38-3228-4953-8d03-f5bd397b50da">

**Comment by lgj1107** [comment]
I tested on 2700x, 5800K, and FX7500, and the results were the same.  However, this only tested the situation where the BSP sends an INIT signal to the AP in GUEST MODE.
During the testing process, it was found that AMD did not seem to comply with the INIT provisions in the INTEL MP specification. (Bochs also did not follow this specification.)

MultiProcessor Specification Version 1.4

> 3.7.2 System-wide INIT
The system-wide INIT, as defined by this specification, refers to a soft or warm reset that
initializes only portions of the processor. This type of reset initializes the microprocessor in such a
way that the reset does not corrupt any pending cycles, but waits instead for a cycle boundary, and
does not invalidate the contents of caches and floating point registers. This type of reset request is
connected to the INIT signal of newer processors, such as the Pentium processors. On Intel486
processors, the RESET pin is used for this function, as well as for hard resets, but the RESET pin
does not provide the advantages of the INIT pin. There are many possible ways to assert a soft
reset, including:
• A write either to a port of the 8042 Keyboard Controller or to some other port provided for the
same purpose by a chipset.
• A shutdown special bus cycle. Usually a chipset senses a shutdown cycle and asserts a soft
reset to the processor.
In a compliant system, the standard PC/AT-platform resets mentioned above, both hard and soft,
must be directed to all processors in the system, except in the case of fault-tolerant MP systems, in
which a soft reset may be handled on a per-processor basis.

**Comment by stlintel** [comment]
Let's deal with it later once we have enough ROI to do so, agree ?
I mean we need to see smth that doesn't work otherwise and this smth is important.
