### ISSUE TITLE
Hang in Quake

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#171]
After Quake game is started, it hangs:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/18697c26-f478-4a0f-988d-479023cd7cbc)

Most likely, hang is caused by bugs in VBE support.
It is possible to avoid hang by launching `univbe` before `quake`.
_(`univbe` is included in test image, but commented out in `autoexec.bat`)_

Test files: [quake.zip](https://github.com/bochs-emu/Bochs/files/13689517/quake.zip).

Version: 7641d136148dca90c98876a26b83bcaf4e5b1f89.

**Comment by vruppert** [comment]
I can confirm that the "Bochs VBE" display hangs at this point. It doesn't happen with the Cirrus and Banshee adapters.

**Comment by vruppert** [comment]
Update: It's definitely a VGABIOS issue. When I set the VGA extension to "none", Quake works fine. The Cirrus and Banshee VBE also don't make trouble, but Quake doesn't seem to use the available higher resolutions. After fixing some issues in the VGABIOS code, it exits with an abnormal program termination and DOS is unusable.

**Comment by Vort** [comment]
UniVBE comes with `vbetest` utility. And it also crashes.
Maybe it will be easier to track problem with it: [univbe.zip](https://github.com/bochs-emu/Bochs/files/13693306/univbe.zip).

**Comment by vruppert** [comment]
In the log file I have found some CPU error messages related to protected mode, so I guess the INT 10h VBE stuff is called from it. The Cirrus and Banshee VBE stuff is completely ASM code and it seems to work. The Bochs VBE stuff is still a mix of C and ASM code and the failing function is written in C. I guess the data is copied to a wrong address causing protection faults. Some more investigation is required.

**Comment by vruppert** [comment]
Update: I have now rewritten the VBE functions 0x00 and 0x01 in assembler. Quake now starts normally and VBE 8 bpp modes are now available in video options. The resolution changes as expected, but the colors are wrong. The binaries are available in the VGABIOS repository. I intend to update the files in the Bochs bios folder when the remaining issues are fixed.

**Comment by Vort** [comment]
I confirm that hang is gone. Thanks.
Should this issue be closed now or when colors will be fixed / when binary will be copied?

**Comment by sskras** [comment]
> Update: I have now rewritten the VBE functions 0x00 and 0x01 in assembler. Quake now starts normally and VBE 8 bpp modes are now available in video options. The resolution changes as expected, but the colors are wrong. The binaries are available in the VGABIOS repository. I intend to update the files in the Bochs bios folder when the remaining issues are fixed.

@vruppert, please excuse me my interest.

Would it be possible to rewrite it back in C? Would some specific C compiler be needed for that?

**Comment by vruppert** [comment]
I have now fixed a bug in get/set palette data, but it doesn't help in Quake. Currently I have no idea what can go wrong with the colors. I still have to add some missing stuff in VBE function 0x00 and then I intend to update the binaries in the Bochs tree. When this is done, I think this issue can be closed,
The SeaBIOS project has also a VGABIOS written in C. I think it is based on an older version of our VGABIOS. For the remaining Quake issue it doesn't really help. There is no hang or crash, but there are no VBE modes listed in video options. That's why I cannot say whether or not their implementation of VBE set palette would work correctly.

**Comment by Vort** [comment]
> but it doesn't help in Quake

Problem is visible not only in Quake, but also in Windows XP with 8bpp mode:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/8ec840ee-6b1c-428f-96a8-affa3d3d5166)

**Comment by Vort** [comment]
@vruppert, I figured out what's wrong with colors.
VBE standard is just confusing.
I found better explanation of how palette data should be organized: [69030BG.zip](https://github.com/bochs-emu/Bochs/files/13753623/69030BG.zip).

![image](https://github.com/bochs-emu/Bochs/assets/1242858/1d927846-eecd-402f-a75f-102a39b325de)

So it is not RGBA, but ABGR instead.
Such change fixes colors in Quake:

```diff
diff --git a/vgabios/vgabios.c b/vgabios/vgabios.c
index 0ba942a..6dec499 100644
--- a/vgabios/vgabios.c
+++ b/vgabios/vgabios.c
@@ -4781,13 +4781,13 @@ vbe_set_palette_data:
   mov   dx, # VGAREG_DAC_DATA
   cld
 vbe_set_dac_loop:
-  inc   si
-  lodsb
+  mov   al, [si+2]
   out   dx, al
-  lodsb
+  mov   al, [si+1]
   out   dx, al
-  lodsb
+  mov   al, [si]
   out   dx, al
+  add   si, #4
   loop  vbe_set_dac_loop
   pop   ds
   pop   si 
```

**Comment by vruppert** [comment]
In the meantime I also found out the order of colors described in the VBE 2.0 spec is wrong. I have now applied a similar set of changes (also modified get function) to the VGABIOS repository.

**Comment by vruppert** [comment]
Small addition: Quake now looks okay with Bochs VBE and Banshee, but Cirrus doesn't provide VBE modes yet. Now I'll review this code, too. The VBE get/set palette data code is shared between all there extensions, so I think it's a bug in function 0x00 or 0x01.

**Comment by Vort** [comment]
I confirm that colors in Quake and Windows XP look good with https://github.com/bochs-emu/VGABIOS/commit/b3ddbb59cf7b0bea7c244d39946ec1a5aa64e252.
