### ISSUE TITLE
Visual artifacts in Windows XP with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#172]
After recent changes, rendering of Windows XP user interface with Voodoo 3 became worse.
Most likely, more artifacts start to appear after 438fd787c317230e4866d1e39fa75a67533706e2.
Before:
![vxp1](https://github.com/bochs-emu/Bochs/assets/1242858/d0579f0e-5568-4481-a14b-ad6fe7d20d74)
After:
![vxp2](https://github.com/bochs-emu/Bochs/assets/1242858/5b13ae51-f302-4362-b3c4-1d9ef401ce39)

Logs now contain lines like
`[VOODOO] bx_banshee_c::mem_read unsupported length 4`
and
`[VOODOO] bx_banshee_c::mem_write unsupported length 8`

First one looks like effect of missing break here:
https://github.com/bochs-emu/Bochs/blob/e67fb33443fb6e0bf571efa25cb4c08e327b156f/bochs/iodev/display/banshee.cc#L842-L845

As for `len` = `8` problem I have no idea yet.

Version: e67fb33443fb6e0bf571efa25cb4c08e327b156f

**Comment by Vort** [comment]
With fixes from #173, results looks even better than before:
![vxp3](https://github.com/bochs-emu/Bochs/assets/1242858/002551a2-c68e-47a9-af12-57e4976f0155)

**Comment by stlintel** [comment]
I have added missing break and also tried to handle len=8 as well. Can you check now ?

**Comment by Vort** [comment]
> I have added missing break and also tried to handle len=8 as well. Can you check now ?

I saw no reads from ROM with len = 8, so there should be no differences.
As for `break`, it will just silence wrong error message, so it is good.

**Comment by Vort** [comment]
Rechecked 02704120a309c3db0bfab1d61d88e0136f49f37e - works good.
