### ISSUE TITLE
Artifacts when moving window with Voodoo 3 drivers

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#182]
When window of guest OS is moved to the right, its right edge becomes corrupted.
Effect can be observed with screen depths of 32 and 16 bpp on Windows 95 and Windows XP.

![bochs_window_move](https://github.com/bochs-emu/Bochs/assets/1242858/c5cf119f-467f-4e8b-b2d4-54b37b4d5d29)

It happens because of incorrect implementation of backward bitblt.
`src_base` and `dst_base` always point to the start of pixel, even when copy needs to happen from right to left.
Which means that with 4 bytes per pixel only 1 byte of last pixel gets copied.

Here is how I was able to fix this problem:
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index a6c4f2d6c..58460e773 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -1881,6 +1881,7 @@ void bx_banshee_c::blt_screen_to_screen()
   Bit8u *dst_ptr, *dst_ptr1, *src_ptr1;
   Bit8u pxpack = (BLT.reg[blt_srcFormat] >> 22) & 3;
   int dpxsize = (BLT.dst_fmt > 1) ? (BLT.dst_fmt - 1) : 1;
+  int backward_adj = BLT.x_dir ? dpxsize - 1 : 0;
   Bit8u *color;
   Bit8u colorkey_en = BLT.reg[blt_commandExtra] & 3;
   int spitch;
@@ -1962,7 +1963,7 @@ void bx_banshee_c::blt_screen_to_screen()
         if (colorkey_en & 2) {
           rop |= blt_colorkey_check(dst_ptr1, abs(dpxsize), 1);
         }
-        BLT.rop_fn[rop](dst_ptr1, src_ptr1, dpitch, spitch, abs(dpxsize), 1);
+        BLT.rop_fn[rop](dst_ptr1 + backward_adj, src_ptr1 + backward_adj, dpitch, spitch, abs(dpxsize), 1);
         src_ptr1 += dpxsize;
         dst_ptr1 += dpxsize;
       } while (--ncols);
@@ -1971,7 +1972,7 @@ void bx_banshee_c::blt_screen_to_screen()
     } while (--nrows);
   } else {
     src_ptr += (sy * abs(spitch) + sx * abs(dpxsize));
-    BLT.rop_fn[0](dst_ptr, src_ptr, dpitch, spitch, w * abs(dpxsize), h);
+    BLT.rop_fn[0](dst_ptr + backward_adj, src_ptr + backward_adj, dpitch, spitch, w * abs(dpxsize), h);
   }
   blt_complete();
   BX_UNLOCK(render_mutex); 
```

However I'm not sure if my change is correct and fast enough.
Probably better solutions exist.

Version: 54e88eee928a04881fd9f59b39b2f8f2e9decc93

**Comment by Vort** [comment]
> I cannot reproduce this issue here. I have tested moving window on Win95, Win98 and Win98SE, but I don't see artifacts on the screen.

First of all, corruption is subtle: instead of being black, rightmost pixels of window turns yellow.
Second, it happens only with high bit depths.
Third, to reproduce this problem on Windows 95, window should be moved straight to the right - there should be no movement on Y axis.
Such movement can be produced with the help of context menu and keyboard arrows, like on this video:

https://github.com/bochs-emu/Bochs/assets/1242858/88995e13-ee50-4452-827e-593d8bd3a6ed

On Windows XP reproduction is easier, because window movement is smooth, while on Windows 95 position changes abruptly.

**Comment by vruppert** [comment]
I don't see an issue in this video. The 2D originally is a part of the Cirrus code. I moved it to bitblt.h to share it with the Banshee code.

**Comment by Vort** [comment]
> I don't see an issue in this video

I said edge is yellow, but it is green instead, sorry.
I don't know how to visualize it better:
![bochs_win_move](https://github.com/bochs-emu/Bochs/assets/1242858/a8cdb651-2522-4a3d-af68-ccc42f085c91)

**Comment by vruppert** [comment]
Okay, now I understand what's going on. The source and destination pointers always use the first byte of the rightmost pixel in backwards mode, This is okay for comparing pixels, but not for copying data in > 8 bpp modes. Unfortunately I don't this effect, when I do the tests here. It also should occur with Cirrus, since the 2D implementation is similar. I think I have to do some more tests, before I apply a bugfix.

**Comment by Vort** [comment]
> It also should occur with Cirrus, since the 2D implementation is similar.

Windows 95 Cirrus driver makes backward blt with `bitblt.pixelwidth = 1` even for 24 bpp mode:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/884f14b5-998e-47cf-8644-94ae76367bf5)

That's why no problem appears.
I will check other OSes.

**Comment by Vort** [comment]
> Unfortunately I don't see this effect, when I do the tests here.

Maybe because of different drivers?
For Windows 95 and 98 I was using [voodoo3_10700.zip](https://github.com/bochs-emu/Bochs/files/13739633/voodoo3_10700.zip), installed from `driver9x` directory, without launching `setup.exe`.
Also here is how I was moving window with keyboard arrows:
1. For Display Properties window: Alt, Down, Enter, Right, Enter.
2. For My Computer window: Alt, Left, Down, Down, Enter, Right, Enter.

> I will check other OSes.

Windows 98 and Windows XP use `bitblt.pixelwidth = 1` as well.
Windows XP makes blt in several calls however, because of non-rectangular shape of window.

**Comment by vruppert** [comment]
Now I also got some artifacts with XP and Banshee driver when I move around a window with the mouse. There were blue vertical lines within the white background of the window. They disappeared after adding some code similar to your suggestion. Now I'll continue with VGABIOS changes related to the Quake issue.
