### ISSUE TITLE
Visual artifacts in Tomb Raider demo with Voodoo

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#183]
When Tomb Raider demo is launched with Voodoo card, various visual artifacts appear.
Most noticeably, some parts of Lara Croft model are missing:
![bochs_tr_bug](https://github.com/bochs-emu/Bochs/assets/1242858/6958ea95-8a9d-4d0a-af1b-4ba168a89f5a)

These problems happen because of inappropriate calls to `fifo_reset`, which results in some commands and data for video card being lost.

When this line is removed:
```diff
diff --git a/bochs/iodev/display/voodoo_func.h b/bochs/iodev/display/voodoo_func.h
index 768765f9a..5dec69c61 100644
--- a/bochs/iodev/display/voodoo_func.h
+++ b/bochs/iodev/display/voodoo_func.h
@@ -1311,7 +1311,7 @@ void recompute_video_memory(voodoo_state *v)
   }
 
   /* reset the FIFO */
-  fifo_reset(&v->fbi.fifo);
+  //fifo_reset(&v->fbi.fifo);
   if (fifo_empty_locked(&v->pci.fifo)) v->pci.op_pending = 0;
 
   /* reset our front/back buffers if they are out of range */ 
```
, game starts to behave almost perfectly:
![bochs_tr_fixed](https://github.com/bochs-emu/Bochs/assets/1242858/9448598d-9d80-4039-91c7-dc52cf5405d7)

Of course, this is not proper fix - there was a reason why someone placed `fifo_reset` call there.
But it may give hints for making more correct solution.

This issue was extracted from #67 to focus on one particular problem in one particular game.

Test files: [TR2.zip](https://github.com/bochs-emu/Bochs/files/13724759/TR2.zip).

Version: fc919cd13208ee359b598aa44180e4a330ca81ba

**Comment by vruppert** [comment]
According to the specs the FIFO reset should happen if the corresponding bit in the fbiInit0 register is set. I think recompute_video_memory() should not do that. I also had a look at the voodoo code of PCem - there is no FIFO reset at all.

**Comment by Vort** [comment]
Maybe code related to memory FIFO should be extracted from `recompute_video_memory` into separate function and this new function should be called after `v->fbi.fifo.enabled = FBIINIT0_ENABLE_MEMORY_FIFO(data);`.

**Comment by Vort** [comment]
@vruppert if you stumble upon black screen after selecting New Game, it happens because of race condition between `update_pens()` (Main Thread) and `case clutData:` (fifo_thread).

**Comment by vruppert** [comment]
I decided to use your suggested change until we find a better solution. The FIFO handling must be observed. I also noticed some hangs, but Bochs always hangs on exit. I had to modify the destructor to fix this. The other hangs need some more investigation.

**Comment by Vort** [comment]
Should I make separate issue about `clut`-related problem?

**Comment by vruppert** [comment]
I'll have at the remaining hangs tomorrow. A separate issue is not yet required.

**Comment by Vort** [comment]
It is not hang in fact.
Polygons are rendered, but because of wrong clut, screen is black.
More precisely, screen is going black after menu item is selected and then fails to go back to normal because of bug.
It happens only sometimes and I don't know if it will reproduce with your build and hardware.
But problems with thread safety in that place are understandable so I think it is possible to fix them even without reproduction (by adding one more mutex maybe).

**Comment by vruppert** [comment]
After hopefully fixing the hang on exit that occurred with the pthreads library, but not on Windows, I mode some tests, but the black screen didn't appear here yet. I'll have a closer look at the code to find out what could happen.

**Comment by vruppert** [comment]
Please try this one. The issue still didn't appear here.

[voodoo-patch.txt](https://github.com/bochs-emu/Bochs/files/13792932/voodoo-patch.txt)
``

**Comment by vruppert** [comment]
I have now applied the patch and I'll have a look at the issues you mentioned later.

**Comment by Vort** [comment]
I extracted problem with flickering triangles into separate issue: #246.
