### ISSUE TITLE
Hang in Captain Dynamo

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#186]
Shortly after Captain Dynamo game starts, it hangs, on this screen:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/a16340e8-8df7-46e7-8203-f240975e229d)

This is how animation should look:
https://www.youtube.com/watch?v=62b05QOdr3k

It works ok in DOSBox and VirtualBox.

Test files: [dynamo.zip](https://github.com/bochs-emu/Bochs/files/13728146/dynamo.zip)
Version: 75ea1c2222a825e99e6de2f976ed41de55b021ad

**Comment by Vort** [comment]
I decided to look into `DYN.EXE` first. It is compressed, so I uncompressed it for further debugging.
Right from the start it sets up timer. Problem is that timer interrupt never triggers.
I reproduced this behaviour with smaller program ([timer.zip](https://github.com/bochs-emu/Bochs/files/13857312/timer.zip)):
```asm
org 100h

start:
  push ds
  cli
  mov al, 0x3E
  out 0x43, al
  mov al, 0xEC
  out 0x40, al
  mov al, 0x5C
  out 0x40, al
  push ds
  xor ax, ax
  mov ds, ax
  les bx, [0x20]
  mov word [0x20], handler
  mov [0x22], cs
  pop ds
  mov [oldhandler1], bx
  mov [oldhandler2], es
  sti
  @@:
  cmp [ticks], 40
  jnz @b
  cli
  mov al, 0x3E
  out 0x43, al
  xor al, al
  out 0x40, al
  out 0x40, al
  les bx, dword [oldhandler1]
  xor ax, ax
  mov ds, ax
  mov word [0x20], bx
  mov [0x22], es
  sti
  pop ds
  ret

handler:
  push ax
  inc [cs:ticks]
  mov al, 0x20
  out 0x20, al
  pop ax
  iret

ticks dw 0
oldhandler1 dw 0
oldhandler2 dw 0
```

**Comment by stlintel** [comment]
Talking about smaller program (from timer.zip) - what is expected behavior and how do you see it ?
what Bochs does ?
What is supposed to trigger timer interrupt ?
I am CPU person and not sure how interrupts should work without APIC ...

**Comment by Vort** [comment]
> what is expected behavior

Program should wait several seconds and exit.
This is how it works in DOSBox.

> what Bochs does ?

In Bochs program hangs.

> What is supposed to trigger timer interrupt ?

Timer hardware.

**Comment by stlintel** [comment]
Sorry for my badness. 
Cn you point me to some doc about the Timer Hardware ?
How it is set up and how it delivers interrupt to CPU. Though PIC, I guess ?

**Comment by stlintel** [comment]
I don't have any DOS image around so I run it within Win95 image I have.
The timer.com started waited for ~1s and quit.
May be the issue was already fixed ?
Remember we had optimizations problem with similar symptoms (timer not triggered) in frogger game and I have fixed it.
Can you retry ?

**Comment by stlintel** [comment]
Took DOS image from Dynamo game above. It is stuck. So Win95 connects PIT to PIC better than DOS ...

**Comment by Vort** [comment]
> Remember we had optimizations problem with similar symptoms (timer not triggered) in frogger game and I have fixed it.

I retested other hangs when Frogger was fixed, they stayed in place.

> May be the issue was already fixed ?

No, I tested latest version.
There may be differences because of compiler settings, but I doubt it.

> The timer.com started waited for ~1s and quit.

I confirm that it works fine in Win 95.
But Windows may emulate hardware.

> I don't have any DOS image around

I made floppy image with `timer.com` and some utilities: [Timer.zip](https://github.com/bochs-emu/Bochs/files/13863834/Timer.zip).
`timer.com` can be rebuilt with `..\fasm\fasm timer.asm` command.

**Comment by stlintel** [comment]
Yes, the problem exists with DOS guest. I don't know what is going on with PIT because it is not my area of expertise, just can't say   how it is supposed to work (entire dataflow).

I enabled debug prints to see what happening and this is the last meaningful prints I saw:

```
04921322392i[PIT   ] irq_handler 1
04926157764i[PIT   ] write to port 0x0043, value = 0x3e
04926157764i[PIT81 ] Control Word Write.
04926157764i[PIT81 ] Counter Program command.  SC=0, RW=3, M=7, BCD=0
04926157764i[PIT81 ] Setting read_state to LSB_mult
04926157764i[PIT   ] irq_handler 1
04926157768i[PIT   ] write to port 0x0040, value = 0xec
04926157768i[PIT81 ] Write Initial Count: counter=0, count=236
04926157770i[PIT   ] write to port 0x0040, value = 0x5c
04926157770i[PIT81 ] Write Initial Count: counter=0, count=92
```

these are triggered by this asm:

```
mov al, 0x3E
  out 0x43, al
  xor al, al
  out 0x40, al
  out 0x40, al
```

what supposed to happen next I don't know.
timer should trigger event which should call pit82c54 out handler (function PIT::irq_handler) and raise IRQ ?
well, don't know. Need someone who understands how this stuff supposed to work.

**Comment by Vort** [comment]
I have idea of how to fix it:
```diff
diff --git a/bochs/iodev/pit82c54.cc b/bochs/iodev/pit82c54.cc
index c5163f2d4..a35610bb3 100644
--- a/bochs/iodev/pit82c54.cc
+++ b/bochs/iodev/pit82c54.cc
@@ -724,6 +724,8 @@ void pit_82C54::write(Bit8u address, Bit8u data)
           thisctr.rw_mode=RW;
           thisctr.bcd_mode=(BCD > 0);
           thisctr.mode=M;
+          if (thisctr.mode > 5)
+            thisctr.mode -= 4;
           switch(RW) {
           case 0x1:
             BX_DEBUG(("Setting read_state to LSB")); 
```

**Comment by stlintel** [comment]
Looks like you are right !
Merging to master
