### ISSUE TITLE
No text in SimCity

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#187]
After loading SimCity game and clicking START NEW CITY, screen without text appears:
![bochs_simcity](https://github.com/bochs-emu/Bochs/assets/1242858/bd6908f9-a0d0-4b7d-8196-e353d4cbf02e)

This is how it should look:
![vbox_simcity](https://github.com/bochs-emu/Bochs/assets/1242858/c0529b8f-41ef-4b9c-818e-04abd2e04b08)

Test files: [SimCity.zip](https://github.com/bochs-emu/Bochs/files/13740840/SimCity.zip)
Version: b63b1225a8507f7677e8576c019a3d069d9ad0c0

**Comment by vruppert** [comment]
I tried your image and I don't see an issue. The text is displayed correctly.

**Comment by Vort** [comment]
Oops, my mistake, sorry.
I was using latest [VGABIOS-lgpl-latest.bin](https://github.com/bochs-emu/VGABIOS/blob/master/vgabios/VGABIOS-lgpl-latest.bin).
So it's a very recent regression.

**Comment by Vort** [comment]
Regression happened because of commit https://github.com/bochs-emu/VGABIOS/commit/1bff26a9beebb5e8d117c40b3ce6abf085fe1f2d.

**Comment by vruppert** [comment]
I can confirm this issue with the debug version only - VGABIOS-lgpl-latest.bin works correctly. I'll have a closer look at the printf() stuff, since the modified VBE code isn't used by this game.

**Comment by Vort** [comment]
> I'll have a closer look at the printf() stuff, since the modified VBE code isn't used by this game.

Glitch appears not because of `printf`, but because of `push bp` and `pop  bp` additions:
https://github.com/bochs-emu/VGABIOS/blob/b3ddbb59cf7b0bea7c244d39946ec1a5aa64e252/vgabios/vgabios.c#L317
https://github.com/bochs-emu/VGABIOS/blob/b3ddbb59cf7b0bea7c244d39946ec1a5aa64e252/vgabios/vgabios.c#L431

**Comment by vruppert** [comment]
The font functions are using the return value ES:BP for the pointer to the ROM font. So we should only preserve BP when we use it internally. I'll try to fix it tomorrow. I think after fixing this issue it's time to update the binaries in the Bochs tree.

**Comment by Vort** [comment]
Problem is solved with https://github.com/bochs-emu/VGABIOS/commit/61efb5ce491a26b850eac7d836d06ef697682fe3.

> I think after fixing this issue it's time to update the binaries in the Bochs tree.

I agree.
