### ISSUE TITLE
Screen split in half in One Must Fall 2097

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#188]
When One Must Fall 2097 game is started, this screen appear:

![bochs_omf](https://github.com/bochs-emu/Bochs/assets/1242858/8d1d3e82-abf5-4193-bfc8-5fed95c88d18)

This is how it should look:
![vbox_omf](https://github.com/bochs-emu/Bochs/assets/1242858/662dfb15-fe2a-477e-9069-2a44aad1d6a3)

Test files: [omf.zip](https://github.com/bochs-emu/Bochs/files/13742130/omf.zip)
Version: b63b1225a8507f7677e8576c019a3d069d9ad0c0

**Comment by vruppert** [comment]
Adding this at line 1518 seems to fix this issue:
start_addr <<= 1;

**Comment by Vort** [comment]
> Adding this at line 1518 seems to fix this issue:

No, image is still shifted.
It is better visible at main menu:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/7d51f2a4-5e2b-4231-8d12-e5e95abeaa9c)

**Comment by vruppert** [comment]
Shifting by two looks better. Please also verify with other VGA mode 0x13 games if possible.
start_addr <<= 2;

**Comment by Vort** [comment]
> Shifting by two looks better.

I agree.

> Please also verify with other VGA mode 0x13 games if possible.

Not many games use this feature.
Looks like Legend of Kyrandia (#108) uses it and it now glitches **differently**.
Maybe something is wrong with tile update flags and now wrong tiles are marked?
I have suspicion that tile updates in One Must Fall 2097 are also not right.
Game uses screen shake during battles and screen edges look glitchy during this effect.
However I'm not sure about it.

**Comment by vruppert** [comment]
Now I have downloaded Kyrandia and tried it. It really uses mode 13h, but it looks okay with and without the change. The files in the archive are from 1996, but you seem to have a different version.

**Comment by Vort** [comment]
> but you seem to have a different version

Here is what I tested: [kyr1.zip](https://github.com/bochs-emu/Bochs/files/13759746/kyr1.zip).

**Comment by vruppert** [comment]
Please try the latest code with your games.

**Comment by Vort** [comment]
With e3eb603ad4ea64fb2d19b061b358ccd5f2ac6525 both Legend of Kyrandia and One Must Fall 2097 renders correctly. Thank you.
I tested several other games and saw no problems.
