### ISSUE TITLE
Wrong fade animations in Alien Carnage

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#189]
When Alien Carnage game starts, several animations plays with fade in and fade out.
However, in Bochs fades executed in wrong order, producing fade out, fade in, fade out instead.

Here is how animations looks in Bochs:

https://github.com/bochs-emu/Bochs/assets/1242858/3e5fe578-49a0-4653-951c-bb6e1d14e42a

And here is how they look on real hardware (sorry for bad quality):

https://github.com/bochs-emu/Bochs/assets/1242858/7e323287-36ad-4706-a9da-3f1ff343c46b

This problem may be tricky to solve, because all virtual machines I tested failed to play animations correctly.

Test files: [Carnage.zip](https://github.com/bochs-emu/Bochs/files/13745001/Carnage.zip)
Version: b63b1225a8507f7677e8576c019a3d069d9ad0c0

**Comment by vruppert** [comment]
I guess this could be an undocumented feature of the 256-color VGA mode. I have to do some more investigation with VGA debug messages turned on.

**Comment by Vort** [comment]
There are really 3 fades in the code. I marked them as red digits **1**, **2**, **3**.
However, first fade is done between Video Refresh Control BIOS calls.
Looks like these calls should make first fade invisible.

But in `vgabios.c` I see this:
https://github.com/bochs-emu/VGABIOS/blob/6f4a83ccf8dff2e6ad0b683a4fabad50ac3de121/vgabios/vgabios.c#L3556-L3561
```cpp
static void biosfn_enable_video_refresh_control (AL) Bit8u AL;
{
#ifdef DEBUG
 unimplemented();
#endif
}
```

Of course it does not work.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/15fc335e-5a2a-404a-992e-c143b431b875)

**Comment by vruppert** [comment]
Thanks for pointing this out. I just tried with Cirrus PCI setup and an original VGABIOS for this graphics card and I can confirm that it looks correctly with it (1-5436_46.bin). Now I'll have a look how to implement it.

**Comment by vruppert** [comment]
Please try again with latest files from VGABIOS repository. I'll create a new version soon.

**Comment by Vort** [comment]
Works good with https://github.com/bochs-emu/VGABIOS/commit/af86f51f83b87db88459c6f829e6a9f430b9096a. Thank you.
