### ISSUE TITLE
Sound desynchronization in One Must Fall 2097

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#194]
When One Must Fall 2097 game is started, it shows several lightning strike animations.
At the same time corresponding sound should play.
But in Bochs, sound is delayed.

This problem appears with lots of software in lots of operating systems, but it's effects are easier to see with this game.

_(video should be played with sound turned on)_

https://github.com/bochs-emu/Bochs/assets/1242858/3bd444fb-8346-494d-af00-ae581cb8ace5

Test files: [omf.zip](https://github.com/bochs-emu/Bochs/files/13742130/omf.zip).
Version: aed0c5e9547ef4483129c70cffae4eb3b38097d1.

**Comment by Vort** [comment]
I figured out how to get rid of desynchronization.
Turned out, this problem originates from unclear documentation.

This is what documentation in `.bochsrc` states:
https://github.com/bochs-emu/Bochs/blob/5b61b5149855a6a3f6f790a3da66b8441ae54a4e/bochs/.bochsrc#L1027-L1036

When I was configuring `sb16`, I first of all tried to use default values.
Default value for `dmatimer` is `0`, which makes `sb16` unusable.
Already not good and should be fixed.

Next, I read `750000 is usually a good value` and started to use it in my configurations.
However, this is exactly what leads to desynchronization problem described in this report.
Only value of `1000000` gives well synchronized sound.

I don't know how exactly documentation and default value should be changed, but I'm sure that something should be done with it.

By the way, `non-continuous sound` problems are usually solved with increased bufferization and not by altering flow of time.

**Comment by vruppert** [comment]
The suggested "good" value for dmatimer existed before I have added the mixer and resampler thread. The sound performance should be better now. I suggest to set the new default value to native speed (1000000). We should also add a note that the sound output can depend on the clock sync settings.

**Comment by Vort** [comment]
> I suggest to set the new default value to native speed (1000000)

Yes, I think this is correct.

But reasons why Doom (for example) have problems with sound with `1000000` setting should be investigated.
Probably that's why non-1000000 values were needed in the first place.

**Comment by Vort** [comment]
I think it's ok to close this issue after 29fbdb48da7f739fc5c0e1837961d05c7070abe1.
Problem with Doom probably needs separate issue.
