### ISSUE TITLE
Wrong colors in Duke Nukem 3D

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#199]
This is how game looks like in Bochs:
![bochs_duke](https://github.com/bochs-emu/Bochs/assets/1242858/f4a85af5-f470-4b10-8eb6-fc7a0e6d4a4e)

And this is how it should look like:
![vbox_duke](https://github.com/bochs-emu/Bochs/assets/1242858/aca976ca-b15a-4e0a-b736-520cabe78a06)

Test files: [duke.zip](https://github.com/bochs-emu/Bochs/files/13797385/duke.zip).
Version: 63ab5ea24ae0f65bed95d1dca3153cb6e0cbac74.

**Comment by vruppert** [comment]
This game uses the VBE protected mode interface, but the set palette data function is not yet implemented for this API. The Banshee and Cirrus version are okay, since there is no protected mode interface yet. It seems the recently released VGABIOS needs an update.

**Comment by vruppert** [comment]
Update: please try again with the new binary from VGABIOS repository.

**Comment by Vort** [comment]
Works good with https://github.com/bochs-emu/VGABIOS/commit/1a038b614d7b2ac16ebd0e430c92ed298b7ffd05. Thank you.
