### ISSUE TITLE
Crash when changing resolution to 400x300 with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#202]
When I try to change resolution to 400x300 with Voodoo 3 card in Windows 95, Bochs crashes.
In Windows XP resolution changes, but desktop is rendered with artifacts.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/7fc7cd7a-e504-4911-98bf-0bcef145632a)

Here is program which reproduces this problem: [modeset.zip](https://github.com/bochs-emu/Bochs/files/13811896/modeset.zip).
_(Warning: it changes resolution, but makes no attempts to change it back)_

Version: f48acd833ff5d27c5c3358ceca1a20d20ed6a188

**Comment by vruppert** [comment]
Latest change fixes this issue and possibly #203 too.

**Comment by Vort** [comment]
No crash with 210ea89b36f72d065e028706e3e9346181e7ecf0, technically this problem is solved.
But I doubt leaving such pixel proportions is good idea.
Why it happens this way? Is it hard to make pixels square?

Initially I noticed crash because of [Half-Life](https://archive.org/details/half-life-game-of-the-year-edition).
Having ability to set 400x300 allowed to get 8 FPS instead of 4 FPS with 640x480, but image looks not right with 400x300:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/e7f0e131-1846-474c-afa6-cf8c581c0808)

800x600 for comparison:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/b53cdd09-2cb0-473b-910c-3fd43ddcf9ab)

**Comment by vruppert** [comment]
In VGA mode the horizontal pixels are doubled if dot clock is divided by two. I'll have a look what to do in the Banshee code tomorrow.

**Comment by vruppert** [comment]
I have now added double width support in 'half mode' if height > width.

**Comment by Vort** [comment]
Proportions in Half-Life are good now. Thank you.
![image](https://github.com/bochs-emu/Bochs/assets/1242858/92ab452c-16d7-4472-a402-0178360dfeb6)

One minor problem is that mouse cursor looks not right, but I'm closing this issue anyway.
![image](https://github.com/bochs-emu/Bochs/assets/1242858/f444a34a-fc41-47c8-b299-280506530986)
