### ISSUE TITLE
Visual artifacts in Pac-In-Time

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#204]
Shortly after Pac-In-Time game is started, it shows this screen:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/60617217-e12c-4d25-a49d-922479298e8f)

Bottom part of it makes no sense and, most likely, should not be displayed.

Test files: [pac.zip](https://github.com/bochs-emu/Bochs/files/13816918/pac.zip).
Version: 210ea89b36f72d065e028706e3e9346181e7ecf0.

**Comment by vruppert** [comment]
Both pac and sf (#205) are using "modeX" when the issues appear. When the pac game starts it switches to VGA mode 13h and it has artifacts in the bottom part, too. Compring with DOSBox is not possible - both games hang at startup.

**Comment by vruppert** [comment]
My DOSBox version is called dosbox-staging 0.80.1. Now I have found out what's going on and applied the bugfix to Bochs.

**Comment by Vort** [comment]
I confirm that 071f5c72f7c7095a81a46cef5c019a6423d1f489 fixes this problem. Thank you.
