### ISSUE TITLE
Dotted lines in Superfrog

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#205]
After first level of Superfrog game is loaded, in some places blinking black dots start to appear:
![bochs_sf](https://github.com/bochs-emu/Bochs/assets/1242858/0801c43a-1625-4d4e-bf1f-28485e7d5286)

In VirtualBox these artifacts are even more visible, but in VMware and DOSBox image is clear:
![vmware_sf](https://github.com/bochs-emu/Bochs/assets/1242858/992419d8-3bbd-4e36-9395-b3f73f481234)

Test files: [superfrog.zip](https://github.com/bochs-emu/Bochs/files/13817168/superfrog.zip).
Version: 210ea89b36f72d065e028706e3e9346181e7ecf0

**Comment by Vort** [comment]
Video from DOSBox:


https://github.com/bochs-emu/Bochs/assets/1242858/664747a0-d835-4897-bb1e-8761a63b9380

**Comment by vruppert** [comment]
Please try again after may latest change.

**Comment by Vort** [comment]
No more dotted lines now. Thank you.
There is one more artifact left: coin at bottom right part of the screen is shaking during movement.
But it is most likely related to #206.
