### ISSUE TITLE
Wrong scroll in Raiden

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#206]
When aircraft in Raiden game is moved to the left, visual artifacts at the left side of the screen appears:
![bochs_raiden](https://github.com/bochs-emu/Bochs/assets/1242858/69b6f71e-3aac-47b4-84ba-6be042691147)

Also black dots similar to #205 shows up.

Test files: [raiden.zip](https://github.com/bochs-emu/Bochs/files/13828494/raiden.zip).
Version: 41c2bb8bee56539d4113a106b68c33f3571d98ac.

**Comment by Vort** [comment]
@vruppert why closing? Dotted horizontal lines are gone, but scroll is still having problems (glitchy vertical lines appear on the left side of the screen):
![image](https://github.com/bochs-emu/Bochs/assets/1242858/9d8350ab-8e8b-4112-a297-6f80849bc631)

**Comment by vruppert** [comment]
I'm sorry I didn't see that. You only told me something about the other game. I'll have a look what's going on.

**Comment by vruppert** [comment]
After adding horizontal scrolling the modeX support should be almost complete now. This feature is missing or incorrectly implemented in other modes. Please report if see scrolling issues in other games.

**Comment by Vort** [comment]
Problem is solved both for Raiden and Superfrog. Thank you.
