### ISSUE TITLE
Hang in Frogger

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#207]
After Frogger game is started, it shows this screen:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/ae616ef9-80ee-48da-9345-cf3496f87b61)

After pressing Enter, screen turns black and nothing happens:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/62d12a2a-e36c-448e-a25a-0b785432fcb4)

What strange is that game starts normally if Bochs is launched with debugger support.
However, gameplay is very fast even with `ips=1000000`.
For game to be playable, IPS should be lowered even more, but Bochs not allows to do this:
`numerical parameter 'ips' was set to 500000, which is out of range 1000000 to 4294967295`

Test files: [frogger.zip](https://github.com/bochs-emu/Bochs/files/13830747/frogger.zip).
Version: 41c2bb8bee56539d4113a106b68c33f3571d98ac.

**Comment by stlintel** [comment]
The main difference "with debugger support vs without" is optimizations.
If you disable all optimizations - does game start correctly ?

**Comment by Vort** [comment]
If I replace `--enable-all-optimizations` with `--enable-repeat-speedups --enable-fast-function-calls --enable-trace-linking`, game starts correctly.
So it is `handlers-chaining`, which triggers bug.

**Comment by stlintel** [comment]
I figured it out. After pressing a key there is int 0x10 triggered. 
After interrupt is handled in debugger version there is always interrupt 0x09 trigger which is missing in bad version with optimizations.
I tracked it down to OUT instruction which cause the interrupt raise
`(0).[16321199] [0x0000000c3a01] c000:3a01 (unk. ctxt): out dx, al                ; ee            raise_INTR`
with the speedups the out was not interruptible point, trace continued after it.
when make OUT instruction as BxEndTrace - now it works

**Comment by stlintel** [comment]
I don't think we will ever bother addressing it. 
We are not trying to address emulation of < 386 and I never saw 386 with less than 1Mhz.
This game is 16-bit code, not even protected mode, seems like written for 286.
If it is too fast even with 1Mhz - it is not our problem, this is timer code limitation, don't think it is good idea to rewrite timers code to support IPS less than 1M.

**Comment by Vort** [comment]
> I never saw 386 with less than 1Mhz.

> seems like written for 286.

From [this table](https://www.x86-guide.net/en/cpu/Intel-80286.html) it seems like there were no 286 CPUs slower than 4 MHz.

So why 1M IPS is too fast? Because clock cycles and instruction counts are different things?
Or there is some bug which make game work faster than it should?

> don't think it is good idea to rewrite timers code to support IPS less than 1M.

Ok, I thought 1M limitation is arbitrary.

**Comment by stlintel** [comment]
>So why 1M IPS is too fast? Because clock cycles and instruction counts are different things?
>Or there is some bug which make game work faster than it should

I guess there is a way to check. How does it work in DosBox ? VirtualBox ?
May be indeed there is some other bug which makes it to run too fast but it is beyond of my understanding ...

**Comment by Vort** [comment]
More information:
Game is probably was made for [IBM Personal Computer](https://en.wikipedia.org/wiki/IBM_Personal_Computer) (model 5150).
It includes 8088 CPU and it is 6 times slower than Bochs 1M IPS:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/66239530-0de8-4423-954c-0f7b914ef15f)

I can understand decision to not make full support for 286 and older CPUs.
Just wanted to get data, which confirms current state of their support.
