### ISSUE TITLE
Wrong scroll in Golden Axe

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#208]
When character in Golden Axe game moves to the right, screen starts to shake:

https://github.com/bochs-emu/Bochs/assets/1242858/fa9d9019-0544-4a28-922e-4a35a504995e

This is how it should look like:
_(DOSBox lags for some reason, so only last few seconds of video are important)_

https://github.com/bochs-emu/Bochs/assets/1242858/78728e4c-e555-4cf9-8929-5a843ef8069e

Nice property of this game is that it allows to check scroll functioning for several different video modes.

Test files: [axe.zip](https://github.com/bochs-emu/Bochs/files/13849466/axe.zip).
Version: 6d433ec44b037a9dd4a82a8fcf04f3f9c94e4cc2.

**Comment by vruppert** [comment]
I found out the password and how to select the player, I still don't know how to start the game.

**Comment by Vort** [comment]
>  I still don't know how to start the game.

I'm sorry I didn't mention it. <5> key on numpad selects character.
This is how these old games work unfortunately - by hiding some information.

**Comment by vruppert** [comment]
After trying a lot of possible key I also found it. Since there is no README or so, I don't know how to survive long enough to see some more scrolling. In CGA mode I noticed a black border on top and fixed the start address usage. The EGA/VGA 16-color mode and the VGA 256-color mode (modeX) should be actually fixed, but there are issues. Hercules and Tandy modes are not supported by VGA hardware.

**Comment by Vort** [comment]
> Since there is no README or so, I don't know how to survive long enough to see some more scrolling

Holding <6> (right) from the start (after pressing <5> to select character) is enough to see scrolling.

> The EGA/VGA 16-color mode and the VGA 256-color mode (modeX) should be actually fixed, but there are issues.

I still see problems with scroll with options 1 (EGA) and 4 (VGA).

Option 2 (CGA) is very fast for some reason, it is hard to understand what is going on on screen, probably scroll is fine there, but I suspect image corruption at the bottom part of the screen. Need to look closely there.

**Comment by Vort** [comment]
Yes, there is corruption with CGA. Look below character "photo":

![image](https://github.com/bochs-emu/Bochs/assets/1242858/3e77c5ee-22e0-442e-aa38-fa6fbc879dc8)

![image](https://github.com/bochs-emu/Bochs/assets/1242858/cf208ccd-7de1-4649-bdcc-5614a80a5800)

**Comment by vruppert** [comment]
The EGA 16-color and the VGA 256-color issues are tricky. Axe in EGA mode has very similar VGA register save/restore data as the correctly working Commander Keen. The same applies to Axe in VGA modeX and the recently fixed Raiden game.
Adding some BX_INFOs in the vgacore code shows what's going on.

02118320500i[BXVGA ] VSYNC = 0
02118320501i[BXVGA ] saddr = 0x0141
02119742700i[BXVGA ] VSYNC = 1
02119742706i[BXVGA ] hp = 0x06
02119822511i[BXVGA ] VSYNC = 0
02120216300i[BXVGA ] update
02121171202i[BXVGA ] VSYNC = 1
02121177502i[BXVGA ] VSYNC = 0
02121177503i[BXVGA ] saddr = 0x8141
02121177508i[BXVGA ] saddr = 0x8142
02122504800i[BXVGA ] update         <<== This one causes the issues
02122599701i[BXVGA ] VSYNC = 1
02122599707i[BXVGA ] hp = 0x00
02122680024i[BXVGA ] VSYNC = 0

The horizontal pixel panning changes in this interval: 0, 2, 4, 6. Then the start address is incremented and the panning is set to 0. The problem: the start address is modified right after VSYNC off and the panning register is reset right after VSYNC on. If the screen update happens inbetween you can see the issue. Driving the update timer with the vertical frequency could possibly fix these issues.

**Comment by Vort** [comment]
It looks like change which can potentially break other games.
It may be better to try fixing it later, after 2.8 release.

_(I tested CGA and it looks good now, apart from abnormal speed)_

**Comment by vruppert** [comment]
I had a look at the VGA timer code to see what can be done. A special value of 0 for the update fraquency to force using the vertical total usec value if in a valid range could be an option. The Voodoo device already has a vertical timer for it's own modes that sets the display start usec, but doesn't call update() yet. As a first step I have increased the maximum update frequency to 75. It doesn't fix the issue, but it possibly makes it easier to determine whether we have a timing issue or buggy update code.

**Comment by vruppert** [comment]
I have now implemented the feature I described above. The EGA and VGA display issue should be fixed by using the special value of 0 for the update frequence. Note that the feature is not yet enabled if Voodoo support is compiled in. Some more testing is required with this device.

**Comment by Vort** [comment]
I see scrolling glitches even with `update_freq=0`.
Maybe I was testing this change incorrectly.

**Comment by vruppert** [comment]
I can confirm that the issues are gone on the Linux port, but I can also confirm that there are still issues on Windows. The reason is the low performance of the win32 gui. When playing the game the IPS status shows only a little more than 10 million. The best results on Windows I got with the sdl2 gui and "clock: sync=realtime" - around 50 million, that's very similar to the performance on Linux. Since SDL on Windows uses DirectX, the conclusion is: we need DirectX support in the win32 gui for better performance and less graphics issues.

**Comment by Vort** [comment]
My intuition says me that something is wrong with timings.
No DirectX is needed to achieve such result:

https://github.com/bochs-emu/Bochs/assets/1242858/84b2ff5d-6035-4934-af8d-78ec3b81a1fb

Of course, this is not proper solution.
```diff
diff --git a/bochs/iodev/display/vgacore.cc b/bochs/iodev/display/vgacore.cc
index 1e5deda64..09015d127 100644
--- a/bochs/iodev/display/vgacore.cc
+++ b/bochs/iodev/display/vgacore.cc
@@ -64,6 +64,7 @@ bx_vgacore_c::bx_vgacore_c()
 {
   memset(&s, 0, sizeof(s));
   timer_id = BX_NULL_TIMER_HANDLE;
+  timer_id2 = BX_NULL_TIMER_HANDLE;
 }
 
 bx_vgacore_c::~bx_vgacore_c()
@@ -226,6 +227,8 @@ void bx_vgacore_c::init_systemtimer(void)
   if (BX_VGA_THIS timer_id == BX_NULL_TIMER_HANDLE) {
     BX_VGA_THIS timer_id = bx_virt_timer.register_timer(this, vga_timer_handler,
        100000, 1, 1, BX_VGA_THIS update_realtime, "vga");
+    BX_VGA_THIS timer_id2 = bx_virt_timer.register_timer(this, vga_timer2_handler,
+        100000, 1, 1, BX_VGA_THIS update_realtime, "vga");
     vga_update_freq->set_handler(vga_param_handler);
     vga_update_freq->set_device_param(this);
   }
@@ -1269,6 +1272,15 @@ bool bx_vgacore_c::skip_update(void)
   return 0;
 }
 
+void bx_vgacore_c::updatevsync(void)
+{
+    // Always set display start time if update timer is driven by VSYNC
+    if (BX_VGA_THIS update_mode_vsync) {
+        BX_VGA_THIS s.display_start_usec =
+            bx_virt_timer.time_usec(BX_VGA_THIS vsync_realtime) - BX_VGA_THIS s.vrend_usec;
+    }
+}
+
 void bx_vgacore_c::update(void)
 {
   unsigned iHeight, iWidth;
@@ -1276,11 +1288,8 @@ void bx_vgacore_c::update(void)
   static bool cs_visible = 0;
   bool cs_toggle = 0;
 
-  // Always set display start time if update timer is driven by VSYNC
-  if (BX_VGA_THIS update_mode_vsync) {
-    BX_VGA_THIS s.display_start_usec =
-      bx_virt_timer.time_usec(BX_VGA_THIS vsync_realtime) - BX_VGA_THIS s.vrend_usec;
-  }
+  bx_virt_timer.activate_timer(BX_VGA_THIS timer_id2, BX_VGA_THIS s.vtotal_usec - 10, 0);
+
   cs_counter--;
   /* no screen update necessary */
   if ((BX_VGA_THIS s.vga_mem_updated == 0) && (cs_counter > 0))
@@ -2303,6 +2312,12 @@ void bx_vgacore_c::refresh_display(void *this_ptr, bool redraw)
   vga_timer_handler(vgadev);
 }
 
+void bx_vgacore_c::vga_timer2_handler(void *this_ptr)
+{
+    bx_vgacore_c *vgadev = (bx_vgacore_c *)this_ptr;
+    vgadev->updatevsync();
+}
+
 void bx_vgacore_c::vga_timer_handler(void *this_ptr)
 {
   bx_vgacore_c *vgadev = (bx_vgacore_c *) this_ptr;
diff --git a/bochs/iodev/display/vgacore.h b/bochs/iodev/display/vgacore.h
index 6d780be67..bc9f36036 100644
--- a/bochs/iodev/display/vgacore.h
+++ b/bochs/iodev/display/vgacore.h
@@ -107,6 +107,7 @@ public:
   virtual bool   get_update_mode(void) {return update_mode_vsync;}
   virtual void   set_update_timer(Bit32u usec);
   static void    vga_timer_handler(void *);
+  static void    vga_timer2_handler(void *);
   static Bit64s  vga_param_handler(bx_param_c *param, bool set, Bit64s val);
 
 protected:
@@ -123,6 +124,7 @@ protected:
 
   Bit8u get_vga_pixel(Bit16u x, Bit16u y, Bit16u raddr, Bit16u lc, bool bs, Bit8u **plane);
   virtual void update(void);
+  void updatevsync(void);
   void determine_screen_dimensions(unsigned *piHeight, unsigned *piWidth);
   void calculate_retrace_timing(void);
   bool skip_update(void);
@@ -270,6 +272,7 @@ protected:
   } s;  // state information
 
   int timer_id;
+  int timer_id2;
   Bit32u vga_update_interval;
   bool update_mode_vsync;
   bool update_realtime; 
```

**Comment by vruppert** [comment]
This change makes things worse on Linux. The screen is flickering again when scrolling. You have added an additional timer that is called 10 useconds before the update timer expires, right ? This could also be done by adding 10 to the calculated display_start_usec. With your code it can happen that update() is called between the two required register changes causing these visible effects. On Linux the behaviour with my code is exactly as expected, but I still don't know why this doesn't work on Windows. I guess it's related to the virtual timer that calls platform dependent code.

**Comment by Vort** [comment]
This is what I found:
_At the end of the vertical retrace, the current line start address is loaded with this value._
http://www.osdever.net/FreeVGA/vga/vgafx.htm

Tried to implement it and result looks good:
```diff
diff --git a/bochs/iodev/display/vgacore.cc b/bochs/iodev/display/vgacore.cc
index 1e5deda64..95977ad0e 100644
--- a/bochs/iodev/display/vgacore.cc
+++ b/bochs/iodev/display/vgacore.cc
@@ -470,6 +470,8 @@ Bit32u bx_vgacore_c::read(Bit32u address, unsigned io_len)
       }
       if ((display_usec >= BX_VGA_THIS s.vrstart_usec) &&
           (display_usec <= BX_VGA_THIS s.vrend_usec)) {
+        BX_VGA_THIS s.CRTC.reg0c_copy = BX_VGA_THIS s.CRTC.reg[0x0c];
+        BX_VGA_THIS s.CRTC.reg0d_copy = BX_VGA_THIS s.CRTC.reg[0x0d];
         retval |= 0x08;
       }
       if (display_usec >= BX_VGA_THIS s.vblank_usec) {
@@ -1317,7 +1319,7 @@ void bx_vgacore_c::update(void)
     unsigned long byte_offset;
     unsigned xc, yc, xti, yti;
 
-    start_addr = (BX_VGA_THIS s.CRTC.reg[0x0c] << 8) | BX_VGA_THIS s.CRTC.reg[0x0d];
+    start_addr = (BX_VGA_THIS s.CRTC.reg0c_copy << 8) | BX_VGA_THIS s.CRTC.reg0d_copy;
 
     determine_screen_dimensions(&iHeight, &iWidth);
     if((iWidth != BX_VGA_THIS s.last_xres) || (iHeight != BX_VGA_THIS s.last_yres) ||
@@ -1776,7 +1778,7 @@ void bx_vgacore_c::mem_write(bx_phy_address addr, Bit8u value)
       offset = (Bit32u)addr - 0xA0000;
   }
 
-  start_addr = (BX_VGA_THIS s.CRTC.reg[0x0c] << 8) | BX_VGA_THIS s.CRTC.reg[0x0d];
+  start_addr = (BX_VGA_THIS s.CRTC.reg0c_copy << 8) | BX_VGA_THIS s.CRTC.reg0d_copy;
 
   if (BX_VGA_THIS s.graphics_ctrl.graphics_alpha) {
     if (BX_VGA_THIS s.sequencer.chain_four) {
diff --git a/bochs/iodev/display/vgacore.h b/bochs/iodev/display/vgacore.h
index 6d780be67..10084cb2d 100644
--- a/bochs/iodev/display/vgacore.h
+++ b/bochs/iodev/display/vgacore.h
@@ -147,6 +147,8 @@ protected:
     struct {
       Bit8u   address;
       Bit8u   reg[0x19];
+      Bit8u   reg0c_copy;
+      Bit8u   reg0d_copy;
       bool write_protect;
     } CRTC;
```

**Comment by Vort** [comment]
Two more notes:
1. `htotal_usec` do not have enough precision. It stores value `31` while in fact `31.778` should be there. This difference introduce significant error in following calculations of `vblank_usec`, `vrstart_usec` and `vrend_usec`. I think maybe it should be changed to `htotal_nsec` and scaled `1000` times.
2. `BX_VGA_THIS s.display_start_usec = bx_virt_timer.time_usec(BX_VGA_THIS vsync_realtime) - BX_VGA_THIS s.vrend_usec;` inside of `bx_vgacore_c::update` looks suspicious. It looks more natural to have display_start aligned with update, in other words having no `- BX_VGA_THIS s.vrend_usec` there. This is how "vertical back porch" works I suppose. But I'm not sure about it.

**Comment by vruppert** [comment]
About the start address change I also that about that, but I didn't find information about it. I'll implement this behavior  ASAP. About note 1: You are definitely wrong here. If the frame rate is 70 Hz, the vertical total usec is 14285. If you have 400 scan lines the time for drawing one line is about 35 usec. About note 2: I agree, that's what I originally wanted to do, but it didn't fix the issue. When the start address handling is fixed, I think it will also work.

**Comment by Vort** [comment]
Not 400. There are some invisible lines. `crtcp.vtotal` equals `449`.
However calculation is made slightly different:
`hfreq = vclock / (crtcp.htotal * cwidth)`
`s.htotal_usec = 1000000 / hfreq`

`vclock` = `28322000`, `crtcp.htotal` = `100`, `cwidth` = `9`.
`htotal_usec` = `1000000 / 28322000 * 100 * 9` = `31.777`

But my idea was about precision, not about particular value.
For example, `vrend_usec` = `htotal_usec` * `vrend`. `vrend` is `414`.
Using `htotal_usec` = `31`, `vrend_usec` = `12834`.
Using `htotal_usec` = `31.777`, `vrend_usec` = `13155`.
Which is 2.5% difference - I think it may be noticeable in some cases. I have no proofs however.

**Comment by vruppert** [comment]
I'm sorry I misunderstood your explanation. I think the calculation must be modified. We need to divide the clock frequency by vertical total first to get a more precise vertical total usec value. Your suggested change for the start address change needs to be mdified. It assumes that the input status 1 register is frequently read. This happens in most games, but not not when you simply change the current page in text mode with the VGABIOS. I'm looking for a better solution.

**Comment by Vort** [comment]
> I think the calculation must be modified. We need to divide the clock frequency by vertical total first to get a more precise vertical total usec value.

Right now `vtotal_usec` = `14285`.
More precise calculation (`crtcp.vtotal * 1000000 / (vclock / (crtcp.htotal * cwidth))`) gives `14268` instead.
Such value is 0.1% more accurate.

It is good, but I'm more concerned about 2.5% inaccuracy in `vrstart_usec` and other values which use `htotal_usec`.

> Your suggested change for the start address change needs to be mdified.

Right.

**Comment by vruppert** [comment]
I have now applied the VGA timing code rewrite. Some remarks in addition to the log message: For setting the display start time I'm still using what you call ugly code. Setting it in the update() code would possibly make the game speed depending on the update frequency if the vsync mode is not used. I also tried to modify the timer settings within a timer handler but this makes Bochs hang forever at startup. That's why calling the update code from the new timer doesn't work yet. For now I let the timer be independent from each other. I hope the change is good enough to fix the bug.

**Comment by Vort** [comment]
Scroll works perfectly now in Golden Axe with EGA, CGA and VGA modes and with `update_freq` `0` and `30`.
However, problem with Commander Keen 5 (#114) appeared again.

**Comment by Vort** [comment]
To understand what is going on, I added logging to `bx_vgacore_c::vsync_timer` and `bx_vgacore_c::update`, but results looks like chaos for me. Do you see different amounts of `update` and `vsync_timer` calls as well? Should not be like that with `update_freq=0`. Maybe I added logging wrong, not sure.
```
00324069841e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00324190076e[BXVGA ] display_usec: 19166 | bx_vgacore_c::update
00324276936e[BXVGA ] display_usec: 23462 | bx_vgacore_c::update
00324355200e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00324490976e[BXVGA ] display_usec: 19943 | bx_vgacore_c::update
00324626076e[BXVGA ] display_usec: 26698 | bx_vgacore_c::update
00324640561e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00324742176e[BXVGA ] display_usec: 18221 | bx_vgacore_c::update
00324832776e[BXVGA ] display_usec: 22765 | bx_vgacore_c::update
00324910396e[BXVGA ] display_usec: 26646 | bx_vgacore_c::update
00324925921e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00325056376e[BXVGA ] display_usec: 19677 | bx_vgacore_c::update
00325211280e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00325232516e[BXVGA ] display_usec: 14191 | bx_vgacore_c::update
00325353816e[BXVGA ] display_usec: 20281 | bx_vgacore_c::update
00325449876e[BXVGA ] display_usec: 25084 | bx_vgacore_c::update
00325496641e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00325700196e[BXVGA ] display_usec: 23332 | bx_vgacore_c::update
00325782000e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
```

**Comment by vruppert** [comment]
If both timers running in the same mode you would see one update per vsync_timer in vsync update mode. The problem with Commander Keen is that update is called before vsync_timer. If I add the vga timer call at the end of vsync_timer and disable it in set_update_timer() the display is okay for Commander Keen. This solution is not 100 percent okay, since the update call should happen at the display start time and it is not okay for the Voodoo 1 and 2, since the updates are also called from VGA timer handler.

**Comment by Vort** [comment]
I misunderstood how these options works then.
With `update_freq=0, realtime=0` I see logs like this:
```
00359068782e[BXVGA ] display_usec: 27423 | bx_vgacore_c::update
00359068782e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00359354140e[BXVGA ] display_usec: 27423 | bx_vgacore_c::update
00359354140e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00359639501e[BXVGA ] display_usec: 27423 | bx_vgacore_c::update
00359639501e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
00359924861e[BXVGA ] display_usec: 27423 | bx_vgacore_c::update
00359924861e[BXVGA ] display_usec: 27423 | bx_vgacore_c::vsync_timer
```
But in such case Golden Axe scroll is glitchy again.

In description I see "The calling time is defined as vertical retrace end", but in code and in logs `update` and `vsync_timer` happens simultaneously.

**Comment by Vort** [comment]
Also I noticed lines like these:
`hfreq = 559,4 kHz / vfreq = 279722,2 Hz`
Maybe setting timer to such high frequency is bad idea and protection like made in `bx_vgacore_c::set_update_timer` is needed here as well.

**Comment by Vort** [comment]
Maybe it makes sense to allow modification for timer phase:
```diff
diff --git a/bochs/iodev/display/vgacore.cc b/bochs/iodev/display/vgacore.cc
index 6db165cb4..34fa6ff07 100644
--- a/bochs/iodev/display/vgacore.cc
+++ b/bochs/iodev/display/vgacore.cc
@@ -2331,6 +2331,7 @@ void bx_vgacore_c::vsync_timer(void)
 
 void bx_vgacore_c::set_update_timer(Bit32u usec)
 {
+  Bit32u delay_usec = 0;
   if (usec == 0) {
 #if BX_SUPPORT_PCI
     if (BX_VGA_THIS s.vga_override && (BX_VGA_THIS s.nvgadev != NULL)) {
@@ -2339,6 +2340,8 @@ void bx_vgacore_c::set_update_timer(Bit32u usec)
 #endif
     {
       usec = BX_VGA_THIS s.vtotal_usec;
+      if (BX_VGA_THIS s.vrend_usec != 0)
+        delay_usec = usec - BX_VGA_THIS s.vrend_usec;
     }
     if ((usec < 8000) || (usec > 200000)) {
       usec = 100000;
@@ -2349,7 +2352,7 @@ void bx_vgacore_c::set_update_timer(Bit32u usec)
   }
   if (usec != BX_VGA_THIS vga_update_interval) {
     BX_INFO(("Setting VGA update interval to %d (%.1f Hz)", usec, 1000000.0 / (float)usec));
-    bx_virt_timer.activate_timer(BX_VGA_THIS timer_id1, usec, 1);
+    bx_virt_timer.activate_timer(BX_VGA_THIS timer_id1, usec, 1, delay_usec);
     // VGA text mode cursor blink frequency 1.875 Hz
     if (usec < 266666) {
       BX_VGA_THIS s.blink_counter = 266666 / (unsigned)usec;
diff --git a/bochs/iodev/virt_timer.cc b/bochs/iodev/virt_timer.cc
index 37ddcf2b2..4bcafa82d 100644
--- a/bochs/iodev/virt_timer.cc
+++ b/bochs/iodev/virt_timer.cc
@@ -281,21 +281,23 @@ void bx_virt_timer_c::start_timers(void)
 }
 
 //activate a deactivated but registered timer.
-void bx_virt_timer_c::activate_timer(unsigned timer_index, Bit32u useconds, bool continuous)
+void bx_virt_timer_c::activate_timer(unsigned timer_index, Bit32u period_usec, bool continuous, Bit32u delay_usec)
 {
   BX_ASSERT(timer_index < BX_MAX_VIRTUAL_TIMERS);
 
   BX_ASSERT(timer[timer_index].inUse);
-  BX_ASSERT(useconds>0);
+  BX_ASSERT(period_usec>0);
+
+  Bit64u total_usec = period_usec + delay_usec;
 
   bool realtime = timer[timer_index].realtime;
-  timer[timer_index].period = useconds;
-  timer[timer_index].timeToFire = s[realtime].current_timers_time + (Bit64u)useconds;
+  timer[timer_index].period = period_usec;
+  timer[timer_index].timeToFire = s[realtime].current_timers_time + total_usec;
   timer[timer_index].active = 1;
   timer[timer_index].continuous = continuous;
 
-  if (useconds < s[realtime].timers_next_event_time) {
-    s[realtime].timers_next_event_time = useconds;
+  if (total_usec < s[realtime].timers_next_event_time) {
+    s[realtime].timers_next_event_time = total_usec;
     next_event_time_update(realtime);
     //FIXME
   }
diff --git a/bochs/iodev/virt_timer.h b/bochs/iodev/virt_timer.h
index da054c7af..89fcff653 100644
--- a/bochs/iodev/virt_timer.h
+++ b/bochs/iodev/virt_timer.h
@@ -126,7 +126,7 @@ public:
   void start_timers(void);
 
   //activate a deactivated but registered timer.
-  void activate_timer(unsigned timer_index, Bit32u useconds, bool continuous);
+  void activate_timer(unsigned timer_index, Bit32u period_usec, bool continuous, Bit32u delay_usec = 0);
 
   //deactivate (but don't unregister) a currently registered timer.
   void deactivate_timer(unsigned timer_index); 
```

**Comment by vruppert** [comment]
I'm not really familiar with this timer code, but it needs some changes to implement a more accurate VGA timing. At the moment I don't understand what your code should do. What we need is a timer that alternates between a long and a short interval (long from display start to retrace end and short to the next display start). Since we cannot restart the timer from within a timer handler, I thought about adding a latch for that case. I could be loaded after processing timer handlers and before calculating the next timer event.

**Comment by Vort** [comment]
> I don't understand what your code should do.

It makes `timer_id1` execute later than `timer_id2`, but with the same frequency (for `update_freq=0, realtime=0` case).

**Comment by vruppert** [comment]
Okay, I understand. This is one option for a final fix. As a first step I have disabled the capability to change the status of update_mode_vsync at runtime to make things easier. If > 0 the valid range at runtime is 1 to 75 and the update behavior is the same as it was before adding support for the special value 0. If 0 changing value at runtime is disabled. I intend to look at some other issues first, before I continue with VGA timing stuff.

**Comment by vruppert** [comment]
Can you please try both games with the latest VGA code. On Linux it looks okay, but I haven't tested it on Windows yet.

**Comment by Vort** [comment]
Golden Axe looks good now both in `update_freq=0, realtime=0` and `update_freq=30, realtime=1` modes. Thank you.
Commander Keen looks good in `update_freq=0, realtime=0` and not good in `update_freq=15, realtime=1` mode. I wonder how it was possible to make it look better with less accurate timings in previous versions. Maybe it worth separate investigation, but it is enough fixes now to have this report closed I think.
Also I tested several other programs and found no new problems.
