### ISSUE TITLE
Lack of header files on iSH

### ISSUE THREAD

**Issue by HeavySnowJakarta** [bochs-emu/Bochs#21]
![image](https://user-images.githubusercontent.com/54460050/206861315-955cb831-b51c-406e-bbab-ad913ce94cf4.png)![image](https://user-images.githubusercontent.com/54460050/206861321-8b4ee5e7-19bc-483a-bdad-2a237adf1fa6.png)![image](https://user-images.githubusercontent.com/54460050/206861326-9b22ae1f-7e1e-4b4e-8cbe-30c32bef2a2d.png)![image](https://user-images.githubusercontent.com/54460050/206861331-ea6b9c3e-1675-4a27-b9d2-343a2d1b1aeb.png)![image](https://user-images.githubusercontent.com/54460050/206861334-d230b97f-f4af-4abc-951c-8fcdb9045e20.png)![image](https://user-images.githubusercontent.com/54460050/206861339-794452a4-41c7-43d3-a07b-7d4c77a7b70c.png)![image](https://user-images.githubusercontent.com/54460050/206861344-bf9c3ee0-1355-473b-bfd7-58f3b3432005.png)![image](https://user-images.githubusercontent.com/54460050/206861348-812afebd-f527-4f86-9b78-22f413912985.png)![image](https://user-images.githubusercontent.com/54460050/206861355-916ef0e5-8248-4dfd-89e9-975b4511bbc7.png)

The environment of iSH lacks many header files, and as I downloaded them from the Linux kernel on GitHub, it reported those errors. Is it that there are problems with the header files downloaded?

**Comment by stlintel** [comment]
See no problem with Bochs ...
