### ISSUE TITLE
Test stuck due to incorrect Virtual NMI handling

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#211]
According to the manual:

28.2.2 Information for VM Exits Due to Vectored Events

— Bit 11 is set to 1 if the VM exit is caused by a hardware exception that would have delivered an error code
on the stack. This bit is always 0 if the VM exit occurred while the logical processor was in real-address
mode (CR0.PE=0).2 If bit 11 is set to 1, the error code is placed in the VM-exit interruption error code (see
below).

![error_code](https://github.com/bochs-emu/Bochs/assets/3366897/67708447-1930-4204-9fcb-71de4764209f)

**Comment by stlintel** [comment]
Can you attach testing image ?
Should be easy to fix but I need a test to verify ...

**Comment by lgj1107** [comment]
[bochsrc.zip](https://github.com/bochs-emu/Bochs/files/13869507/bochsrc.zip)

**Comment by stlintel** [comment]
Does this image works for you ?
I tried to boot it on Bochs and got it stuck. 
It printed to log:
```
====
00331171362e[FLOPPY] read() on floppy image returns 0
00331726917e[FLOPPY] read() on floppy image returns 0
00332282472e[FLOPPY] read() on floppy image returns 0
00337345542e[CPU0  ] RDMSR: Unknown register 0x1d9
====
```
and then nothing

**Comment by stlintel** [comment]
But in general - can you try this patch ?

```
diff -uBbwr Bochs-tmul-regression.backup/bochs/cpu/exception.cc Bochs-tmul-regression/bochs/cpu/exception.cc
--- Bochs-tmul-regression.backup/bochs/cpu/exception.cc	2024-01-09 23:01:03.253151100 +0200
+++ Bochs-tmul-regression/bochs/cpu/exception.cc	2024-01-10 20:16:20.199483800 +0200
@@ -923,11 +923,6 @@
 
   BX_DEBUG(("exception(0x%02x): error_code=%04x", vector, error_code));
 
-  if (real_mode()) {
-    push_error = false; // not INT, no error code pushed
-    error_code = 0;
-  }
-
 #if BX_SUPPORT_VMX
   VMexit_Event(BX_HARDWARE_EXCEPTION, vector, error_code, push_error);
 #endif
@@ -1001,6 +996,11 @@
 
   BX_CPU_THIS_PTR last_exception_type = exception_type;
 
+  if (real_mode()) {
+    push_error = false; // not INT, no error code pushed
+    error_code = 0;
+  }
+
   interrupt(vector, BX_HARDWARE_EXCEPTION, push_error, error_code);
 
   BX_CPU_THIS_PTR last_exception_type = 0; // error resolved

```
It supposed to solve the issue. Can you confirm ?

**Comment by lgj1107** [comment]
It may be caused by bochs inconsistency, because I encountered exactly the same problem as https://sourceforge.net/p/bochs/bugs/1460/, and I added something to VMX.CC to solve the NMI_exiting problem:

  if (vm->pin_vmexec_ctrls & VMX_PIN_BASED_VMEXEC_CTRL_VIRTUAL_NMI) {
    if (is_masked_event(BX_EVENT_VMX_VIRTUAL_NMI))
      interruptibility_state |= BX_VMX_INTERRUPTS_BLOCKED_NMI_BLOCKED;
  }
/*
*	28.1 ARCHITECTURAL STATE BEFORE A VM EXIT
*
*	If an event causes a VM exit directly, it does not update architectural state as it would have if it had it not
*caused the VM exit:
*	— An NMI causes subsequent NMIs to be blocked, but only after the VM exit completes.
*/
  
  else {
  if (vm->pin_vmexec_ctrls & VMX_PIN_BASED_VMEXEC_CTRL_NMI_EXITING) {
    if (is_masked_event(BX_EVENT_NMI))
      interruptibility_state = interruptibility_state & 0x17;
  }


  else {
    if (is_masked_event(BX_EVENT_NMI))
      interruptibility_state |= BX_VMX_INTERRUPTS_BLOCKED_NMI_BLOCKED;
}
 }


Very simple repair for your reference。

**Comment by lgj1107** [comment]
Your patch works normally and solves the problem。
![130c](https://github.com/bochs-emu/Bochs/assets/3366897/af2951c1-5de5-4435-a36e-d165c2c106c9)

**Comment by stlintel** [comment]
reopen as NMI issue until fixed

**Comment by stlintel** [comment]
actually applied patch above with

```
  if (vm->pin_vmexec_ctrls & VMX_PIN_BASED_VMEXEC_CTRL_NMI_EXITING) {
    if (is_masked_event(BX_EVENT_NMI))
      interruptibility_state = interruptibility_state & 0x17;
  }
  else {
    if (is_masked_event(BX_EVENT_NMI))
      interruptibility_state |= BX_VMX_INTERRUPTS_BLOCKED_NMI_BLOCKED;
   }

```
and it is still not booting. I wonder if the floppy image is just broken ?
"read() on floppy image returns 0" clearly indicates the floppy is  broken. It's size is 9595 bytes, is it enough for a floppy ?

**Comment by stlintel** [comment]
BTW, I thought about what is hack actually does ... it seems to tell that 
if NMI exiting is enabled, the NMI blocking is not being set when NMI_VMEXIT happens.
if yes -> the following patch might be a solution instead of the hack.
Can you try and confirm it does smth ?

```
diff --git a/bochs/cpu/event.cc b/bochs/cpu/event.cc
index be4d2ad76..cec317184 100644
--- a/bochs/cpu/event.cc
+++ b/bochs/cpu/event.cc
@@ -345,11 +345,11 @@ bool BX_CPU_C::handleAsyncEvent(void)
     }
 #endif
     clear_event(BX_EVENT_NMI);
-    mask_event(BX_EVENT_NMI);
     BX_CPU_THIS_PTR EXT = 1; /* external event */
 #if BX_SUPPORT_VMX
     VMexit_Event(BX_NMI, 2, 0, 0);
 #endif
+    mask_event(BX_EVENT_NMI);
     BX_INSTR_HWINTERRUPT(BX_CPU_ID, 2, BX_CPU_THIS_PTR sregs[BX_SEG_REG_CS].selector.value, RIP);
     interrupt(2, BX_NMI, 0, 0);
   }

```

**Comment by stlintel** [comment]
See complete patch including "An NMI causes subsequent NMIs to be blocked, but only after the VM exit completes" part

```
diff --git a/bochs/cpu/event.cc b/bochs/cpu/event.cc
index be4d2ad76..cec317184 100644
--- a/bochs/cpu/event.cc
+++ b/bochs/cpu/event.cc
@@ -345,11 +345,11 @@ bool BX_CPU_C::handleAsyncEvent(void)
     }
 #endif
     clear_event(BX_EVENT_NMI);
-    mask_event(BX_EVENT_NMI);
     BX_CPU_THIS_PTR EXT = 1; /* external event */
 #if BX_SUPPORT_VMX
     VMexit_Event(BX_NMI, 2, 0, 0);
 #endif
+    mask_event(BX_EVENT_NMI);
     BX_INSTR_HWINTERRUPT(BX_CPU_ID, 2, BX_CPU_THIS_PTR sregs[BX_SEG_REG_CS].selector.value, RIP);
     interrupt(2, BX_NMI, 0, 0);
   }
diff --git a/bochs/cpu/vmx.cc b/bochs/cpu/vmx.cc
index 1da5415a1..c394312a4 100644
--- a/bochs/cpu/vmx.cc
+++ b/bochs/cpu/vmx.cc
@@ -2886,6 +2899,11 @@ void BX_CPU_C::VMexit(Bit32u reason, Bit64u qualification)
   //
 
   mask_event(BX_EVENT_INIT); // INIT is disabled in VMX root mode
+  if (reason == VMX_VMEXIT_EXCEPTION_NMI) {
+    Bit32u vector = VMread32(VMCS_32BIT_VMEXIT_INTERRUPTION_INFO) & 0xFF;
+    if (vector == 2)
+      mask_event(BX_EVENT_NMI);
+  }
 
   BX_CPU_THIS_PTR EXT = 0;
   BX_CPU_THIS_PTR last_exception_type = 0;

```

**Comment by stlintel** [comment]
Well tested on the image from https://sourceforge.net/p/bochs/bugs/1460/
Works perfectly now, closing the issue
