### ISSUE TITLE
Wrong title bar gradient in Windows XP with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#213]
When Command Prompt (`cmd.exe`) window is opened in Windows XP with 16 bpp video mode and Voodoo 3 card, green pixels appear at the right side of title bar:
![bochs_winxp_gradient](https://github.com/bochs-emu/Bochs/assets/1242858/ea4c5938-8fa1-427c-8a2e-557f11979ea9)
Zoomed in:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/0276fc10-fae5-4bfa-9ed3-8ed1556aa660)

No such problem appear with Cirrus card.

Version: cfa7276cb9889f19a3728ce3c3af2f8081da04fa.

**Comment by Vort** [comment]
I made test file with gray color (RGB 128, 128, 128):
![gray](https://github.com/bochs-emu/Bochs/assets/1242858/01e354f1-e86f-4329-8bd8-595b9c0ccc61)

It is perfectly representable with 16 bit color depth.
But Bochs shows RGB 132, 130, 132 instead:
![bochs_gray](https://github.com/bochs-emu/Bochs/assets/1242858/aa8d8b46-de88-4d90-972f-ace761731789)

**Comment by Vort** [comment]
Same gradient renders well in Windows 98:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/b671299a-2ddf-4cc9-a8ff-aad6d36783b5)

If I change gradient colors in Windows XP, bug becomes even more visible.
Here is gradient from black to white:
![bochs_gradient_bw](https://github.com/bochs-emu/Bochs/assets/1242858/f666633e-5a8a-466d-8e0b-97db8ec3c681)

**Comment by Vort** [comment]
Here is article which explains how to draw gradients in Windows:
https://board.flatassembler.net/topic.php?t=15278

I took source code from there and made slight change: replaced `GRADIENT_FILL_RECT_V` with `GRADIENT_FILL_RECT_H`: [GradientFill.zip](https://github.com/bochs-emu/Bochs/files/13905683/GradientFill.zip).

And such code shows the same problem:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/2568b407-8dc9-41da-a715-034f3e83f36b)

**Comment by Vort** [comment]
I'm almost sure it's a bug not in Bochs, but in Voodoo 3 driver.
I was able to obtain the same glitched values as driver sends to video card with such code:
```cpp
#include <windows.h>
#include <iostream>
#include <iomanip>

#define PEL16_FROM_RGB( r, g, b, dither ) \
            (   ((((r) + dither) >> 8)       & 0xf800) | \
                ((((g) + (dither>>1)) >> 13) & 0x07e0) | \
                ((((b) + dither) >> 19)      & 0x001f)      )

static ULONG gaulDitherTable16[4][4] =
{
	{ 0x00000, 0x40000, 0x10000, 0x50000 },
	{ 0x60000, 0x20000, 0x70000, 0x30000 },
	{ 0x18000, 0x58000, 0x08000, 0x48000 },
	{ 0x78000, 0x38000, 0x68000, 0x28000 }
};

int main()
{
	LONG        i;
	ULONG       ditherAlignmentX = 1;
	ULONG       ditherAlignmentY = 0;
	ULONG       *ditherTable;
	ULONG       dither;
	ULONG       pel;
	LONG        rdx;
	LONG        gdx;
	LONG        bdx;
	LONG        rd;
	LONG        gd;
	LONG        bd;
	LONG        rs;
	LONG        gs;
	LONG        bs;
	TRIVERTEX   vtUl = { 0 };
	TRIVERTEX   vtLr = { 0 };
	LONG        dx;
	RECTL       rect;

	vtLr.Red = 0xFF00;
	vtLr.Green = 0xFF00;
	vtLr.Blue = 0xFF00;
	vtLr.x = 582;
	vtLr.y = 24;

	rect.left = vtUl.x;
	rect.right = vtLr.x;
	rect.top = vtUl.y;
	rect.bottom = vtLr.y;

	ULONG       WidthY = rect.bottom - rect.top;
	ULONG       WidthX = rect.right - rect.left;

	rd = (vtLr.Red - vtUl.Red) << 8;
	gd = (vtLr.Green - vtUl.Green) << 8;
	bd = (vtLr.Blue - vtUl.Blue) << 8;

	rs = vtUl.Red << 8;
	gs = vtUl.Green << 8;
	bs = vtUl.Blue << 8;

	dx = rect.right - rect.left;

	rdx = rd / dx;
	gdx = gd / dx;
	bdx = bd / dx;

	ditherTable = gaulDitherTable16[ditherAlignmentY];

	i = WidthX >> 1;
	while (i-- > 0)
	{
		dither = ditherTable[ditherAlignmentX++ & 3];
		pel = PEL16_FROM_RGB(rs, gs, bs, dither);
		rs += rdx;
		gs += gdx;
		bs += bdx;

		dither = ditherTable[ditherAlignmentX++ & 3];
		pel |= (PEL16_FROM_RGB(rs, gs, bs, dither) << 16);
		rs += rdx;
		gs += gdx;
		bs += bdx;

		std::cout << std::hex << std::setfill('0') << std::setw(8) << pel << std::endl;
	}

	return 0;
}
```

I'm surprised that not only original developers did not fixed this bug, but also people who made modified drivers (SFFT).

**Comment by sskras** [comment]
It still would be nice to test the gradient painting on real gear :)
