### ISSUE TITLE
CMDFIFO writes with len = 8 and 16

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#216]
In attempts to find which Voodoo 3 driver works best with Windows XP, I installed [AmigaSport V3.0 WinXP/Win2K](http://falconfly.3dfx.pl/downloads/amigasport-win2k_xp-30.zip).
After software starts 3D rendering (for example [Half-Life](https://archive.org/details/half-life-game-of-the-year-edition) in OpenGL mode), Bochs logs begins to fill with messages like
`CMDFIFO #0 write with len = 8 redirected to LFB`
`CMDFIFO #0 write with len = 16 redirected to LFB`
I made hackfix and it allowed Half-Life to work, but something more robust should be implemented.
Also my tests were made with latest hack from #178 included, I don't know if it is required for AmigaSport driver.
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index b63d0f001..130bfef21 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -962,7 +962,15 @@ void bx_banshee_c::mem_write(bx_phy_address addr, unsigned len, void *data)
     if (v->fbi.cmdfifo[0].enabled && (offset >= v->fbi.cmdfifo[0].base) &&
         (offset < v->fbi.cmdfifo[0].end)) {
       if (len == 4) {
-        cmdfifo_w(&v->fbi.cmdfifo[0], offset, value);
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 0, *((Bit32u*)data + 0));
+      } else if (len == 8) {
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 0, *((Bit32u*)data + 0));
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 4, *((Bit32u*)data + 1));
+      } else if (len == 16) {
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 0, *((Bit32u*)data + 0));
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 4, *((Bit32u*)data + 1));
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 8, *((Bit32u*)data + 2));
+        cmdfifo_w(&v->fbi.cmdfifo[0], offset + 12, *((Bit32u*)data + 3));
       } else {
         BX_ERROR(("CMDFIFO #0 write with len = %d redirected to LFB", len));
         mem_write_linear(offset, value, len); 
```
Version: 167942816aa9847503c61993091edd2d90cdda42.

**Comment by vruppert** [comment]
Please try the latest Banshee code, since I have no test case here. It doesn't include the changes in other files.

**Comment by Vort** [comment]
Looks like success. Thank you.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/306278ac-b115-449e-a58c-1fde6bfda26c)
