### ISSUE TITLE
Problems with PML were discovered during testing of EFLAGS.RF

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#217]
The entries recorded by PML are not aligned at 4K

BOCHS:
<img width="865" alt="bochs" src="https://github.com/bochs-emu/Bochs/assets/3366897/9e105e72-1a13-4700-8773-e823b8bd19fc">

i76700：
![i76700](https://github.com/bochs-emu/Bochs/assets/3366897/ecf446ab-a48b-4852-a004-9658cbdf458c)

PML_ADDR[6-9] is guest page struct。

[test1.zip](https://github.com/bochs-emu/Bochs/files/13926608/test1.zip)

**Comment by stlintel** [comment]
Yeah just noticed that PML address saved should be always 4K aligned. Fixing now.
