### ISSUE TITLE
Vector logo for project

### ISSUE THREAD

**Issue by yutyo** [bochs-emu/Bochs#22]
Hi! I've tried to make a vector version of the [Bochs logo](https://commons.wikimedia.org/wiki/File:Bochs.png). Here it is:
![image](https://user-images.githubusercontent.com/40173707/207049457-e0ca0874-e476-4b51-8f1a-28f839ad5263.png)

Here is the svg version: https://commons.wikimedia.org/wiki/File:Bochs_Vector_Logo.svg

What do you think? I am open to recommendations.

**Comment by stlintel** [comment]
I think this red smthing is very different from original idea :)
![image](https://user-images.githubusercontent.com/77239907/207262359-67ccdb26-ce5a-4b65-9643-19bc80015db5.png)
