### ISSUE TITLE
Why are the lower 8 bits of the tmpUITT_upidaddr read here masked?

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#225]
https://github.com/bochs-emu/Bochs/blob/0f677ccfc66c2f1376684e87c09940a5f1ba9671/bochs/cpu/uintr.cc#L192C1-L192C2

**Comment by stlintel** [comment]
I don't understand the Q.

```
  // ----------- UITT format --------
  // |     00 | Valid
  // |  07:01 | Reserved, MBZ
  // |  15:08 | UVector, user-level interrupt vector, must be < 64
  // |  63:16 | Reserved, MBZ
  // | 127:64 | UPID_ADDR, linear address of UPID, must be 64-byte aligned
  // --------------------------------

  Bit64u tmpUITT_entry_lo = system_read_qword(BX_CPU_THIS_PTR uintr.uitt_addr + index * 16);
  Bit64u tmpUITT_upidaddr = system_read_qword(BX_CPU_THIS_PTR uintr.uitt_addr + index * 16 + 8);
```

there are total 128 bit
tmpUITT_entry_lo gets bits bits 0-63 (qword)
tmpUITT_upidaddr gets bits 64-127 (second qword)
what is masked ?

You want to say upid_addr is not checked for 64-byte alignment ?
seems like missing check... - agree

**Comment by lgj1107** [comment]
sorry：
shifted right by 8 bits。

**Comment by stlintel** [comment]
> ed right by 8 bits。

it is not shifted, what do you mean ?

**Comment by lgj1107** [comment]
This is the UITT entry I set up：
	.align	64
uitt_addr:
	.quad	0x2f01
	.quad	0xc40

The value printed with BX_INFO is not normal.

00337310209i[CPU0  ] SENDUIPI : index=0x0
00337310209i[CPU0  ] SENDUIPI : uitt_e=0x400000000000002f
00337310209i[CPU0  ] SENDUIPI : upidaddr=0x10000000000000c
00337310209e[CPU0  ] SENDUIPI #GP(0): invalid UITT entry, reserved bits set

**Comment by stlintel** [comment]
Ah, I see. The uitt_addr[0] is SENDUIPI enable bit and it has to be cleared before doing the read together with other reserved bits (bits 3:1 are reserved)

**Comment by lgj1107** [comment]
Okay, it's normal now
