### ISSUE TITLE
No screen updates in Half-Life in Direct3D mode with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#226]
When Half-Life level is loaded with Direct3D mode enabled, screen like this is displayed and nothing else happens.
![bochs_half-life_dx_no_updates](https://github.com/bochs-emu/Bochs/assets/1242858/1d3c7291-3e0f-4eb0-8776-efb937fbaf88)
However, if you move character forward, you can hear footsteps, so game is working, but no image is displayed.

Reason why no image appears is triggering of this condition inside of `bx_voodoo_base_c::update`:
https://github.com/bochs-emu/Bochs/blob/6770a355aed6a9e09d409cb1eac965bb3c6502d1/bochs/iodev/display/voodoo.cc#L580-L583

As opposed to `dxdiag`, which uses `swap_buffers` to update screen (and which works fine), Half-Life uses `blt_screen_to_screen` instead and such code path have no possibility to trigger `gui_update_pending` state.
If I add `v->fbi.video_changed = 1;` right after this line:
https://github.com/bochs-emu/Bochs/blob/6770a355aed6a9e09d409cb1eac965bb3c6502d1/bochs/iodev/display/banshee.cc#L2002
, game starts to work:
![bochs_half-life_dx](https://github.com/bochs-emu/Bochs/assets/1242858/510672d3-40ac-48f5-beb9-35de8f414894)

Such output is glitchy, OpenGL mode works better now. But it is better than nothing.
![bochs_half-life_gl](https://github.com/bochs-emu/Bochs/assets/1242858/19fa0c77-708f-4d0b-acfd-33fa77ae92a0)

Half-Life version: v45/1.1.0.8 ([GOTY edition](https://archive.org/details/half-life-game-of-the-year-edition)).
Bochs version: 6770a355aed6a9e09d409cb1eac965bb3c6502d1.

**Comment by vruppert** [comment]
The gui_update_pending flag is not used for Banshee and Voodoo3 (see line 571, voodoo.cc). There must be a reason why blt_complete() doesn't call redraw_area(). Please see the comparisons in line 1606, banshee.cc. I guess one of them fails and the whole redraw code is skipped.

**Comment by Vort** [comment]
> The gui_update_pending flag is not used for Banshee and Voodoo3 (see line 571, voodoo.cc).

There is `&&` at line 571.
And it causes one more problem sometimes (wrong `pitch`), I justs did not made bug report about it yet.

>  There must be a reason why blt_complete() doesn't call redraw_area(). Please see the comparisons in line 1606, banshee.cc.

`bx_voodoo_base_c::redraw_area` is called. Looks like it is not enough for some reason,

**Comment by vruppert** [comment]
Okay, I understand. Since using bitblt functions in 3D mode is an unhandled case I have added some code for it. Now blt_complete() sets v->fbi.video_changed in 3D mode instead of calling redraw_area(). The pitch issue should be fixed, too.

**Comment by Vort** [comment]
Screen updates now happens correctly. Thank you.
Pitch problem was rare, I made few tests and it is most likely solved too. If not, I will open another issue.
