### ISSUE TITLE
Possible Undefined Behavior in NEG_EdR() and NEG_EdM() 

### ISSUE THREAD

**Issue by barotto** [bochs-emu/Bochs#227]
Consider these 2 lines:

https://github.com/bochs-emu/Bochs/blob/6770a355aed6a9e09d409cb1eac965bb3c6502d1/bochs/cpu/arith32.cc#L495
https://github.com/bochs-emu/Bochs/blob/6770a355aed6a9e09d409cb1eac965bb3c6502d1/bochs/cpu/arith32.cc#L506

The type of `op1_32` is `Bit32u`.
When its value is `0x80000000` (2^31) we have an UB, since that value is not representable as a signed 32 bit.

I came across this problem working on my personal project and asked for help on SO, see this discussion for reference: https://stackoverflow.com/questions/65977673/c-bitwise-and-gives-different-result-with-o0-and-o2/

I think the solution would be removing the cast to `Bit32s`, as negating the unsigned value is well defined.

**Comment by stlintel** [comment]
>I think the solution would be removing the cast to Bit32s, as negating the unsigned value is well defined.

Old legacy Bochs code had (0-val_32) but I remember Visual Studio didn't like that.
Adopted this solution. Thanks !
