### ISSUE TITLE
No video playback in MegaMan X4 with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#231]
After MegaMan X4 game is started, black screen appear.
![bochs_megaman_s1_voodoo](https://github.com/bochs-emu/Bochs/assets/1242858/56351ddf-03f4-4836-a0a4-bb6f0865f350)

Next, red rectangle appear:
![bochs_megaman_s2_voodoo](https://github.com/bochs-emu/Bochs/assets/1242858/9061668b-982c-4fbe-ad65-ce1e4241cdd9)

This is how the same screens looks like with Cirrus card:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/b20549ef-1703-4ddd-b68f-0fe9c72e3338)
![image](https://github.com/bochs-emu/Bochs/assets/1242858/0c12d23e-526d-4158-8814-d4e7d38b8b85)

When videos are finished, game works normally both with Voodoo 3 and Cirrus cards.

Test was made in Windows 98 with 1.07.00 drivers for Voodoo 3.
Version: ab32c8a2bb8596af84372c5fe085220b73073f11.

**Comment by vruppert** [comment]
Is there any useful output in the log file? Where can I find this game for testing?

**Comment by Vort** [comment]
> Where can I find this game for testing?

I found it [here](https://rutracker.org/forum/viewtopic.php?t=5803587) (`magnet:?xt=urn:btih:AEC469205F9F1B675C1828B7DB43CDB594EB8760&dn=X4&tr=http%3a%2f%2fbt4.t-ru.org%2fann&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a6969`), maybe there are better places, I don't know.

> Is there any useful output in the log file?

Nothing interesting at default logging level.
Did not looked at debug level logs yet.

**Comment by vruppert** [comment]
Unfortunately I cannot read most of the text, so I don't know where to click.

**Comment by Vort** [comment]
That link leads to torrent tracker, so it is not enough to just click, torrent client is needed.
After torrent client is loaded, magnet link should be supplied to it (either one I posted before, or from this link: ![image](https://github.com/bochs-emu/Bochs/assets/1242858/d371a8ed-dbd3-4fb7-97e7-d796b25f49cd))
I can try to find direct HTTP link if needed, but I;'m not sure if it is possible.
Or I can reupload files somewhere, where it is easier for you to download from.

**Comment by Vort** [comment]
This change allows video to play properly:
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index 649a61518..a607dde18 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -1024,7 +1024,7 @@ void bx_banshee_c::mem_write(bx_phy_address addr, unsigned len, void *data)
 void bx_banshee_c::mem_write_linear(Bit32u offset, Bit64u value, unsigned len)
 {
   Bit8u value8;
-  Bit32u start = v->banshee.io[io_vidDesktopStartAddr];
+  Bit32u start = v->banshee.io[io_vidDesktopStartAddr] & v->fbi.mask;
   Bit32u pitch = v->banshee.io[io_vidDesktopOverlayStride] & 0x7fff;
   unsigned i, w, x, y;
```
Don't know if this is correct fix or not.

**Comment by Vort** [comment]
**update:** looks like not. If fixes videos 1 and 2. Video 3 still displays incorrectly:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/f3d624dd-d851-48a8-a472-36b103fa3173)

**Comment by Vort** [comment]
I copied some code parts from `bx_banshee_c::blt_complete` and now both modes works fine:
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index 649a61518..7de7629cd 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -1024,7 +1024,7 @@ void bx_banshee_c::mem_write(bx_phy_address addr, unsigned len, void *data)
 void bx_banshee_c::mem_write_linear(Bit32u offset, Bit64u value, unsigned len)
 {
   Bit8u value8;
-  Bit32u start = v->banshee.io[io_vidDesktopStartAddr];
+  Bit32u start = v->banshee.io[io_vidDesktopStartAddr] & v->fbi.mask;
   Bit32u pitch = v->banshee.io[io_vidDesktopOverlayStride] & 0x7fff;
   unsigned i, w, x, y;
 
@@ -1047,6 +1047,13 @@ void bx_banshee_c::mem_write_linear(Bit32u offset, Bit64u value, unsigned len)
     x = (offset % pitch) / (v->banshee.disp_bpp >> 3);
     y = offset / pitch;
     w = len / (v->banshee.disp_bpp >> 3);
+    if (v->banshee.half_mode) {
+      y <<= 1;
+    }
+    if (v->banshee.double_width) {
+      x <<= 1;
+      w <<= 1;
+    }
     if (w == 0) w = 1;
     theVoodooVga->redraw_area(x, y, w, 1);
   } 
```

**Comment by Vort** [comment]
I see no differences visually, but this version should be more correct:
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index 649a61518..8b5804816 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -1024,9 +1024,9 @@ void bx_banshee_c::mem_write(bx_phy_address addr, unsigned len, void *data)
 void bx_banshee_c::mem_write_linear(Bit32u offset, Bit64u value, unsigned len)
 {
   Bit8u value8;
-  Bit32u start = v->banshee.io[io_vidDesktopStartAddr];
+  Bit32u start = v->banshee.io[io_vidDesktopStartAddr] & v->fbi.mask;
   Bit32u pitch = v->banshee.io[io_vidDesktopOverlayStride] & 0x7fff;
-  unsigned i, w, x, y;
+  unsigned i, w, h, x, y;
 
   if (offset >= v->fbi.lfb_base) {
     offset -= v->fbi.lfb_base;
@@ -1047,8 +1047,17 @@ void bx_banshee_c::mem_write_linear(Bit32u offset, Bit64u value, unsigned len)
     x = (offset % pitch) / (v->banshee.disp_bpp >> 3);
     y = offset / pitch;
     w = len / (v->banshee.disp_bpp >> 3);
+    h = 1;
+    if (v->banshee.half_mode) {
+      y <<= 1;
+      h <<= 1;
+    }
+    if (v->banshee.double_width) {
+      x <<= 1;
+      w <<= 1;
+    }
     if (w == 0) w = 1;
-    theVoodooVga->redraw_area(x, y, w, 1);
+    theVoodooVga->redraw_area(x, y, w, h);
   }
   BX_UNLOCK(render_mutex);
 } 
```

It is also possible instead of introducing `h` variable, to just use `v->banshee.half_mode + 1`.
Not sure what method is better.

**Comment by vruppert** [comment]
The changes look okay, so I have applied then to repository.

**Comment by Vort** [comment]
Should height be adjusted as well, like in [my previous message](https://github.com/bochs-emu/Bochs/issues/231#issuecomment-1910796779)?

**Comment by vruppert** [comment]
I saw your updated changes after applying the changes and posting my comment. For the half mode adding the height would be important if the tile height value is odd. Since the Bochs tile height is 24, there is always one tile affected and we should see no visible issues.

**Comment by Vort** [comment]
Ok, thanks. I'm closing issue then.
