### ISSUE TITLE
SSP=0 when VMEXIT, which should not be the correct value.

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#237]
https://github.com/bochs-emu/Bochs/blob/fb428960007e1e4f4c6939446fa5516f707ab6f5/bochs/cpu/vmx.cc#L2458

I added BX_INFO here and found that SSP is 0.

> 00197060798i[CPU0  ] IA32_CET=3
00197060798i[CPU0  ] INT_SSP_TABLE=4000000
00197060798i[CPU0  ] IA32_PL0_SSP=4004000
00197060798i[CPU0  ] IA32_PL3_SSP=4005000
00197060798i[CPU0  ] SSP=0
00579100000p[XGUI  ] >>PANIC<< POWER button turned off.
00579100000i[CPU0  ] CPU is in long mode (active)
00579100000i[CPU0  ] CS.mode = 64 bit
00579100000i[CPU0  ] SS.mode = 64 bit
00579100000i[CPU0  ] EFER   = 0x00000500

**Comment by stlintel** [comment]
I don't understand - and what it supposed to be ?

This is just write of SSP. it is not zero if SSP is in use but might be zero if it is not.
The value of SSP is nothing more than the value of SSP.
Do I miss smth ?

**Comment by lgj1107** [comment]
The manual says, (Document Number: 334525-003, Revision 3.0)

10.6 VM EXIT
On processors that support CET, the VM exit saves the state of IA32_S_CET, SSP and IA32_INTER-RUPT_SSP_TABLE_ADDR MSR to the VMCS guest-state area unconditionally.

**Comment by stlintel** [comment]
A wild guess, did you enter guest with VMX_VMENTRY_CTRL1_LOAD_GUEST_CET_STATE bit cleared ?
In this case you enter to guest without reading from VMCS any CET state and the CET state.
I guess it possible (docs are silent here) that SSP not need to be saved to VMCS as well in this case. i.e. 

  if (BX_CPUID_SUPPORT_ISA_EXTENSION(BX_ISA_CET)) {
    VMwrite_natural(VMCS_GUEST_IA32_S_CET, BX_CPU_THIS_PTR msr.ia32_cet_control[0]);
    VMwrite_natural(VMCS_GUEST_INTERRUPT_SSP_TABLE_ADDR, BX_CPU_THIS_PTR msr.ia32_interrupt_ssp_table);
    VMwrite_natural(VMCS_GUEST_SSP, SSP);
  }

should be guarded with VMX_VMENTRY_CTRL1_LOAD_GUEST_CET_STATE.

This is the case ?

**Comment by stlintel** [comment]
> The manual says, (Document Number: 334525-003, Revision 3.0)
> 
> 10.6 VM EXIT On processors that support CET, the VM exit saves the state of IA32_S_CET, SSP and IA32_INTER-RUPT_SSP_TABLE_ADDR MSR to the VMCS guest-state area unconditionally.

So this is exactly what I do. What is the issue in Subj is still a question.

**Comment by lgj1107** [comment]
VMCS VM-Entry Controls Extensions and VMCS VM-Exit Controls Extensions, bit load_cet_state  are 0.

**Comment by stlintel** [comment]
So what is the Q ?
The controls are zero meaning CET is not loaded from VMCS and this is exactly how Bochs works.

```
  if (vmentry_ctrls & VMX_VMENTRY_CTRL1_LOAD_GUEST_CET_STATE) {
    SSP = guest.ssp;
    BX_CPU_THIS_PTR msr.ia32_interrupt_ssp_table = guest.interrupt_ssp_table_address;
    BX_CPU_THIS_PTR msr.ia32_cet_control[0] = guest.msr_ia32_s_cet;
  }
```

"the VM exit saves the state of IA32_S_CET, SSP and IA32_INTER-RUPT_SSP_TABLE_ADDR MSR to the VMCS guest-state area unconditionally" which is also exactly how Bochs works.

**Comment by lgj1107** [comment]
But I have initialized the relevant MSR for CET in the guest, and according to the manual, it should save the MSR.

**Comment by stlintel** [comment]
Please explain the scenario.

vmentry_ctrls & VMX_VMENTRY_CTRL1_LOAD_GUEST_CET_STATE == 0 (bit clear)

You say you:
1) initialize the MSR and SSP on the guest
2) VMEXIT
3) VMENTER back
3) MSR and SSP are empty ?

Hard to think how it could be according to code.
Do you have a disk image with test ?
How do you determine that this is not your test problem ?
Do you have HW machine with CET support  to verify ?

**Comment by lgj1107** [comment]
1：initialize the MSR and SSP on the guest
2：VMEXIT
Then detect the values saved in VMCS。

I don't have a real machine test. Just follow the manual, step by step.

Try this.  I added xchg bx,bx
[test1.zip](https://github.com/bochs-emu/Bochs/files/14024282/test1.zip)

**Comment by stlintel** [comment]
How do you initialize SSP on the guest ?
I added a debug dump in the CPU loop to print if you ever have SSP != 0 within the CPU_LOOP.

```
if (SSP != 0)
    BX_INFO(("in cpu_loop SSP=%llx\n", SSP));
```

and it never prints.

Also in debugger I see 
   ssp: 00000000_00000000
at the moment of magic breakpoint hit

So SSP was never not 0.

The fact that put smth into MSR doesn't move the value to SSP.
You need to execute SETSSBSY instruction which initializes the SSP and sets shadow stack busy.
And I see you never called this instruction.
So SSP will be forever 0.

**Comment by lgj1107** [comment]
For now, let's stop here.  Later I will test it on a real machine.  I really don't want to play on UEFI.

**Comment by stlintel** [comment]
Please reopen if you see it works on real machine.
