### ISSUE TITLE
Black screen in Descent II: Destination Quartzon 3dfx OEM with Voodoo

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#238]
After Descent II: Destination Quartzon game is started in MS-DOS 6.22, black screen appear and nothing else happens afterwards.
In debug logs register access to Voodoo card can be seen, so some activity before hang happens.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/89b0e974-909c-4545-afdc-5c2fecee3320)

Lots of versions of this game exists, so it is important to pick correct version for testing.
At [this page](https://archive.org/details/20230723_20230723_0858), [Descent II: Destination Quartzon Diamond OEM](https://archive.org/download/20230723_20230723_0858/redump.org/Descent%20II%20-%20Destination%20Quartzon%20%28USA%29%20%28Diamond%20OEM%29.zip) should be picked.
Also game is distributed in `.cue` + `.bin` format, so in order to mount it, Daemon Tools or similar software is needed. Then Bochs should be configured to use real-virtual drive.

Version: ae0c9df3175e2d6f27209b6780f90e3737baa086.

**Comment by Vort** [comment]
**update:** It hangs with MSVC build. With clang build Bochs crashes. Probably it will be easier to track problem with clang. However, crash may happen because of unrelated problem.

**Comment by Vort** [comment]
Crash with clang was a very useful clue.
This problem is very similar to crash related to wrong ROM access in Voodoo 3.
But this time bug is in `bx_voodoo_1_2_c::mem_read_handler`.
I hackfixed it like that and game started successfully:
```diff
diff --git a/bochs/iodev/display/voodoo.cc b/bochs/iodev/display/voodoo.cc
index f16b3e333..86ff3e1ac 100644
--- a/bochs/iodev/display/voodoo.cc
+++ b/bochs/iodev/display/voodoo.cc
@@ -1004,9 +1004,11 @@ void bx_voodoo_1_2_c::after_restore_state(void)
 bool bx_voodoo_1_2_c::mem_read_handler(bx_phy_address addr, unsigned len,
                                        void *data, void *param)
 {
-  Bit32u *data_ptr = (Bit32u*)data;
-
-  *data_ptr = voodoo_r((addr>>2) & 0x3FFFFF);
+  Bit32u val = voodoo_r((addr>>2) & 0x3FFFFF);
+  if (len == 4)
+    *(Bit32u*)data = val;
+  else if (len == 1)
+    *(Bit8u*)data = val >> ((addr & 3) * 8);
   return 1;
 }
```
Please make proper fix.

**Comment by stlintel** [comment]
Seems like perfectly correct fix, merging it.

**Comment by Vort** [comment]
I'm not sure if it is ok to leave other `len`gths unimplemented.
Also I don't know how to implement Big Endian support (mostly because I don't have BE device for testing).

**Comment by vruppert** [comment]
Adding an error message for unimplemented data sizes could be useful. 16-bit support could be added in a similar way. If 8 or 16 byte access exists, it could be done like I did it for Banshee/Voodoo3. Since the data for byte access is shifted, there should be no issue on big endian. For odd data sizes we would need a byte array that requires some special code for big/little endian.

**Comment by Vort** [comment]
I think adding error for unimplemented `len` values and waiting until test case will be found is good choice. Will you make change?

**Comment by stlintel** [comment]
added error message with  0e1c5e35ffd84e1d585d427c708e9cd6a54cd60b

**Comment by Vort** [comment]
Same Descent game also shows `Voodoo mem_read_handler: unknown len=2`.
I wonder how it was possible for it to work well enough without correct reads.

**Comment by Vort** [comment]
> 16-bit support could be added in a similar way.

I thought that such access theoretically can cross boundary of aligned 4 byte blocks.
But `len` = `4` can hit such problem as well. There is no guarantee that discarded 2 bits (`addr>>2`) will be zero.
I tested what access game use (`addr & 3` is `0` in `len` = `2` case), but it is better to have support for all possible cases.

**Comment by Vort** [comment]
With commit 3ec05e8f05da21a189481c003a5463afd936e3f9 applied, this game allowed to uncover yet another problem:
`Voodoo mem_write(): unknown len=1`

> If this is correct and we have a test case for odd length and address, it could be easily added.

Not with FIFA 2000, but with Descent II.

**Comment by vruppert** [comment]
I have now applied the first attempt to fix this issue. If there are unaligned writes, I need to review voodoo_w() how to get rid of this (addr>>2) stuff.

**Comment by Vort** [comment]
I saw `addr & 3` equal `2` and `3`.
Here is how UI looks without 1 byte writes:
![bochs_descent_no1b](https://github.com/bochs-emu/Bochs/assets/1242858/1382803d-48a1-44da-b3c1-2f6eeb6aa0bd)
Here is how UI looks with partially implemented 1 byte writes:
![bochs_descent_1bp](https://github.com/bochs-emu/Bochs/assets/1242858/596fa41b-fcc2-4363-9c1d-0617b1e215e8)

Looks like shade on the right should not be striped with correct implementation.

**Comment by Vort** [comment]
Also shade should not be black, probably alpha mixing or something like that is missing.
Look at "PREPARE FOR DESCENT..." window this video:
https://youtu.be/ec302Jve4CM?si=4kuYjVXdcexyft4z&t=42

![image](https://github.com/bochs-emu/Bochs/assets/1242858/7a5ff3ca-1796-49dc-be96-537d4b6948ae)

**Comment by vruppert** [comment]
I have now applied a new try without modifying the voodoo_w() function. If this one is not okay, I'll have a look what I can do. I have ported the Voodoo stuff from a patch for DOSBox some years ago, but the 3D core is mostly untouched, since I'm not familiar with it.

**Comment by Vort** [comment]
Looks like result became worse.

I said about alpha blending for a reason.
Having such feature means that writes in Voodoo are not that simple, they are more like commands.
You can't just read and write the same value and expect no changes.

As for 3D... it looks like Voodoo in fact have no 3D support - it draws 2D triangles.
It's a responsibility of application programmers to make 3D out of it.
There are depth testing, texturing, blending, dithering, but nothing really complex.
It's a lots of tiny details which make implementation of correct emulation hard.
However, I'm not expert and I may be wrong.

As for problems with this game, probably it is better to revert code to previous state (with black stripes) and close this issue.
Maybe in the future understatding of how to implement memory access properly will come.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/5af2cd6e-235f-4221-9522-01b75a75048e)

**Comment by vruppert** [comment]
I have now applied the final attempt to implement byte writes. If this one doesn't make things better, I'll go back to revision caef53a.

**Comment by Vort** [comment]
It is still not correct, but better than all previous attempts. Thanks.

![bochs_descent_1bp3](https://github.com/bochs-emu/Bochs/assets/1242858/ae291731-6525-498c-9522-cccbe1beb127)

I'm closing this issue.
