### ISSUE TITLE
Parts of MS-DOS Prompt are missing in Windows 95 with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#239]
If MS-DOS Prompt is launched in 256 colors mode and Voodoo 3 card, some text fails to render properly:
![bochs_win_dos_bad](https://github.com/bochs-emu/Bochs/assets/1242858/63dcab4f-49bb-4b12-b027-32d8fbc1d51b)
Same window with Cirrus card looks correct:
![bochs_win_dos_good](https://github.com/bochs-emu/Bochs/assets/1242858/03a8c9ac-18fd-4972-a2c9-24b506975ab1)

Problem reproduces both with Windows 95 and Windows 98.

Version: 30a61c2a5145d0b002b31642e7bcabce76751cf0.

**Comment by vruppert** [comment]
This is a VGABIOS issue- It looks okay with original rom image for Banshee/Voodoo3. I'll have a look what to do.

**Comment by vruppert** [comment]
Win95/98 using VGABIOS functions to set up the MS-DOS prompt window. I have now fixed the TTY functions to use current mode from BDA and call 8-bpp extended mode check only if it is not VGA. Applied to VGABIOS repository.

**Comment by Vort** [comment]
Now text in MS-DOS Prompt shows correctly. Thank you.
