### ISSUE TITLE
Slow switching out of full screen mode for MS-DOS Prompt with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#243]
If I switch MS-DOS Prompt to full screen and back, Bochs freezes for approximately 10 seconds.
Tested with Voodoo 3 and Windows 95.

Video:

https://github.com/bochs-emu/Bochs/assets/1242858/e54fdda5-e4d7-4e65-9832-0a0d5fd1c73d

Version: c4689f284c03558cc2d6545fad2f40a2a9910433.

**Comment by vruppert** [comment]
I cannot confirm this behavior on Windows 95. I have tested both Banshee and Voodoo3 to make sure it's not a driver issue. Exiting from full screen DOS prompt to Windows desktop has no delay in both cases. I only noticed that the first switch of DOS prompt with ALT-ENTER from windowed to full screen mode needs a few seconds, but that's acceptable for me.

**Comment by Vort** [comment]
I figured out what happens.
Lag occurs inside of `bx_vgacore_c::redraw_area` function called from `bx_banshee_c::blt_rectangle_fill`.
Problem is `s.last_yres` during this call equals to `0`.
Which means `yt1` equals `0x0aaaaaaa`.
And loop from `yt0` = `0` to `yt1` takes lots of resources.

If this description is not enough, let me know, I will collect more data.

**Comment by vruppert** [comment]
Okay, I understand. Different results might be caused by different timing setup. I have now added a check for valid screen parameters in redraw_area().

**Comment by Vort** [comment]
Works good now. Thank you.
