### ISSUE TITLE
No sound playback in Impulse Tracker with Sound Blaster 16

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#248]
After loading test music file (`elysium.mod`) into Impulse Tracker and starting playback, nothing happens.

To reproduce this problem, load test configuration attached below and press Enter, Enter, F5.

https://github.com/bochs-emu/Bochs/assets/1242858/534249ae-9acd-438e-94a9-e801501b7536

This is how program should work _(video should be played with sound turned on_):

https://github.com/bochs-emu/Bochs/assets/1242858/093cf33e-eb43-4ea7-b5b5-dd0300cfc633

Impulse Tracker is open source software. Its code can be useful for debugging:
https://github.com/herrnst/impulsetracker

Test files: [impulse.zip](https://github.com/bochs-emu/Bochs/files/14082616/impulse.zip).
Version: b373890b05b696fe9c7eda2817c276c74b08dcee.

**Comment by Vort** [comment]
Impulse Tracker is able to produce sound with `it /S4` (Sound Blaster Pro) driver.
So problem with Sound Blaster 16 is related to differences between Pro and 16.

**Comment by Vort** [comment]
Here are the differences:
`/S4` (Sound Blaster Pro) driver makes DSP Reset only once, when program is started.
`/S5` (Sound Blaster 16) driver makes DSP Reset several times.

Important thing is that `ITSB16` driver makes such reset during active DMA transfer:
```
00608654538 (4) DMA transfer done, triggering IRQ
00608654538 (4) auto-DMA reinitializing to length 2047
00608654741 (4) read from mixer register 82 returns 42
00608654827 (4) 16-bit DMA IRQ acknowledged
00608767178 (5) Received 8-bit DMA: 0x00, 2047 remaining 
00608806995 (4) DSP Reset port write value 1
00608807082 (3) Read access to 0x0226: unsupported port!
00608807163 (3) Read access to 0x0226: unsupported port!
00608807244 (3) Read access to 0x0226: unsupported port!
00608807325 (3) Read access to 0x0226: unsupported port!
00608807406 (4) DSP Reset port write value 0
00608807406 (4) DSP resetting...
00608807406 (4) DSP reset: DMA aborted
00608807406 (4) DMA transfer done, triggering IRQ
00608807610 (4) read from mixer register 82 returns 42
00608807696 (3) 16-bit DMA IRQ acknowledged but not active!
```

And looks like Bochs reacts to such situation incorrectly.
`16-bit DMA IRQ acknowledged but not active!` message is sign of a problem.

I think something is wrong in this place:
https://github.com/bochs-emu/Bochs/blob/ad8c21437f2752a330e2a7eac50ed544b2045e42/bochs/iodev/sound/sb16.cc#L671-L680

`bx_sb16_c::dsp_dmadone` sets `DSP.irqpending = 1;` and then `bx_sb16_c::dsp_reset` just sets it back to `0`.

If I remove `DSP.irqpending = 0;` line from `dsp_reset`, Impulse Tracker with Sound Blaster 16 starts to produce sound.
But, most likely, something smarter should be done with it instead.

**Comment by Vort** [comment]
02f2811 fixed it. Kinda.
It revealed new problem:
No matter which IPS I set (almost), Bochs uses 100% of CPU core and runs at half IPS.
I set 40M, it runs on 20M. I set 10M, it runs at 5M and so on.

**Comment by vruppert** [comment]
After the DSP reset fix the error in the log is fixed, but I still have no sound playback. I can also confirm very low IPS values. While testing several setups I have found an issue with Ben's new BIOS. It hangs at the program startup, so I have created an issue on Ben's page.

**Comment by Vort** [comment]
> but I still have no sound playback

This is strange.
Do you press Enter, Enter, F5 after program is started?

Also here is updated archive just in case: [impulse.zip](https://github.com/user-attachments/files/18241811/impulse.zip).

I hear sound, but it is intermittent because of incorrect IPS:
_(sound playback is disabled by default on GitHub, so you need to manually enable it)_

https://github.com/user-attachments/assets/d90561dd-8384-4dd9-8b8a-d04b836c19a0

**Comment by vruppert** [comment]
Now I got it working. On Linux this program has an additional issue. Since the file menu is empty I had to change to the folder selection, selected "IT" and pressed Enter. Then I pressed F5 and nothing happened. Pressing one more Enter before F5 worked then. Then I tried the Windows version of Bochs with wine and everything worked as you described it. With Ben's BIOS the program enters ann infinite loop in the BIOS code at startup. Maybe this is related to the IPS drop we see with the Bochs BIOS.

**Comment by Vort** [comment]
I figured out why it is lagging. Because of inefficient text rendering.
Lowering `update_freq` "solves" this problem:

`vga: extension=vbe, update_freq=10, realtime=0, ddc=builtin`

![image](https://github.com/user-attachments/assets/a9a2ac5c-dfc9-4da9-a770-b52927561a75)

No sound problem is fixed so I close this issue. Thanks.

**Comment by vruppert** [comment]
The "issue" I found on Linux is a feature. In the config file there is a reference to drive D: and I have created a VVFAT folder for drive D: to copy the folder for DOSbox tests. If drive D: exists, Impulse Tracker selects this drive and I don't see the file.
Lowering the update frequency makes the music output better, but not perfect.

**Comment by vruppert** [comment]
Update: On Windows the display libraries sdl2 and wx have a better performance then win32 when playing music in Impulse Tracker. The text update code in win32 gui needs to be reviewed.

**Comment by Vort** [comment]
> The text update code in win32 gui needs to be reviewed.

I suspect for such tiny characters rendering in software may be faster than thousands of accelerated WinAPI calls. However I did not read that code well enough, so I don't know if it is possible.
