### ISSUE TITLE
Wrong mouse cursor proportions with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#249]
With 320x200 screen mode, cursor is rendered with wrong proportions:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/ecbf1c50-b3c0-4829-844c-b36cf7d79eb0)

It should look like this instead:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/e77f38ad-bb7e-4587-950e-146f26c2ce5b)

Test was performed with Windows 95, Voodoo 3 and this program: [modeset.zip](https://github.com/bochs-emu/Bochs/files/14084454/modeset.zip).

Version: b373890b05b696fe9c7eda2817c276c74b08dcee.

**Comment by vruppert** [comment]
Please try again with the latest code.

**Comment by Vort** [comment]
Cursor proportions are good now. Thank you.
