### ISSUE TITLE
White screen in 800x600 resolution with Cirrus

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#252]
When resolution of Windows XP is switched from 640x480x16 to 800x600x16 with Cirrus card, white screen appear and nothing happens next.
White screen persists even after reboot. To recover Windows from such state, safe mode and registry editor can be used.
It's a regression. This mode was working correctly some time ago.

Video:

https://github.com/bochs-emu/Bochs/assets/1242858/c6b0d511-2f53-4065-8d7c-e593dd8bf7fb

Version: 3ed8639bfa9e4ea6de627801d0743f39ab39cea4.

**Comment by Vort** [comment]
Problem start to appear after 1ebe15e3.
Driver, most likely, waits for `8-bit read from 0x03da = 0x09`, but it never happens.

**Comment by Vort** [comment]
Problem is that `vrstart_usec` (`16820`) and `vrend_usec` (`16978`) become larger than `vtotal_usec` (`16582`).
Something is wrong with timing calculations.

**Comment by Vort** [comment]
It is probably VGABIOS problem (wrong `ccrtc_800x600x16`).
Works good with CL-GD5436/46 PCI VGA BIOS Version 1.25.

**Comment by vruppert** [comment]
I can confirm that this is a VGABIOS issue. I'll have a look at the VGABIOS CRTC parameter lists tomorrow.

**Comment by vruppert** [comment]
Fixed in VGABIOS repository.

**Comment by Vort** [comment]
I checked all modes _(available with built in UI)_ with Windows XP and confirm that no hang happens now. Thanks.
I've found that 1152x864x8 mode (`0x7C`) is not supported, but I don't know if this problem worth solving now.
