### ISSUE TITLE
Crash in vbetest with Cirrus

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#258]
When `vbetest` (from UniVBE 5.1) is started with Cirrus card, it shows `Null code pointer was called` message and exits.
If I swap `VGABIOS-lgpl-latest-cirrus` with `cl-gd5446_pci_vga_bios_version_1.31.u2` (included in archive), `vbetest` starts fine.

Test files: [vbetest.zip](https://github.com/bochs-emu/Bochs/files/14157450/vbetest.zip).
Version: f1e4e6757e73797988cdc2d5954cefe4439a4dfb.

**Comment by vruppert** [comment]
The Cirrus and Banshee version of the VGABIOS don't have a protected mode yet.

**Comment by vruppert** [comment]
I have now added a basic protected mode interface to the Cirrus version. VBETEST starts now, but especially the banked mode is still buggy and the virtual resolution tests are not working. For Banshee/Voodoo3 the protected mode stuff is still to do, but I think we should fix some bugs before I start this task.

**Comment by Vort** [comment]
That was the idea - to uncover possibilities to track more bugs. Thanks.
