### ISSUE TITLE
No swap space error in Quake with Bochs VBE

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#261]
After `VGABIOS-lgpl-latest` change https://github.com/bochs-emu/VGABIOS/commit/6b17d5d0620edcc4560afd6de7cc0e31424cfe87, Quake begins to show such error:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/75b11e3f-0798-4eec-aab4-aa35b8372c4c)

Version: f1e4e6757e73797988cdc2d5954cefe4439a4dfb.

**Comment by vruppert** [comment]
Update: It works with PCI version, but current version fails with ISA.

**Comment by vruppert** [comment]
Fixed in VGABIOS repository.

**Comment by Vort** [comment]
Works good now both with PCI and ISA. Thanks.
