### ISSUE TITLE
Image flicker with disabled Vertical Sync with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#264]
When buffer swaps are not synchronized with screen updates, image flickering may appear:

https://github.com/bochs-emu/Bochs/assets/1242858/9478459b-60cf-4e53-a368-e82ab32b9857

Image tearing effect should appear instead in such case.

Disabled synchronization is default setting for Voodoo 3 drivers in Windows 95:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/f546d598-298e-4a44-9497-2acb5f462956)

To reproduce this problem, test program from this archive should be executed: [GlideTest_v3.zip](https://github.com/bochs-emu/Bochs/files/14191874/GlideTest_v3.zip).

Flickering happens because `bx_voodoo_base_c::update` function assumes `start` and `disp_ptr` variables won't change during its execution. Sometimes it happens this way, but sometimes not. When start pointer in fact changes, `update` function starts to display pixels from incorrect location (back buffer instead of front buffer for example).

Applying such hack does not allow to get rid of flicker completely, but allows to localize it to separate tiles:
```diff
diff --git a/bochs/iodev/display/voodoo.cc b/bochs/iodev/display/voodoo.cc
index e0fbbd403..d6fcb7f84 100644
--- a/bochs/iodev/display/voodoo.cc
+++ b/bochs/iodev/display/voodoo.cc
@@ -693,6 +693,19 @@ void bx_voodoo_base_c::update(void)
           for (yc=0, yti = 0; yc<iHeight; yc+=Y_TILESIZE, yti++) {
             for (xc=0, xti = 0; xc<iWidth; xc+=X_TILESIZE, xti++) {
               if (GET_TILE_UPDATED(xti, yti)) {
+                if ((s.model >= VOODOO_BANSHEE) &&
+                    ((v->banshee.io[io_vidProcCfg] & 0x181) == 0x81)) {
+                    start = v->banshee.io[io_vidDesktopStartAddr];
+                } else {
+                  BX_LOCK(fifo_mutex);
+                  if (s.model >= VOODOO_BANSHEE) {
+                    start = v->fbi.rgboffs[0];
+                  } else {
+                    start = v->fbi.rgboffs[v->fbi.frontbuf];
+                  }
+                  BX_UNLOCK(fifo_mutex);
+                }
+                disp_ptr = &v->fbi.ram[start & v->fbi.mask];
                 if (v->banshee.half_mode) {
                   if (v->banshee.double_width) {
                     vid_ptr = disp_ptr + ((yc >> 1) * pitch + xc); 
```

Some solution to get rid of flicker completely is needed.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/dca6a832-08ad-4aea-a86e-2f46c4378883)

https://github.com/bochs-emu/Bochs/assets/1242858/4e739730-bd16-484c-a702-bea624f89a06

Version: c3269722f43faa1547443c1828c8f2b2c5c83604.

**Comment by vruppert** [comment]
Instead of adding support for start address changes while rendering, I decided to block buffer swapping while rendering.

**Comment by Vort** [comment]
Such solution won't allow to get maximum utilization of host CPU resources, but it have its advantages and it is good for now. Thank you.
