### ISSUE TITLE
File error in Command & Conquer

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#268]
After Command & Conquer game is launched, it displays `FILE ERROR(CONQUER.INI): Bad file number`:
![bochs_cnc](https://github.com/bochs-emu/Bochs/assets/1242858/2cc974f7-c8e5-4079-af79-95265575393a)
It should complain about missing CD instead:
![vbox_cnc](https://github.com/bochs-emu/Bochs/assets/1242858/1b64b637-a184-4915-9bda-e973180f6be9)
Test files: [cnc.zip](https://github.com/bochs-emu/Bochs/files/14235327/cnc.zip).
Version: 30c1e74627f6664f3d3e2e259877c00ad20754d8.

**Comment by vruppert** [comment]
This is a BIOS issue, since it works with SeaBIOS. I'll have a look at the INT 13h functions.

**Comment by vruppert** [comment]
I haven't found the bug in Bochs BIOS yet, but I can confirm that it works correctly with Ben's BIOS (discussion #273).

**Comment by Vort** [comment]
@vruppert I figured out why Command & Conquer glitches:
Problem occurs because `lcmpul` and `lsrul` functions damage `ebx` register.
There are more similar functions nearby, but such change is enough to make Command & Conquer start correctly:
```diff
diff --git a/bochs/bios/rombios.c b/bochs/bios/rombios.c
index d1ec39e1e..e35bfa18c 100644
--- a/bochs/bios/rombios.c
+++ b/bochs/bios/rombios.c
@@ -455,12 +455,14 @@ typedef unsigned long  Bit32u;
   ;; cmp function
   lcmpl:
   lcmpul:
+    push ebx
     and eax, #0x0000FFFF
     shl ebx, #16
     or  eax, ebx
     shr ebx, #16
     SEG SS
       cmp eax, dword ptr [di]
+    pop  ebx
     ret
 
   ;; sub function
@@ -519,6 +521,7 @@ typedef unsigned long  Bit32u;
 
   ;; sr function
   lsrul:
+    push ebx
     mov  cx,di
     jcxz lsr_exit
     and  eax, #0x0000FFFF
@@ -530,6 +533,7 @@ typedef unsigned long  Bit32u;
     mov  ebx, eax
     shr  ebx, #16
   lsr_exit:
+    pop  ebx
     ret
 
   ;; sl function 
```

**Comment by vruppert** [comment]
Thanks for pointing this out. Fixed in Bochs repository now.

**Comment by Vort** [comment]
Should `lmulul`, `ltstul`, `lslul` and `ldivul` be changed as well?

**Comment by vruppert** [comment]
I'll have a look what to do.

**Comment by Vort** [comment]
While 140e2e9 fixed some problems, it added (or uncovered) another problem:
During boot, incorrect size of HDD is displayed, 64 GBytes in this case (39 MBytes should be displayed instead):
![image](https://github.com/bochs-emu/Bochs/assets/1242858/e3b10d14-e19e-4c7c-b135-f9eb02b9eac2)

**Comment by vruppert** [comment]
Now I hope that I have found the right fix for this issue. Preserving EBX in lsrul was wrong, since BX is the hiword of the result. Using 16-bit operations makes sure that the hiwords are not modified. The other helper functions still need to be reviewed.

**Comment by Vort** [comment]
I retested following software and it works fine:
* Command & Conquer
* Open Watcom
* Mortal Kombat
* Mortal Kombat 2

Also HDD size now displayed correctly. Thanks.
