### ISSUE TITLE
Windows 11 24H2 stuck at boot screen on Bochs 2.8 (BIOS retated issue)

### ISSUE THREAD

**Issue by youself64github** [bochs-emu/Bochs#280]
I tried these CPU Configs:

corei5_lynnfield_750
phenom_8650_toliman
corei7_sandy_bridge_2600k
sapphire_rapids

but it got stuck at boot screen when booting Windows 11 24H2 (build 25905 or later) on Bochs 2.8. (this issue does not happen in Bochs 2.7)
[win1124h2test2.bxrc.zip](https://github.com/bochs-emu/Bochs/files/14573702/win1124h2test2.bxrc.zip)

Here's Download Link for this iso:
https://dl.bobpony.com/windows/unofficial/Win11-24H2-TESTER-x64.7z

Maybe POPCNT emulation issue or not?

**Comment by Vort** [comment]
e67fb334 - good
a566b1e6 - bad
Regression is most likely happened somewhere between ~15.12.2023 and ~07.01.2024.
_(That's why it's important to have collection of binaries for different versions)_

**Comment by Vort** [comment]
@stlintel I suspect a67fb31d4fc65a0775ee3110ebbfcd1726d86ebb (or commit very close to it) is causing problems.

**Comment by stlintel** [comment]
How do you decide if it is good or bad ?
For me it is stuck on boot screen even on version you consider as good (https://github.com/bochs-emu/Bochs/commit/3a73e8a0b2b5b5971d4c123d78e2549b690cc0df). Or I didn't wait long enough ?
Does it boot to desktop ?
How long it takes ?

**Comment by stlintel** [comment]
Vort, can you attempt to revert https://github.com/bochs-emu/Bochs/commit/a67fb31d4fc65a0775ee3110ebbfcd1726d86ebb and see if it becomes good ?

**Comment by Vort** [comment]
> For me it is stuck on boot screen even on version you consider as good

Do you use config provided in first message?
It is important to select `model=corei7_sandy_bridge_2600k` if I understand correctly.

**Comment by youself64github** [comment]
> > For me it is stuck on boot screen even on version you consider as good
> 
> Do you use config provided in first message? It is important to select `model=corei7_sandy_bridge_2600k` if I understand correctly.

Yes. I tried this config, but it has same issue.

**Comment by Vort** [comment]
> Vort, can you attempt to revert https://github.com/bochs-emu/Bochs/commit/a67fb31d4fc65a0775ee3110ebbfcd1726d86ebb and see if it becomes good ?

It was nearby commit, not this one, sorry.
Specifically, these lines:

https://github.com/bochs-emu/Bochs/blob/2314cbcfe14f53bbe25b7e8589ec48291f3701d5/bochs/cpu/cpuid.cc#L90-L91

> How long it takes ?

Several minutes.

> Does it boot to desktop ?

To this screen:

(I will add it few minutes later)

**Comment by stlintel** [comment]
Were you able to boot GIT latest tree when fixing these 2 lines ?
For me I was not able to boot it yet with any git revision 

This is my .bochsrc:

```
# configuration file generated by Bochs
#plugin_ctrl: voodoo=false, unmapped=true, biosdev=true, speaker=true, extfpuirq=true, parallel=true, serial=true, busmouse=false, e1000=false, es1370=false, gameport=true, ne2k=false, sb16=false, usb_uhci=false, usb_ohci=false, usb_ehci=false, usb_xhci=false
config_interface: win32config
display_library: win32
memory: guest=1024, host=1024, block_size=128
romimage: file="bios/BIOS-bochs-latest", address=0x00000000, options="fastboot", flash_data=none
vgaromimage: file="bios/VGABIOS-lgpl-latest"
boot: cdrom
floppy_bootsig_check: disabled=0
floppya: type=1_44
# no floppyb
ata0: enabled=true, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=cdrom, path="..\..\disks\Win11-24H2-TESTER-x64.iso", status=inserted, model="Generic 1234", biosdetect=auto
ata0-slave: type=none
ata1: enabled=true, ioaddr1=0x170, ioaddr2=0x370, irq=15
ata1-master: type=none
ata1-slave: type=none
ata2: enabled=false
ata3: enabled=false
pci: enabled=1, chipset=i440fx, slot1=none, slot2=none, slot3=none, slot4=none, slot5=none
vga: extension=vbe, update_freq=5, realtime=1, ddc=builtin
cpu: count=1, ips=500000000, model=corei7_sandy_bridge_2600k, reset_on_triple_fault=1, cpuid_limit_winnt=0, ignore_bad_msrs=1, mwait_is_nop=0
print_timestamps: enabled=0
port_e9_hack: enabled=false, all_rings=false
private_colormap: enabled=0
clock: sync=realtime, time0=local, rtc_sync=0
# no cmosimage
log: .bochs.log
logprefix: %t%e%d
debug: action=ignore
info: action=report
error: action=report
panic: action=ask, siminterface=report
keyboard: type=mf, serial_delay=250, paste_delay=100000, user_shortcut=none
mouse: type=ps2, enabled=false, toggle=ctrl+mbutton
#sound: waveoutdrv=win, waveout=none, waveindrv=win, wavein=none, midioutdrv=win, midiout=none
speaker: enabled=true, mode=sound, volume=15
parport1: enabled=true, file=none
parport2: enabled=false
com1: enabled=true, mode=null
com2: enabled=false
com3: enabled=false
com4: enabled=false

```

**Comment by Vort** [comment]
> Were you able to boot GIT latest tree when fixing these 2 lines ?

Yes (99% sure).

> This is my .bochsrc:

I modified paths and it works for me.

---

Can you check with my binary? [bochs.zip](https://github.com/bochs-emu/Bochs/files/14603053/bochs.zip)

No need to wait for full boot.
If you see this and nothing else, this is bad result:
```
01686127274e[CPU0  ] RDMSR: Unknown register 0x17
01686127405e[CPU0  ] RDMSR: Unknown register 0x17
01686127536e[CPU0  ] RDMSR: Unknown register 0x17
01686127667e[CPU0  ] RDMSR: Unknown register 0x17
01686127798e[CPU0  ] RDMSR: Unknown register 0x17
01686166708i[BIOS  ] int13_harddisk: function 08, unmapped device for ELDL=80
05373176194e[CPU0  ] RDMSR: Unknown register 0x8b
05393297877e[CPU0  ] RDMSR: Unknown register 0x1a0
05393297895e[CPU0  ] WRMSR: Unknown register 0x1a0
05393439013e[CPU0  ] WRMSR: Unknown register 0x8b
05393439036e[CPU0  ] RDMSR: Unknown register 0x8b
```

If it continues like that, this is good result:
```
05404097675i[CPU0  ] RDMSR: Read 00000000:fee00900 from MSR_APICBASE
05404124289i[CPU0  ] RDMSR: Read 00000000:fee00900 from MSR_APICBASE
05404124640e[CPU0  ] RDMSR: Unknown register 0x179
05404124737i[APIC0 ] set timer divide factor to 1
05404127527i[IOAPIC] IOAPIC: could not write, IOREGSEL=0x01
05404127527i[IOAPIC] IOAPIC: could not write, IOREGSEL=0x01
05404127527i[IOAPIC] IOAPIC: setting id to 0x1
05404140822i[CPU0  ] WARNING: Architectural Performance Monitoring is not implemented
05404141003i[CPU0  ] WARNING: Architectural Performance Monitoring is not implemented
05404141003e[CPU0  ] RDMSR: Unknown register 0x345
05404141078i[CPU0  ] WARNING: Architectural Performance Monitoring is not implemented
05404142374i[CPU0  ] WRMSR: write into IA32_PERFEVTSEL0 MSR: 00000000:00000000
05404142374e[CPU0  ] WRMSR: Unknown register 0x186
05404142408i[CPU0  ] WRMSR: write into IA32_PERFEVTSEL1 MSR: 00000000:00000000
05404142408e[CPU0  ] WRMSR: Unknown register 0x187
05404142433i[CPU0  ] WRMSR: write into IA32_PERFEVTSEL2 MSR: 00000000:00000000
...
```

**Comment by youself64github** [comment]
> > Were you able to boot GIT latest tree when fixing these 2 lines ?
> 
> Yes (99% sure).
> 
> > This is my .bochsrc:
> 
> I modified paths and it works for me.
> 
> Can you check with my binary? [bochs.zip](https://github.com/bochs-emu/Bochs/files/14603053/bochs.zip)
> 
> No need to wait for full boot. If you see this and nothing else, this is bad result:
> 
> ```
> 01686127274e[CPU0  ] RDMSR: Unknown register 0x17
> 01686127405e[CPU0  ] RDMSR: Unknown register 0x17
> 01686127536e[CPU0  ] RDMSR: Unknown register 0x17
> 01686127667e[CPU0  ] RDMSR: Unknown register 0x17
> 01686127798e[CPU0  ] RDMSR: Unknown register 0x17
> 01686166708i[BIOS  ] int13_harddisk: function 08, unmapped device for ELDL=80
> 05373176194e[CPU0  ] RDMSR: Unknown register 0x8b
> 05393297877e[CPU0  ] RDMSR: Unknown register 0x1a0
> 05393297895e[CPU0  ] WRMSR: Unknown register 0x1a0
> 05393439013e[CPU0  ] WRMSR: Unknown register 0x8b
> 05393439036e[CPU0  ] RDMSR: Unknown register 0x8b
> ```
> 
> If it continues like that, this is good result:
> 
> ```
> 05404097675i[CPU0  ] RDMSR: Read 00000000:fee00900 from MSR_APICBASE
> 05404124289i[CPU0  ] RDMSR: Read 00000000:fee00900 from MSR_APICBASE
> 05404124640e[CPU0  ] RDMSR: Unknown register 0x179
> 05404124737i[APIC0 ] set timer divide factor to 1
> 05404127527i[IOAPIC] IOAPIC: could not write, IOREGSEL=0x01
> 05404127527i[IOAPIC] IOAPIC: could not write, IOREGSEL=0x01
> 05404127527i[IOAPIC] IOAPIC: setting id to 0x1
> 05404140822i[CPU0  ] WARNING: Architectural Performance Monitoring is not implemented
> 05404141003i[CPU0  ] WARNING: Architectural Performance Monitoring is not implemented
> 05404141003e[CPU0  ] RDMSR: Unknown register 0x345
> 05404141078i[CPU0  ] WARNING: Architectural Performance Monitoring is not implemented
> 05404142374i[CPU0  ] WRMSR: write into IA32_PERFEVTSEL0 MSR: 00000000:00000000
> 05404142374e[CPU0  ] WRMSR: Unknown register 0x186
> 05404142408i[CPU0  ] WRMSR: write into IA32_PERFEVTSEL1 MSR: 00000000:00000000
> 05404142408e[CPU0  ] WRMSR: Unknown register 0x187
> 05404142433i[CPU0  ] WRMSR: write into IA32_PERFEVTSEL2 MSR: 00000000:00000000
> ...
> ```

I checked with this binary, it works fine. :) I have to use this binary for Windows 11 24H2 (build 25905 or later)

**Comment by stlintel** [comment]
Honestly I don't really understand what the CPUID should be for UNIPOCESSOR configuration (1 core 1 thread 1 processor).
Never observed such a system :)

If windows thinks these two lines should be reverted - no problem with that.
Can you submit PR ?

**Comment by Vort** [comment]
> Can you submit PR ?

Done: #285.

**Comment by youself64github** [comment]
Windows 11/Server 24H2 build 26212.5000 not working in Bochs 2.8 even with latest development build (it was working properly in Bochs 2.7)
