### ISSUE TITLE
Change Max emulated instruction per second from 4294967295 to 10000000000

### ISSUE THREAD

**Issue by youself64github** [bochs-emu/Bochs#286]
I tried changing emulated instruction per second to 10000000000. but it gets these message:
Numerical parameter 'ips' was set to 10000000000, which is out of range 1000000 to 4294967295. and I can't set ips beyond 4294967295 properly.

**Comment by Vort** [comment]
Why you need this?
4G IPS (2^32 - 1) is close to performance of real CPU and way higher than any emulation can achieve.

**Comment by youself64github** [comment]
> Why you need this? 4G IPS (2^32 - 1) is close to performance of real CPU and way higher than any emulation can achieve.

Because some heavy workloads needs over 4G IPS.

**Comment by Vort** [comment]
If emulation can't run that fast, then what's the point?
Do some software refuses to run with <= 4G IPS?
Or you plan to perform non-realtime emulation?

**Comment by youself64github** [comment]
> If emulation can't run that fast, then what's the point? Do some software refuses to run with <= 4G IPS? Or you plan to perform non-realtime emulation?

Very Heavy websites in Chrome or Firefox will be very laggy with <= 4G IPS single core. very few softwares runs laggy with <= 4G IPS

**Comment by stlintel** [comment]
My laptop runs 1.3Ghz. I bet it doesn't reach 4G IPS either even natively.
I tend to dismiss such request.
Are you sure IPS is the problem ?

**Comment by qeeg** [comment]
@stlintel That's pretty slow by today's standards, and it sounds like your laptop is either super old, or super low-end. My laptop has a 4.3 GHz BASE clock, and it runs pretty fast in general. My desktop's CPU is about the same age, and runs at 5.4 GHz at basically all times. They also both have VERY high IPC as well, so they'd probably be faster than your laptop even if clocked at the same low clock rate.

**Comment by Vort** [comment]
It's better to describe exact situation where 2G IPS emulation performs worse than 4G IPS emulation.
So anyone can check it. Most likely, it happens because of some bug, and not IPS by itself.
And bugs worth fixing of course.
