### ISSUE TITLE
IPv6 support for Slirp networking in Bochs?

### ISSUE THREAD

**Issue by youself64github** [bochs-emu/Bochs#292]
I need to add IPv6 support for Slirp networking in Bochs as IPv6 is more futureproof than IPv4. as Internet usually don't work on users with IPv6-only internet unless you implement IPv6 in Slirp networking. IPv4 has address exhaustion issues that doesn't happens in IPv6.

**Comment by vruppert** [comment]
I have now added support for using external libslirp library instead of builtin slirp. Bochs must be compiled with --enable-using-libslirp option and IPv6 support can be enabled then in slirp.conf.

**Comment by youself64github** [comment]
> I have now added support for using external libslirp library instead of builtin slirp. Bochs must be compiled with --enable-using-libslirp option and IPv6 support can be enabled then in slirp.conf.

Does it work for Windows users?

**Comment by youself64github** [comment]
I tried to compile with libslirp support via MinGW-32 Cross Compiler or Linux, but it fails even with libslirp-dev installed.

**Comment by vruppert** [comment]
On Windows I have only tested libslirp support with msys64/mingw64. I haven't tested it with Cygwin yet. Cross compiling with an additional library (DLL) requires a "cross" version of this library. On Linux the libslirp-dev package doesn't have the required binary files for linking with the DLL. I intend to update the builtin slirp sources based on the latest libslirp code to make it available for MSVC and cross compilation.

**Comment by youself64github** [comment]
> On Windows I have only tested libslirp support with msys64/mingw64. I haven't tested it with Cygwin yet. Cross compiling with an additional library (DLL) requires a "cross" version of this library. On Linux the libslirp-dev package doesn't have the required binary files for linking with the DLL. I intend to update the builtin slirp sources based on the latest libslirp code to make it available for MSVC and cross compilation.

It gets these error message:
x86_64-w64-mingw32-g++ -c  -I.. -I../.. -I./.. -I./../.. -I../../instrument/stubs -I./../../instrument/stubs  -DWIN32 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -O3 -Wall -Wno-format -mno-ms-bitfields -DWIN32 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES   eth_slirp.cc -o eth_slirp.o
eth_slirp.cc:38:10: fatal error: slirp/libslirp.h: No such file or directory
   38 | #include <slirp/libslirp.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
I am using Linux-x86_64 to compile Windows version of Bochs with libslirp.

**Comment by vruppert** [comment]
I told you that you'll need a "cross" version of libslirp when compiling on Linux for Windows. Since the configure script detects the Linux version, you may assume that it's correct. I think I have to disable the libslirp detection for the cross compiling case.

**Comment by youself64github** [comment]
> I told you that you'll need a "cross" version of libslirp when compiling on Linux for Windows. Since the configure script detects the Linux version, you may assume that it's correct. I think I have to disable the libslirp detection for the cross compiling case.

How to get cross version of libslirp?

**Comment by vruppert** [comment]
Updating Bochs builtin slirp from libslirp 4.8.0 is now finshed. IPv6 support is now enabled by default and ready fot testing.
