### ISSUE TITLE
increse BX_PACKET_BUFSIZE

### ISSUE THREAD

**Issue by ne-vlezay80** [bochs-emu/Bochs#308]
Modern linux kernel support transfer big package via tun/tap interface (up to 65520).

Please increse the variable.

**Comment by vruppert** [comment]
The value of BX_PACKET_BUFSIZE depends on the maximum size the emulated network devices can send / receive, but on the capabilites of the lowlevel interface. Ethernet frames are limited to 1514 bytes, so we cannot set it higher for this type of network hardware.
