### ISSUE TITLE
Wrong rendering of text cursor in Edit

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#314]
This is how text cursor under `^` character looks:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/6be869f4-604b-457d-b435-0d643b492791)
And this is how it should look (and probably it should also blink):
![image](https://github.com/bochs-emu/Bochs/assets/1242858/d5b57598-7bd0-4749-ab0d-712cee342638)
Full screenshots:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/37bcf3ad-5ebc-4c56-a179-89bafd88f9ca)
![image](https://github.com/bochs-emu/Bochs/assets/1242858/fe1857a4-4a17-4450-8e6d-08019fa4a32c)

Test files: [edit.zip](https://github.com/bochs-emu/Bochs/files/15197087/edit.zip).
Version: 74df052

**Comment by vruppert** [comment]
The rendering issue seems to appear in win32 gui only. The DrawBitmap() function needs to be reviewed. The reversed display starts at font row 0, but it should be cursor start row. Missing blinking is a general issue. I'll have a look.

**Comment by Vort** [comment]
Ok, this problem is fixed, thank you. So I'm closing this issue.
However I have doubts if inversion (like with letter `p`) should happen.
It looks good, yeah, but on real hardware cursor just renders on top of character.
