### ISSUE TITLE
Image corruption in BMC demo

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#317]
Discs with old games, which I use for testing, contain installer software.
When installer is executed, corrupted image appear on screen.

Since installer is quite complex, I needed to find simpler program to reproduce this problem, and I found it.
Program in attached archive just displays disc covers, but, most likely, use the same technology for image output, because it suffers from the same corruption:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/f82771d7-6cff-4fc8-b429-48dcf987345e)

I tested 3 virtual video cards:
* Bochs VBE - works bad;
* Voodoo 3 - works bad;
* Cirrus - works good.

Test files: [BMC.ZIP](https://github.com/bochs-emu/Bochs/files/15260689/BMC.ZIP)
Version: 49736dd.

**Comment by vruppert** [comment]
I have now fixed the Banshee / Voodoo3 VGABIOS. The Cirrus VGABIOS uses 64k for both window size and granularity, but both Bochs VBE and Banshee VGABIOS using 64k window size and 32k granularity. Please test it with games / demos using banked mode VBE. If everything is okay, I'll have a look at the Bochs VBE stuff.

**Comment by Vort** [comment]
I don't know if I will be able to find banked mode game, but for now I performed test with VBETest (from #258). I also have source code for this (or very similar) test, you can look what this code expects from BIOS: [svgakt51.zip](https://github.com/bochs-emu/Bochs/files/15367467/svgakt51.zip).

Here is the result of making 0-1-1-0 test with Voodoo 3:
Before:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/f9e1ccd1-961c-4839-8df4-61b312021ff5)
After:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/9aa20459-2670-4f8d-8d83-15bfddb27f98)

**Comment by vruppert** [comment]
I have now also fixed the Bochs VBE case. This particular issue should be fixed now, but vbetest still has some issues that should be investigated later.

**Comment by Vort** [comment]
I don't understand completely how your change works, but it looks like avoiding problem.
I mentioned VBETest because available source code may help to figure out what is really going on.
For example, `SRC\SVGAKIT\SVGASDK.C` have these lines:
```cpp
	bankShift = 0;
	while ((64 >> bankShift) != modeInfo.WinGranularity)
		bankShift++;
```
`bankShift` variable can be searched in other files to find what is affected by it.

However, since BMC demo and VBETest looks good now, I'm closing this bug report. Thanks.

**Comment by vruppert** [comment]
The BMC demo expects window size and granularity to be set to the same size. It sets bank to 0 and fills the first 64k, then increments bank by one and assumes to fill the next 64k. Since granularity was 32k, we got this image corruption. My fixes set the reported granularity to 64k and the VBE get/set window functions need to do a shift by one. Now both Banshee and Bochs VBE look better in vbetest, but Cirrus still has issues in protected mode.

**Comment by Vort** [comment]
I wonder why VBETest wasn't working properly with 32k granularity.
It is strange because its code is aware of granularity setting and handles it somehow.
Looks like something prevents it from doing what it should do.
