### ISSUE TITLE
Black screen with SeaBIOS and Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#322]
When I try to boot Voodoo 3 system with `bios.bin-1.13.0` instead of `BIOS-bochs-latest`, black screen appears:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/50e1888e-e7a8-4fe0-8afb-7b025a10567d)

For comparison, Cirrus configuration boots fine:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/bbb5b647-8a7b-4790-b464-06e639ebc6f0)

Test files: [sea.zip](https://github.com/bochs-emu/Bochs/files/15373116/sea.zip)
Version: b76ead9

**Comment by vruppert** [comment]
I think this is a SeaBIOS issue. It also doesn't work with latest release 1.16.3 and original Banshee / Voodo3 VGABIOS. I had a look at the sources, but haven't found the reason for the failure yet. It doesn't seem to detect the VGA compatible adapter correctly and then it doesn't copy the PCI ROM data to RAM at 0xc0000. I haven't found out how to send some more debug information to the Bochs BIOS info port.

**Comment by Vort** [comment]
> it doesn't copy the PCI ROM data to RAM at 0xc0000

How Cirrus card work then? Without such copying?

**Comment by vruppert** [comment]
Both Cirrus and Bochs VBE cards are detected correctly, but for Banshee / Voodoo3 the SeaBIOS reports an incorrect ROM signature and doesn't copy it to RAM. A closer look at the SeaBIOS sources is required. I have attached SeaBIOS image with serial port debugging and debug level 6 and my serial port output file. Use this in your bochsrc config:

com1: mode=file, dev=serial.txt

[bios.bin.zip](https://github.com/bochs-emu/Bochs/files/15377624/bios.bin.zip)
[serial-banshee.txt](https://github.com/bochs-emu/Bochs/files/15377644/serial-banshee.txt)

**Comment by Vort** [comment]
@vruppert I have found approximate location of bug:

https://github.com/bochs-emu/Bochs/blob/ccfdb05e29124dbe6da28d7f0a2397d4fed49d49/bochs/iodev/display/banshee.cc#L887-L893

When second byte is accessed, address incremented twice: by ` + i` and `addr++`.

**Comment by vruppert** [comment]
I have also found it after looking at the SeaBIOS sources. It checks the signature with a 16-bit read, but Bochs BIOS uses 8-bit reads from BIOS ROM only.

**Comment by Vort** [comment]
Fixed with 7b2a322d2f4528ce31853dcaf337e5e2042688b0. Thanks.
