### ISSUE TITLE
Black screen in Windows 95 with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#325]
During Windows 95 load with Voodoo 3 card, black screen appears instead of desktop.
This problem start to happen after 244e35a.
![image](https://github.com/bochs-emu/Bochs/assets/1242858/419e7211-9e58-4e88-a325-0e56d34b07b9)

**Comment by vruppert** [comment]
Fixed off-by-one bug.

**Comment by Vort** [comment]
Thanks.
