### ISSUE TITLE
Gui debugger on Windows crashes on memory dump

### ISSUE THREAD

**Issue by dracconi** [bochs-emu/Bochs#326]
On Windows, compiled with VS2017, v141, bochs-2.8-msvc-src.

When trying to perform a memory dump (linear or physical) from the GUI menu, an assert fails in the CRT library and makes the whole program exit.

From the VS debugger and later patching, it fails on the isprint (enh_dbg.c:2006) call in FillDataX (enh_dbg.cc:1997). I figure that this is due to
```c
char C = 0xfb; // negative number
isprint((int)C) // C gets expanded with signed rules, thus becoming 0xfffffffb
// assert fails here in crt
```

This can be patched by making C explicitly expanded to int through unsigned rules. Such that `0xfb` maps to `0x000000fb`.

**Comment by stlintel** [comment]
would changing the function prototype to unsigned char fix the issue ?

void FillDataX(unsigned char* t, unsigned char C, bool doHex)

**Comment by dracconi** [comment]
> would changing the function prototype to unsigned char fix the issue ?
> 
> void FillDataX(unsigned char* t, unsigned char C, bool doHex)

I have temporarily patched it in my build is as following, and it does not crash. I suppose changing it in the function prototype, as you have suggested, would indeed fix the issue.
```c
// performs endian byteswapping the hard way, for a Data dump
void FillDataX(char* t, char C, bool doHex)
{
    char tmpbuf[40];
    char *d = tmpbuf;
    if (isLittleEndian == FALSE || doHex == FALSE)
        d = t + strlen(t);  // bigendian can always be appended directly
    *d = C;
    d[1] = 0;
	unsigned int const tmpc = (unsigned char)C;
    if (isprint(tmpc) == 0)
        *d = '.';```

**Comment by stlintel** [comment]
please check if it works fine now

**Comment by stlintel** [comment]
no response, assume it is fixed
