### ISSUE TITLE
SDL_OpenAudio() failed

### ISSUE THREAD

**Issue by Githubmaniak** [bochs-emu/Bochs#33]
After booting Windows 95, Skyroads was executed using MS-DOS mode, but Bochs terminated with SDL_OpenAudio() Failed displayed.

**Comment by vruppert** [comment]
We need some more information to find out what's going wrong (host platform, SDL version, sound config options used).

**Comment by vruppert** [comment]
I'll close this issue now, since no additional information was provided.
