### ISSUE TITLE
Memory dump not updating in the debugger GUI 

### ISSUE THREAD

**Issue by Natisfaction** [bochs-emu/Bochs#333]
While debugging some code, I noticed that the memory dump (both physical and linear) doesn't update when the memory is modified, even when clicking the refresh button. The only way to force an update is by reopening the memory dump GUI.

I assume it's not intended due to the fact that the stack view updates properly. I'm using Ubuntu 24.04 x64, don't know if this could be helpful tho...

**Comment by vruppert** [comment]
I have now added some code to handle the refresh request correctly by the memory dump window. For an auto -update at break it would be required to create a backup of the dump buffer and redraw if this portion of memory has been modified.

**Comment by Natisfaction** [comment]
Saw the commit, thank you for addressing this, I think that it's fine even if it doesn't refresh at each break, cause the refresh button works. I wanted to try it now, but I'm stuck in building it with the GUI debugger. I get this two lines while executing the `./configure` script:

`configure: WARNING: The Bochs debugger gui cannot be compiled here, disabling it
configure: WARNING: The USB debugger cannot be compiled here, disabling it`

All the libraries are installed, including x, gtk2. Anyways, I'm closing this issue, as it's likely that this is a problem on my end.

**Comment by vruppert** [comment]
Update: I have now added a mechanism to force a memory dump window update after break if the selected portion of memory has been modified.
