### ISSUE TITLE
Black screen after resolution change in Windows 9x with CL-GD5446

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#339]
When I change resolution in Windows 9x with CL-GD5446 from 1024x768x16 to 800x600x16, black screen appears.

Regression test reveals that problem started to appear after commit 4455da0e.

**Comment by vruppert** [comment]
I have now fixed a win32 gui issue with 15 bpp modes. The display wasn't black here, but frozen. Does it work for you, too?

**Comment by Vort** [comment]
> Does it work for you, too?

Yes, commit 79c820e solves this problem. Thank you.
