### ISSUE TITLE
Alpine Linux fails to boot with modern CPU

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#343]
When I try to boot [Alpine Linux 3.19](https://uk.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-standard-3.19.1-x86_64.iso) from CD with `corei7_icelake_u` CPU, it fails:
![bochs_alpine_fail](https://github.com/user-attachments/assets/0b383e55-b0bf-4a2b-89de-34dbd56fbdbc)

Works good with `p4_prescott_celeron_336`:
![bochs_alpine_good](https://github.com/user-attachments/assets/d887cd89-6822-4049-b6f4-c80976051195)

Config and logs: [Alpine_bug.zip](https://github.com/user-attachments/files/16824794/Alpine_bug.zip)
Version: 0138ad4

**Comment by stlintel** [comment]
Confirmed: works well with corei7_skylake_x and doesn't work with corei3_cnl
Checking ...

**Comment by stlintel** [comment]
Fixed in 67b83d

**Comment by Vort** [comment]
Main problem with boot is solved, thank you.

However more problems appear from time to time during boot with `corei7_icelake_u`.
I'm not creating bug report about them yet because I can't figure out exact conditions for bug reproduction.

1. Arithmetic exception
2. Failed to verify signature of /media/cdrom/boot/modloop-tls!

![bochs_alpine_bad2](https://github.com/user-attachments/assets/a82447e8-0883-4ab0-8c5a-bde015117ad5)

![bochs_alpine_bad3](https://github.com/user-attachments/assets/7bc1b384-26b7-43fc-ac34-e4a15cde2ea8)
