### ISSUE TITLE
Bad FPU state detected in Alpine Linux

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#344]
After I load [Alpine Linux 3.19](https://uk.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-standard-3.19.1-x86_64.iso) from CD with `corei7_icelake_u` CPU, FPU related error can be seen in `dmesg` output.

To reproduce this problem:
1. Load Alpine Linux with this config file: [Alpine_bug2.zip](https://github.com/user-attachments/files/16828304/Alpine_bug2.zip);
2. Wait until login prompt appear, enter `root` as login and press Enter;
3. Type `dmesg|less`, press Enter;
4. Press Space 16 times.

Here are the screenshots of what appears afterwards:
![bochs_alpine_fpregs1](https://github.com/user-attachments/assets/ce01a3e2-5a11-4174-84ca-16c73dc207af)
![bochs_alpine_fpregs2](https://github.com/user-attachments/assets/1d79ed2e-3309-4e78-8438-b7c07b07100f)
![bochs_alpine_fpregs3](https://github.com/user-attachments/assets/d5f95768-c5f1-431d-a4ca-e88d26812f4c)

Version: 8d6ac22

**Comment by stlintel** [comment]
I have no idea how to approach this debug ...
Can you think of a way  to reach that point of failure ?
What was detected ? Unexpected floating point exception ?
It seems like #GP was generated why restoring floating point state ... but I can't be sure.
Is it possible to have debugger break on the point of failure somehow ?

**Comment by Vort** [comment]
> Can you think of a way to reach that point of failure ?

Older CPUs like `p4_prescott_celeron_336` have no such problem.
Which means half-split method can be applied.

> Is it possible to have debugger break on the point of failure somehow ?

Looks like Linux address space randomization makes stack trace somewhat useless.
I think it should be possible to rebuild linux with randomization turned off.

For other questions - i have no idea yet.

**Comment by stlintel** [comment]
This is because issue happens in XRSTOR instruction. Older processors without XSAVE/XRSTOR just don't run the same code

**Comment by Vort** [comment]
I don't know if this information is useful or not, but here is corresponding piece of code:
https://github.com/torvalds/linux/blob/431c1646e1f86b949fa3685efc50b660a364c2b6/arch/x86/mm/extable.c#L127-L128

**Comment by stlintel** [comment]
Wow, I found it. 
Silly bug in XRSTOR introduced while fixing another bug for Bochs 2.8 :(
Fixed in https://github.com/bochs-emu/Bochs/commit/de278480fadf27ae9348c6a2e155f806243b878c

**Comment by Vort** [comment]
> Fixed in https://github.com/bochs-emu/Bochs/commit/de278480fadf27ae9348c6a2e155f806243b878c

I see two format specifiers in `BX_ERROR` here, `%s` and `%08x`:
https://github.com/bochs-emu/Bochs/blob/de278480fadf27ae9348c6a2e155f806243b878c/bochs/cpu/sse_move.cc#L328
But only single parameter is passed - `new_mxcsr`.
Is it correct?

**Comment by stlintel** [comment]
Absolutely correct, fixed
