### ISSUE TITLE
Image corruption in WinMode program with CL-GD5446

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#359]
After WinMode program from [CL-GD5446 driver v1.31](https://github.com/user-attachments/files/16976462/CLGD5446.zip) is started with regular Windows 3.11 VGA driver and `VGABIOS-lgpl-latest-cirrus`, it displays wrong colors:

![image](https://github.com/user-attachments/assets/6907da66-9d86-4acf-bc38-b4f1943d6fd2)

When BIOS is changed to `cl-gd5446_pci_vga_bios_version_1.31.u2`, colors become correct:
![image](https://github.com/user-attachments/assets/a98e8391-fbdd-43ad-ad91-dac442063262)

Version: 85c58ff

**Comment by Vort** [comment]
I figured out what is going wrong here:
`vgabios call ah4F al15 bx0001 cx0000 dx0000` changes sequencer index to `0x08` and never restores it to its original value.
In case of WinMode program, value for index before BIOS call is set to `0x02`.
If I add such hack, image corruption disappear (but I think proper restoring should be done instead):
```diff
diff --git a/vgabios/clext.c b/vgabios/clext.c
index 8be7cb2..b7a3cdc 100644
--- a/vgabios/clext.c
+++ b/vgabios/clext.c
@@ -1989,6 +1989,9 @@ cirrus_vesa_15h_01:
   call cirrus_ddc_send_status
   loop cirrus_vesa_15h_01
   call cirrus_ddc_stop
+  mov  dx, #0x3c4
+  mov  al, #0x02
+  out  dx, al
   pop  di
   pop  cx
   mov  ax, #0x004f
```

**Comment by vruppert** [comment]
Correct fix applied to VGABIOS repository.

**Comment by Vort** [comment]
Thank you.
