### ISSUE TITLE
Missing support for Cirrus 4 bpp modes

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#360]
When Windows 3.11 CL-GD5446 driver tries switching to 800x600x4 or 1024x768x4 modes, switch to 640x480x4 happens instead.

It happens because Cirrus modes 0x58 and 0x5D are missing from BIOS tables.
With `vgatables.h` hacked this way, driver is able to switch to 800x600x4 mode successfully, but such solution is of course incorrect - proper implementation is needed.
```diff
diff --git a/vgabios/vgatables.h b/vgabios/vgatables.h
index ff6e7a8..adea6d9 100644
--- a/vgabios/vgatables.h
+++ b/vgabios/vgatables.h
@@ -85,7 +85,7 @@
  * Tables of default values for each mode
  *
  */
-#define MODE_MAX   15
+#define MODE_MAX   16
 #define TEXT       0x00
 #define GRAPH      0x01
 
@@ -129,6 +129,7 @@ static VGAMODES vga_modes[MODE_MAX+1]=
  {0x11, GRAPH, PLANAR1, 1, 0xA000, 0x02, 0x1a},
  {0x12, GRAPH, PLANAR4, 4, 0xA000, 0x02, 0x1b},
  {0x13, GRAPH, LINEAR8, 8, 0xA000, 0x03, 0x1c},
+ {0x58, GRAPH, PLANAR4, 4, 0xA000, 0x02, 0x1d},
  {0x6A, GRAPH, PLANAR4, 4, 0xA000, 0x02, 0x1d}
 };
```

Besides Windows 3.11, VBETest shows lack of these modes as well:
![image](https://github.com/user-attachments/assets/dd51be8f-089c-4c2f-beb0-71c1f90d6017)

With `cl-gd5446_pci_vga_bios_version_1.31.u2`, these modes are in place:
![image](https://github.com/user-attachments/assets/5b55ccc1-8104-420b-a153-b835c90387ec)

Version: 85c58ff450adaca3371ae0bd9a799773d4f562a7

**Comment by vruppert** [comment]
I have now added some test code for 4 bpp mode 0x58 (800x600x4). It simply switches to VGA mode 0x6a and then changes mode number to 0x58. Adding new tables entries for the 4 bpp modes is relatively simple, but it requires some special code to clear VRAM to avoid seqfault and for VBE support some special cases in VESA function 0x01.

**Comment by vruppert** [comment]
Update: I have now added Cirrus mode 0x58 with regular table entries and improved the code to support 4 bpp. There are still issues with some apps: winmode draws a black bar, some DOS cause Bochs to segfault. I'd like to fix these issues before I continue with mode 1024x768 and VBE support.

**Comment by Vort** [comment]
> There are still issues with some apps: winmode draws a black bar

I see black bar on the desktop (while winmode looks fine in this particular configuration):
![image](https://github.com/user-attachments/assets/c925a040-5d86-48f0-9bc3-03648ff1f21c)

**Comment by vruppert** [comment]
After some fixes in the VGABIOS, the black bar and the segfault when testing mode with old DOS program "whatvga" are gone here. If everything is okay at this point, I could start with the VBE part as the next step.

**Comment by Vort** [comment]
800x600x4 support looks good now.

**Comment by vruppert** [comment]
Now most of the VBE stuff for 4 bpp is done. VBE mode 0x0102 works correct and looks okay here with vbetest.

**Comment by vruppert** [comment]
I have now added Cirrus mode 0x5d (VBE mode 0x0104) to the VGABIOS. With vbetest everything looks fine, but in Windows 3.11 with Cirrus driver there are issues. Since the hardware cursor pattern is stored within display memory, you'll have either display or cursor corruption. I also noticed that after closing a menu the background is not restored correctly. These issues appear with both original VGABIOS and our LGPL VGABIOS.

**Comment by Vort** [comment]
> but in Windows 3.11 with Cirrus driver there are issues

Window movement is glitched in a similar way to #364:
1px up and 4px right produce distinctive glitches.
1,2,3px right is less glitchy, but just because it is doing almost nothing.

Also, my hack from #364 makes cursor movement in X direction worse.
So I think these problems may be related.

**Comment by Vort** [comment]
I figured out why cursor movement was incorrect in my build: `bool svga_double_width` was not initialized.

Putting
`BX_CIRRUS_THIS svga_double_width = 0;`
after this line
https://github.com/bochs-emu/Bochs/blob/8c053ca361a5ec2623f7928268cfdc4065d7e6d5/bochs/iodev/display/svga_cirrus.cc#L290
solved this problem.

**Comment by vruppert** [comment]
I have now added this line in Bochs repository. For now I'd like to continue with VGABIOS development (e.g. 1280x1024x4 mode) and have a look at Cirrus emulation issues later.

**Comment by Vort** [comment]
I figured out how to fix 1024x768x4 mode:
```diff
diff --git a/bochs/iodev/display/svga_cirrus.cc b/bochs/iodev/display/svga_cirrus.cc
index d671ebbed..149a0eec3 100644
--- a/bochs/iodev/display/svga_cirrus.cc
+++ b/bochs/iodev/display/svga_cirrus.cc
@@ -832,7 +832,7 @@ void bx_svga_cirrus_c::mem_write(bx_phy_address addr, Bit8u value)
   }
 #endif // BX_SUPPORT_PCI
   if ((BX_CIRRUS_THIS sequencer.reg[0x07] & 0x01) == CIRRUS_SR7_BPP_VGA) {
-    if ((BX_CIRRUS_THIS control.reg[0x0b] & 0x1e) != 0) {
+    if ((BX_CIRRUS_THIS control.reg[0x0b] & 0x1f) != 0) {
       BX_CIRRUS_THIS vga_mem_write(addr,value);
     } else {
       BX_CIRRUS_THIS bx_vgacore_c::mem_write(addr,value);
@@ -1558,7 +1558,7 @@ void bx_svga_cirrus_c::draw_hardware_cursor(unsigned xc, unsigned yc, bx_svga_ti
     tile_ptr = bx_gui->graphics_tile_get(xc, yc, &w, &h) +
                info->pitch * (cy0 - yc) + (info->bpp / 8) * (cx0 - xc);
     if (BX_CIRRUS_THIS svga_dispbpp == 4) {
-      hwc_offset = 0x40000 - 16384; // VGA (TODO: check this)
+      hwc_offset = 0x200000 - 16384; // VGA (TODO: check this)
     } else {
       hwc_offset = BX_CIRRUS_THIS memsize_mask - 16383; // Cirrus
     } 
```

Without proper processing of GRB[0], banking was broken.

**Comment by vruppert** [comment]
Thanks, I think this is the final fix for the hardware cursor. Now I intend to continue with mode 1280x1024x4 to make this issue complete.

**Comment by Vort** [comment]
I think 4bpp support is good enough now to close this issue, thank you.

![bochs_pagemaker_4bpp](https://github.com/user-attachments/assets/14077b72-00a7-428c-a8aa-417dda02ce44)
