### ISSUE TITLE
Dotted lines when moving window in Windows 3.11 with CL-GD5446 driver

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#361]
If partially hidden window is slowly moved from bottom left corner to the top right corner, extra dotted lines appear:
![bochs_cirrus_win_move](https://github.com/user-attachments/assets/b8c2cab2-7ce1-4c12-9cf8-4295b5bd58c1)

It's a regression from 85c58ff. No such lines appear with 9054a9c.

More specifically, `height - 1` is what causes problems.

Version: 85c58ff

**Comment by vruppert** [comment]
Sorry, my fault. I thought that the height needs to be decremented if the redraw area continues on the left side of the display. Fixed.

**Comment by Vort** [comment]
Thanks.
