### ISSUE TITLE
bx_dbg_read_linear: physical memory read error (phy=0x000100000000, lin=0x0000000100000000)

### ISSUE THREAD

**Issue by HuangXiCi** [bochs-emu/Bochs#363]
I download the bochs-2.8 from github and sourceForge, and the configurations are as follow: ./configure --enable-debugger --enable-iodebug --enable-x86-debugger --with-x --with-x11 --enable-x86-64. I use the Ubuntu22.04, and if i don't add "--enable-x86-64" option, the message will not appear. But when i run bochs x86-64 emu, not yet running any code, the gui debugger will tell me the following information. How can i fix it? I hope my English level will not affect your reading.
![bochs](https://github.com/user-attachments/assets/ca22ce51-a152-4d0c-a319-e073c89dfdaa)

**Comment by HuangXiCi** [comment]
I have two bochs-2.8 in my computer, another one is 32-bit bochs-emu, that one is working well. They are using the same bochsrc as the configuration file. And though the 64-bit bochs-emu tell me the message physical memory read error, but it could work.

**Comment by stlintel** [comment]
Fixed
