### ISSUE TITLE
Incorrect video playback with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#369]
When video playback is started in Windows 95 with Voodoo 3 using ActiveMovie Control, incorrect output is produced and log starts to fill with `[VOODOO] vidProcCfg: chromaKey mode not supported yet` messages.

Video playback with Voodoo 3:
![bochs_movie_voodoo3](https://github.com/user-attachments/assets/5748ec44-dce5-40bb-8011-81216dbea6f5)

Video playback with Cirrus:
![bochs_movie_cirrus](https://github.com/user-attachments/assets/e746d3e4-a68b-4882-9817-44297ae7d23b)

Test file: [BigBuckBunny_320x180_crop_cinepak_adpcm.zip](https://github.com/user-attachments/files/17504003/BigBuckBunny_320x180_crop_cinepak_adpcm.zip).

Version: 7373c19.

**Comment by vruppert** [comment]
Here I'm getting different error messages about "unsupported filter mode". The most important missing feature is the combined desktop / overlay mode. The update code needs a second pass for drawing extra content in a small window. Currently it is drawing the extra data as tiles on the whole desktop.

**Comment by vruppert** [comment]
I have now modified the Voodoo update code and added some testing code for the desktop / overlay mode. For the 16 bpp desktop resolution I have added basic black and white output for the YUV format. The correct YUV-to-RGB conversion still needs to be written.

**Comment by Vort** [comment]
> For the 16 bpp desktop resolution I have added basic black and white output for the YUV format. The correct YUV-to-RGB conversion still needs to be written.

My main concern was efficient overlaying code, color transformations may be tuned later, it's fine.

> I have now modified the Voodoo update code and added some testing code for the desktop / overlay mode.

I noticed one minor problem:
Instead of 320x180, overlay is displayed with 321x180 size.
I think `<= v->banshee.overlay.x1` in two places should be replaced with `< v->banshee.overlay.x1`.

Also it looks strange to me that desktop gets brighter after video playback is started, but, maybe this is how it works on real hardware, don't know.

**Comment by vruppert** [comment]
According to the specs the "end screen coordinate" defines the lower right edge of the overlay region. On the other side the YUV color format defines either 2 or 4 pixels per data packet, so this odd size is unusual. I have now applied some optimizations for the new code.

**Comment by Vort** [comment]
> According to the specs the "end screen coordinate" defines the lower right edge of the overlay region.

Both "closed" and "open" intervals exist, it is little weird to have mix of them, but totally possible.
Anyway, correct output is a priority. Proper puzzle solution can obtained later _(like happened with hardware cursor for Cirrus card)_.

> I have now applied some optimizations for the new code.

Less host CPU usage than with Cirrus card now, nice.
However, window moving produces ghosts often enough.
Both previous and present overlay location should be updated I think.

**Comment by Vort** [comment]
This quote suggests confusion with overlay dimensions:
`H5\W2K\Src\Video\Displays\H5\DDOVL32.C`
```cpp
  // Fix for PRS 12592, we dec the overlay height by 1 move the bottom up by 1 line
  // rVidDst.bottom-1;  jmccartney 09/06/00
  //Overlay screen bottom, right
#ifndef WINNT
  wOvlScrEndX = min(rOvlDst.right, wDesktopW-1);
  wOvlScrEndY = min(rOvlDst.bottom-1, wDesktopH-1);
```

**Comment by vruppert** [comment]
I have now added color support for overlay format 6 based on formulas found on Wikipedia. The overlay window dimensions still need to be verified. Having test cases for other overlay formats would be nice.

**Comment by Vort** [comment]
> The overlay window dimensions still need to be verified.

Do you have ideas about how to better understand this problem?

> Having test cases for other overlay formats would be nice.

Try selecting different options in [BSplayer Pro](https://github.com/user-attachments/files/17531661/BSPLAYER_PRO122.817.ZIP) maybe:

![image](https://github.com/user-attachments/assets/b76d0ecd-1fd8-42ac-9eff-7ad8dc7d3cd7)

**Comment by Vort** [comment]
Also [vlc-0.8.4a-win32.zip](https://github.com/user-attachments/files/17690880/vlc-0.8.4a-win32.zip) produces strange output and lags:
![image](https://github.com/user-attachments/assets/53965ccc-249a-4a3e-a31f-20de5ec23b4f)
_(VLC may crash during first launch and it is glitchy overall, so it should be used as reference with caution)_

> I have now added color support for overlay format 6 based on formulas found on Wikipedia.

Colors look dim, but this is low priority problem.

**Comment by vruppert** [comment]
No progress with the overlay window dimension. Since the overlay stride is 640 bytes (320 pixels) the window width cannot be larger than 320, but the horizontal scaling is active and increases the maximum overlay display size to 322. I think I'll continue working on other issues and return to it later.
The BSPlayer Pro uses screen-to-screen stretching with conversion from YUV source. I think it's possible to implement it based on the new code from get_overlay_pixel().
The VLC media player uses the unimplemented YUV planar space to write data to the framebuffer. I have found some infos in the specs and I think it's possible to implement it.

**Comment by Vort** [comment]
I did not figured out how scaling works yet, so I can't say much about it.
However, I remembered interesting property of overlays: they use chroma key.

Overlay may be of wrong size, but before displaying it should be clipped by dark-purple color key, which may make incorrect size hard to notice.
This property allows to play videos when player is covered by its own screenshot, or covered with drawing in mspaint made with specific color. It can help to uncover which size overlay really have on real hardware (in case someone will gain access to it).

Here is a program I found which may help implementing chroma key: [overlaydemo_exe.zip](https://github.com/user-attachments/files/17692475/overlaydemo_exe.zip).
Noise should appear _below_ destop icons.
I tested this program on real hardware (Windows XP with GeForce card), can't make screenshot of it however.

**Comment by vruppert** [comment]
Adding YUV planar space write support makes the video visible with VLC media player, but it still has issues. I'll have a look the the chroma key stuff next.

**Comment by Vort** [comment]
I see, good.
Meanwhile I found another bug.
When two player processes are launched, one of them uses overlay, but other one uses something else.
And that "something else" produces glitches. Here is how it looks with 32bpp mode:
![image](https://github.com/user-attachments/assets/f740e760-1a82-4729-bc69-e4d7f70719ad)

**Comment by vruppert** [comment]
When I try it here on Win95, the display looked different and the log reported unsupported pixel format conversion. I finally added YUV format conversion support to the screen-to-screen BitBlt code to fix it. This my not fix the issue I see above.

**Comment by Vort** [comment]
With c0d9481 Bochs crashes right after Windows 95 desktop shows up.
It happens because `dpxsize` variable should remain signed.
Otherwise `dpxsize *= -1;` produces wrong result.

Problem with two video players is probably fixed, will recheck when `dpxsize` problem will be solved.

**Comment by vruppert** [comment]
After changing type of dpxsize back to signed I have now added some chroma key testing code for 16 bpp. It is based on the BitBlt color key stuff.

**Comment by Vort** [comment]
Context menus are displayed correctly now in 16 bpp mode:
![image](https://github.com/user-attachments/assets/150e32c9-5a06-4bc7-a36c-402827714af2)

**Comment by Vort** [comment]
With ae7b672 commit cursor in [Ballance](https://archive.org/details/BallanceEuropeEnFrDeEsIt) game rendered incorrectly:
![bochs_ballance_cursor](https://github.com/user-attachments/assets/e56ca8d2-c535-4009-aa61-d9e8b78a19bd)

**Comment by Vort** [comment]
> ... based on formulas found on Wikipedia ...

> ... it still has issues ...

I have better formulas _(which can be further tweaked/optimized, especially data types)_:
_(https://learn.microsoft.com/en-us/windows/win32/medfound/recommended-8-bit-yuv-formats-for-video-rendering#converting-8-bit-yuv-to-rgb888)_
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index 0f369121c..7427a5f69 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -520,8 +520,10 @@ Bit32u bx_banshee_c::get_overlay_pixel(unsigned xc, unsigned yc, Bit8u bpp)
 {
   Bit16u index = 0;
   Bit32u value = 0;
-  unsigned ox, oy, r = 0, g = 0, b = 0;
-  Bit8u *vid_ptr, data[4], px, Y[2];
+  unsigned ox, oy;
+  Bit16s r = 0, g = 0, b = 0;
+  Bit8u *vid_ptr, data[4], px;
+  Bit16s Y[2];
   Bit8s U, V;
 
   ox = (unsigned)((double)(xc - v->banshee.overlay.x0) * v->banshee.overlay.fx);
@@ -535,22 +537,22 @@ Bit32u bx_banshee_c::get_overlay_pixel(unsigned xc, unsigned yc, Bit8u bpp)
   }
   if ((v->banshee.overlay.format == 5) || (v->banshee.overlay.format == 6)) {
     if (v->banshee.overlay.format == 5) {
-      Y[0] = data[0];
+      Y[0] = data[0] - 0x10;
       U = data[1] - 0x80;
-      Y[1] = data[2];
+      Y[1] = data[2] - 0x10;
       V = data[3] - 0x80;
     } else {
       U = data[0] - 0x80;
-      Y[0] = data[1];
+      Y[0] = data[1] - 0x10;
       V = data[2] - 0x80;
-      Y[1] = data[3];
-    }
-    r = (unsigned)(Y[px] + (double)V / 0.877);
-    if (r > 255) r = 255;
-    g = (unsigned)(Y[px] - (double)U * 0.39393 - (double)V * 0.58081);
-    if (g > 255) g = 255;
-    b = (unsigned)(Y[px] + (double)U / 0.493);
-    if (b > 255) b = 255;
+      Y[1] = data[3] - 0x10;
+    }
+    r = Y[px] * 1.164383 + V * 1.596027;
+    g = Y[px] * 1.164383 - U * 0.391762 - V * 0.812968;
+    b = Y[px] * 1.164383 + U * 2.017232;
+    CLAMP(r, 0x00, 0xff);
+    CLAMP(g, 0x00, 0xff);
+    CLAMP(b, 0x00, 0xff);
     index = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
   } else if ((v->banshee.overlay.format == 1) ||
              (v->banshee.overlay.format == 7)) {
@@ -2387,8 +2389,9 @@ Bit32u bx_banshee_c::blt_yuv_conversion(Bit8u *ptr, Bit16u xc, Bit16u yc,
                                         Bit16u pitch, Bit8u fmt, Bit8u pxsize)
 {
   Bit32u value = 0;
-  unsigned r, g, b;
-  Bit8u *src_ptr, data[4], px, Y[2];
+  Bit16s r, g, b;
+  Bit8u *src_ptr, data[4], px;
+  Bit16s Y[2];
   Bit8s U, V;
 
   px = xc & 1;
@@ -2398,22 +2401,22 @@ Bit32u bx_banshee_c::blt_yuv_conversion(Bit8u *ptr, Bit16u xc, Bit16u yc,
     data[i] = *(src_ptr + i);
   }
   if (fmt == 8) {
-    Y[0] = data[0];
+    Y[0] = data[0] - 0x10;
     U = data[1] - 0x80;
-    Y[1] = data[2];
+    Y[1] = data[2] - 0x10;
     V = data[3] - 0x80;
   } else {
     U = data[0] - 0x80;
-    Y[0] = data[1];
+    Y[0] = data[1] - 0x10;
     V = data[2] - 0x80;
-    Y[1] = data[3];
-  }
-  r = (unsigned)(Y[px] + (double)V / 0.877);
-  if (r > 255) r = 255;
-  g = (unsigned)(Y[px] - (double)U * 0.39393 - (double)V * 0.58081);
-  if (g > 255) g = 255;
-  b = (unsigned)(Y[px] + (double)U / 0.493);
-  if (b > 255) b = 255;
+    Y[1] = data[3] - 0x10;
+  }
+  r = Y[px] * 1.164383 + V * 1.596027;
+  g = Y[px] * 1.164383 - U * 0.391762 - V * 0.812968;
+  b = Y[px] * 1.164383 + U * 2.017232;
+  CLAMP(r, 0x00, 0xff);
+  CLAMP(g, 0x00, 0xff);
+  CLAMP(b, 0x00, 0xff);
   if (pxsize == 2) {
 #ifdef BX_LITTLE_ENDIAN
     value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3); 
```

**Comment by vruppert** [comment]
I have now applied your suggested changes for the YUV-to-RGB conversion. The VLC media player display looks better now with the test video. It would be nice to have something like a test image formerly used to adjust the analogue color TV display. I have also added 24 / 32 bpp chroma key check support. I still don't know what can go wrong in the Ballace game. The mentioned commit inverts the logic for the chroma key check disabled case. I had a black overlay window on Win95 before this change unless I opened the context menu which turns on chroma key check while it's visible.

**Comment by Vort** [comment]
> I still don't know what can go wrong in the Ballace game. The mentioned commit inverts the logic for the chroma key check disabled case.

Cursor code considers 3D overlay as 2D overlay.
I can provide more information if needed.

**Comment by vruppert** [comment]
I have now added some save/restore code for the new feature and tried to fix the 3d cursor issue.

**Comment by Vort** [comment]
Cursor in Ballance looks good with 637b9d4.

I think overlay support is good enough now to close this issue. Thank you.
