### ISSUE TITLE
Restore Configuration interface on Restore

### ISSUE THREAD

**Issue by fysnet** [bochs-emu/Bochs#37]
The current source does not restore the Configuration Interface on a restore.

The bx_real_sim_c::restore_config() reads in the saved bochrc file, parsing the "config_interface:" line.

Then in config.cc, 
```
if (!SIM->get_param_enum(BXPN_SEL_CONFIG_INTERFACE)->set_by_name(params[1]))
      PARSE_ERR(("%s: config_interface '%s' not available", context, params[1]));
```
Tries to set the configuration interface.

However, since the get_param_enum(BXPN_SEL_CONFIG_INTERFACE) is not enabled, it doesn't set it to the found interface.

`get_param_enum(BXPN_SEL_CONFIG_INTERFACE)->get_enabled()  returns 0.`

paramtree.cc:
```
void bx_param_num_c::set(Bit64s newval)
    {
      if (!enabled) return;
```
returns instead of setting the restored interface.

Therefore, the restore reverts to the textconfig interface instead of the found interface ("win32config" in my case).

The (BXPN_SEL_CONFIG_INTERFACE) gets disabled in main.cc, line 334 before we read in the bochrc file (when restoring a sim),
and after reading the bochrc file when starting a new sim.

**Comment by vruppert** [comment]
Can you confirm that this issue is fixed?

**Comment by fysnet** [comment]
Yes, I can confirm. Thank you.
