### ISSUE TITLE
Hang in QuickView with Bochs VBE

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#371]
After QuickView 1.03b starts playing video in 800x600x16 mode with Bochs VBE, it either hangs or causes Bochs to crash.
With Cirrus card, playback starts fine _(except for horrible noises instead of sound)_.

![image](https://github.com/user-attachments/assets/73d868b3-2537-46b4-b00c-7ef6c71d073b)

Test files: [QV.ZIP](https://github.com/user-attachments/files/17531155/QV.ZIP)

Version: a94ebf9

**Comment by vruppert** [comment]
Please try again with the latest VGABIOS binary. There was a bug in the "set bank" farcall code.

**Comment by Vort** [comment]
No hang anymore. Thank you.
