### ISSUE TITLE
Lags during window movement in Windows XP with CL-GD5446

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#373]
When window in Windows XP is positioned at y=0 coordinate and moved to the right, Bochs starts to use 100% of host CPU core and hangs for several seconds.

For example, put Task Manager window like so and move it 1 pixel to the right:
![image](https://github.com/user-attachments/assets/028d64a2-41af-4693-957c-55053f96234f)

I observed this effect with 1024x768x24 mode, but it may be present in other modes as well.

Version: 884d898

**Comment by Vort** [comment]
Lags happen when `redraw.h` becomes `0` here:

https://github.com/bochs-emu/Bochs/blob/42e7c31e93bb9a12a01dc79add6b0ba339a1f102/bochs/iodev/display/svga_cirrus.cc#L3185

Such change allows to get rid of lags, but I don't know if it is correct.

```diff
diff --git a/bochs/iodev/display/svga_cirrus.cc b/bochs/iodev/display/svga_cirrus.cc
index e2320771f..b83d55242 100644
--- a/bochs/iodev/display/svga_cirrus.cc
+++ b/bochs/iodev/display/svga_cirrus.cc
@@ -3181,6 +3181,7 @@ void bx_svga_cirrus_c::svga_bitblt()
       } else {
         BX_CIRRUS_THIS redraw.x -= BX_CIRRUS_THIS redraw.w;
       }
+      BX_CIRRUS_THIS redraw.y++;
       if (BX_CIRRUS_THIS redraw.h > BX_CIRRUS_THIS redraw.y) {
         BX_CIRRUS_THIS redraw.h = BX_CIRRUS_THIS redraw.y;
         BX_CIRRUS_THIS redraw.y = 0; 
```

**Comment by vruppert** [comment]
I have fixed this issue in a different way.

**Comment by Vort** [comment]
Ok, thanks.
