### ISSUE TITLE
Corrupted image in full screen MS-DOS Prompt in Windows 95 with CL-GD5446

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#375]
When MS-DOS Prompt in Windows 95 with CL-GD5446 card is started, it loads in windowed mode and works correctly.
But after switching to full screen mode, this shows up:

![bochs_msdos](https://github.com/user-attachments/assets/42e7e0e7-6449-469c-9524-c5bb4add8f41)

Version: 47b05e5

**Comment by Vort** [comment]
Hard to say if this issue is related to VGABIOS or emulation:
1. With latest commit 47b05e55e12b3bba93414c51f40b86cf083f9b53 and `cl-gd5446_pci_vga_bios_version_1.31.u2` no problem appear.
2. Regression tests show that there was no problem in case of using `VGABIOS-lgpl-latest-cirrus` before ec469aa:
2024.09.13 bochs-48824a4 - good
2024.09.17 bochs-ec469aa - black
2024.09.18 bochs-d4cee9c - bad

**Comment by vruppert** [comment]
In text mode the standard VGA update code must be used. Fixed.
