### ISSUE TITLE
Hardware cursor is not disabled correctly after mode switch in Windows 95 with CL-GD5446

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#376]
After video mode is switched from 640x480x24 to 640x480x4 in Windows 95 with CL-GD5446, "ghost" cursor appear:

![image](https://github.com/user-attachments/assets/22cf1a62-4fb6-4717-b4b3-710edd81de4f)

Version: 87eeb9d

**Comment by vruppert** [comment]
Fixed in LGPL VGABIOS repository.
