### ISSUE TITLE
Add bochs to playstore

### ISSUE THREAD

**Issue by Coryxkenshin-pixel** [bochs-emu/Bochs#383]
My request is to add bochs to playstore because it would make it easier to download.

**Comment by Vort** [comment]
This is where programs for Android located, right?
If so, this problem should be resolved first:
https://github.com/bochs-emu/Bochs/discussions/342#discussioncomment-10575833 _(there are no official Android port of Bochs)_

**Comment by Coryxkenshin-pixel** [comment]
Ok
