### ISSUE TITLE
Broken support for CL-GD5430 ISA with Windows 95

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#391]
When Windows 95 boots with CL-GD5430 ISA card and default Cirrus Logic 5429/30/34/36 driver, it either BSODs (640x480x24 mode) or hangs (640x480x8 mode) right after desktop is loaded.

![bochs_clgd5430_bsod](https://github.com/user-attachments/assets/eeae121c-22f1-4ab9-9f3e-5f00a294a075)

Log contains lines like `[CIRRUS] bank offset 002c0000 is invalid`, but I'm not sure if that's the only problem which prevents video card from working correctly.

Version: 6aa4160

**Comment by vruppert** [comment]
I tried Cirrus ISA here with LGPL VGABIOS and the default drivers of Win95B in 8, 16 and 24 bpp without any issues.

**Comment by Vort** [comment]
Looks like crash depends on amount of icons in system tray.
Initially I had 4 of them + clock, then tried following:
1. Single sound indicator - no crash;
2. Single language indicator - no crash;
3. Language indicator + just added sound indicator - crash (sometimes).

Besides `bank offset ... is invalid` I have also these messages:
`[CPU0  ] write_virtual_checks(): write beyond limit, r/w expand down`, `[CIRRUS] CLGD543x_MMIO_BLTTRANSPARENTCOLOR`, `[CIRRUS] CLGD543x_MMIO_BLTTRANSPARENTCOLORMASK`, `[CIRRUS] MMIO blt write - address 0x0024, value 0x20`, `[CIRRUS] MMIO blt write - address 0x0025, value 0x17`, ... Maybe they are related to this problem.

**Comment by Vort** [comment]
There are many things which can crash system with CL-GD5430 driver:
Opening Internet Explorer, Total Commander, dxdiag, Printers from Control Panel.
System is unstable overall.
I suspect memory corruption happening somewhere, but I need to check integrity of driver files as well.

**Comment by Vort** [comment]
Turns out, bank switching, which causes `bank offset ... is invalid` messages, happens inside of Page Fault handler.
Here is a screenshot of code, which attempts switching to first invalid bank, `control: index 0x09 write 0x80`:
![cirrus_int0e](https://github.com/user-attachments/assets/c97a468b-a349-4954-a7ff-dc303b13229a)

**Comment by Vort** [comment]
Actually, `VFLATD.VXD` is designed to handle cases of changing GDTR.
To catch moments, when it can change, VflatD installs hook for `vmm.vxd!_Allocate_GDT_Selector`:
![image](https://github.com/user-attachments/assets/5a69d834-7047-446d-8ec9-37aa165e675b)
However, in some cases _(with some of my Windows installations)_ hook fails to install properly:
It installs correctly in one place (`vmm.vxd!_Call_On_My_Not_Flat_Stack` (PCOD:C0025310)), but not in other place (THCR:C004612C from vmm.vxd).

**Comment by sskras** [comment]
Wow, very impressive debugging skills, @Vort .

On the other hand I wonder if this could also happen on bare metal (using he same configuration).

**Comment by Vort** [comment]
Thanks.
I don't have real CL-GD5430 to check it.
But anyway, I also wasn't able to figure out which differences between my image files trigger this problem.
So it is totally possible to get "good" result on real hardware just because of slightly different installation and not because bug is not there.

One more thing I noted is that with Bochs probems with HDD controller appear sometimes.
Sometimes devices look good in device manager:
![image](https://github.com/user-attachments/assets/71e77a0e-5c43-4447-8d55-535c9c0f77a9)
Sometimes secondary controller show exclamation mark.

Also debug logs sometimes contain errors related to HDD:
`[BIOS  ] int13_harddisk: function 08, unmapped device for ELDL=81`
May be related to problems with video driver, may be not.
[bochsout_good.txt](https://github.com/user-attachments/files/17881827/bochsout_good.txt), [bochsout_bad.txt](https://github.com/user-attachments/files/17881828/bochsout_bad.txt)

**Comment by Vort** [comment]
Problem was simpler than I imagined.
Voodoo 3 drivers install `VGARTD.VXD`, which is active even when Voodoo 3 is absent.
And this driver, GART (AGP) services VxD by Intel Corp., breaks `VMM.VXD`, not completely, but enough to cause problems for `VFLATD.VXD` and old video card drivers, which depend on it.
Probably authors did not tested scenario when users want the same Windows installation to work correctly both with AGP and ISA video cards.

**Comment by sskras** [comment]
Cool annd interesting discovery! At least for the retrocomputing folks. Thanks.
