### ISSUE TITLE
Incomplete page table in GUI debugger

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#393]
I needed to look at page table near address `0xCAD00000`, but GUI debugger wasn't able to show it correctly:
![image](https://github.com/user-attachments/assets/d07880b5-2cfc-4b18-8eb8-e545d8c0aa90)

Luckily, I was able to get this information with `info tab` text command.
However, its output is incomplete as well, it can't be scrolled to addresses before `0xCA3DD000`.

Version: dbfb11f1

**Comment by Vort** [comment]
Turned out, reproduction is not as easy as I thought.
On one installation of Windows 95 table shows correctly, on other - not correctly.

However, I think problem appear just when page table gets too large, `LineCount < 1024` looks suspicious here:
https://github.com/bochs-emu/Bochs/blob/dbfb11f1ddd42f784af5089e24ec16cfaf683555/bochs/gui/enh_dbg.cc#L1646
I will think how to force OSes to generate large page tables.

**Comment by Vort** [comment]
Not the smartest piece of code, but whatever: [memalloc.zip](https://github.com/user-attachments/files/17848432/memalloc.zip).
Launch 2-4 instances of it simultaneously in Windows 95 and page table will grow enough for problem reproduction.

**Comment by Vort** [comment]
By the way, to update page table in GUI after Continue - Break cycle, Alt+F2 should be pressed twice.
I consider this as yet another bug. GUI table should update automatically.

**Comment by stlintel** [comment]
> By the way, to update page table in GUI after Continue - Break cycle, Alt+F2 should be pressed twice.
> I consider this as yet another bug. GUI table should update automatically.

In order to update the table efficiently need to catch if it was modified since last update, which is nearly impossible.
BTW, the table itself isn't really trustful too because CPU has TLB and TLB is not necessary coherent with memory.

**Comment by Vort** [comment]
In cases when autoupdate is not desirable, GUIs usually provide "Refresh" button, which helps user to understand that table is not autoupdated.

If autoupdate is that problematic, then it is possible to focus this issue specifically on artificial table length limit. I checked and confirmed that `LineCount < 1024` is the cause.

**Comment by stlintel** [comment]
I noticed that GUI debugger dump page table routine was kind of outdate, text debugger used different routine which was updated to support 64-bit and more.
I ported it to GUI debugger but haven't test it yet - can you take a look and if okay, will merge it

**Comment by stlintel** [comment]
Let me know if the issue may be considered to be resolved
About adding 'Refresh' button there may be better to add separate issue because I don't really know how to resolve it (no a GUI person)

**Comment by Vort** [comment]
Looks good with b942d5ca. Thank you.

![image](https://github.com/user-attachments/assets/66f6b1fc-9976-438f-b4ed-447c13f85850)
