### ISSUE TITLE
Fix boot for vvfat disk

### ISSUE THREAD

**Issue by jossk** [bochs-emu/Bochs#40]
I dump mbr/boot sector from USB flash. Primary partition was align by 1 Mb.
Copy all files to local dir and make vvfat disk.
But after start bochs is crashed.
Quick look on source code:

./vvfat.cc:
`
  first_sectors = new Bit8u[0xc000]; // allocate too small memory :(
`

Next changes will be fix the problem :

vvfat_image_t::vvfat_image_t(Bit64u size, const char* _redolog_name)
{
  const size_t first_sectors_count = 4096;
  const size_t first_sectors_size = first_sectors_count * 0x200;
  //const size_t first_sectors_size = 0xC000;
  
  if (sizeof(bootsector_t) != 512) {
    BX_FATAL(("system error: invalid bootsector structure size"));
  }

  first_sectors = new Bit8u[first_sectors_size];
  memset(&first_sectors[0], 0, first_sectors_size);
  ...

PS Can be better check size of allocated first_sectors ...

**Comment by vruppert** [comment]
Please try again with the latest code.

**Comment by vruppert** [comment]
No response. This issue can be closed.
