### ISSUE TITLE
Incorrect rendering of Block game with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#402]
When Block game is launched in Windows 95 with Voodoo 3, it shows incorrect output:

![bochs_block_voodoo3](https://github.com/user-attachments/assets/2fa1c767-3fc9-4ed6-b44c-dfed93c9d3e9)

With CL-GD5446, output is correct:

![bochs_block_cirrus](https://github.com/user-attachments/assets/02d91764-c295-4ae8-8194-493f2011b490)

Test files: [block130.zip](https://github.com/user-attachments/files/17975611/block130.zip)
Version: 5d471d2

**Comment by Vort** [comment]
I copied `src_ptr` modification code from few lines below and rendering is correct now.
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index 81fb33bac..00b27374f 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -2657,6 +2657,7 @@ void bx_banshee_c::blt_screen_to_screen()
       dst_ptr += dpitch;
     } while (--nrows);
   } else if (colorkey_en > 0) {
+    src_ptr += (sy * abs(spitch) + sx * spxsize);
     nrows = h;
     do {
       src_ptr1 = src_ptr; 
```

**Comment by vruppert** [comment]
Suggested change applied.
