### ISSUE TITLE
gui debugger doesn't appear (linux)

### ISSUE THREAD

**Issue by effbiae** [bochs-emu/Bochs#406]
i'm on linux x64

i cloned this repo and configured it:
```
$ ./configure --enable-smp --enable-cpu-level=6 --enable-all-optimizations --enable-x86-64 --enable-pci --enable-usb --enable-vmx --enable-debugger --enable-disasm --enable-debugger-gui --enable-logging --enable-fpu --enable-3dnow --enable-sb16=dummy --enable-cdrom --enable-x86-debugger --enable-iodebug --disable-plugins --disable-docbook --with-x --with-x11 --with-term --enable-avx --enable-evex
$ make 
$ sudo make install
```

then i run `$ bochs -n -q  display_library:x,options=gui_debug` and press `6` to start the simulation
then i get a dialog box saying "Bochs debugger not available - ignoring 'gui_debug' option"

how do i enable the gui debugger?

i attach [config.log](https://github.com/user-attachments/files/18050681/config.log)

**Comment by stlintel** [comment]
I see inside:
configure:27242: WARNING: The Bochs debugger gui cannot be compiled here, disabling it
configure:27261: WARNING: The USB debugger cannot be compiled here, disabling it

**Comment by stlintel** [comment]
I guess because of this:

```
configure:26588: gcc -c -g -O2 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES  -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES conftest.c >&5
conftest.c:190:10: fatal error: X11/xpm.h: No such file or directory
  190 | #include <X11/xpm.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by vruppert** [comment]
For the gui debugger on Linux you need to have GTK version 2 or 3 with it's development package installed on your system. The USB debugger for Linux is under construction and requires GTK version 3.

**Comment by effbiae** [comment]
i installed libgtk-3-dev and libxpm-dev and configured and installed same as before.  this time, no warnings about the debugger being disabled, but bochs hangs on boot with no debugger:
```
bochs -log bochs.log -f /dev/null boot:disk ata0-master:type=disk,path=/home/jack/bm/BareMetal-OS/sys/baremetal_os.img display_library:x,options=gui_debug
```
i attach the log and config.log
[bochs.log](https://github.com/user-attachments/files/18051299/bochs.log)
[config.log](https://github.com/user-attachments/files/18051300/config.log)

**Comment by vruppert** [comment]
When you are using the latest Bochs code, you should have a look at the top of the CHANGES file. We have recently added support for compiling with debugger by default and enabling it with a command line option.

bochs -dbg ...

This turns on the debugger support. Adding "gui_debug" option only switches to the gui dialog. We should think about adding a command line option "-guidbg" to turn on both at the same time.

**Comment by effbiae** [comment]
ah, thank you
```
$ bochs -dbg  display_library:x,options=gui_debug
```
is the answer

yes, something like `-guidbg` would be convenient. it's hard to judge what is consistent with bochs aesthetics
