### ISSUE TITLE
bochs hangs with minibootable.img

### ISSUE THREAD

**Issue by effbiae** [bochs-emu/Bochs#407]
i git clone'd the repo and am doing some testing. i configured and make installed.
i downloaded [linux-img.tar.gz](https://bochs.sourceforge.io/guestos/linux-img.tar.gz) from https://bochs.sourceforge.io/diskimages.html for testing. the tar.gz contains `minibootable.img`. i untar'ed it and ran:

```
$ bochs boot:disk ata0-master:type=disk,path=./minibootable.img
```
i chose `6` from the main menu and bochs appears to hang (i left it for about a minute)

i attach the log
[bochsout.txt](https://github.com/user-attachments/files/18051562/bochsout.txt)

**Comment by effbiae** [comment]
to be fair, the bochs 2.8 release also hangs with a similar log with minibootable.img

**Comment by effbiae** [comment]
there's a bochsrc file in the tar.gz so i ran bochs with no arguments. it got a lot further but got stuck again

is there a known good img file i can test with?
[bochsout.txt](https://github.com/user-attachments/files/18051627/bochsout.txt)

**Comment by Vort** [comment]
> i chose 6 from the main menu and bochs appears to hang (i left it for about a minute)

Because it is important to add `,cylinders=900,heads=15,spt=17`

> it got a lot further but got stuck again

I'm almost sure it's a bug and should be fixed. Please leave this issue open until then.

> is there a known good img file i can test with?

`hd10meg.img` from https://bochs.sourceforge.io/guestos/dlxlinux4.tar.gz works good.
You need to add `.bin` for `vgaromimage:` option for latest builds however.

**Comment by Vort** [comment]
I was expecting `minibootable.img` was working correctly some time in the past, but I checked many versions of Bochs down to 2.2.6, and all of them show similar behaviour.
It may be not completely broken however: after several `hda: lost interrupt` messages, `VFS: Mounted root (ext2 filesystem) readonly.` message appear, but fixes are required anyway.
![image](https://github.com/user-attachments/assets/1125a968-f1be-4850-89ed-dc6f5bd7c88c)

**Comment by Vort** [comment]
Same disk converted to compatible format and added to VirtualBox 6.1.36 seems to produce correct result:
![vbox_tinylinux](https://github.com/user-attachments/assets/81ff6f8c-4ee4-4987-98bf-660677b71e06)

QEMU 7.0.0 and VMware 12.5.2 produced the same incorrect result as Bochs.

**Comment by Vort** [comment]
I have no idea how APIC works, but I figured out that problem is somehow related to it.
If I force `match` variable to `true` in the following place, OS loads fine.
```diff
diff --git a/bochs/cpu/apic.cc b/bochs/cpu/apic.cc
index bedd06f18..33b41cb5f 100644
--- a/bochs/cpu/apic.cc
+++ b/bochs/cpu/apic.cc
@@ -953,7 +953,7 @@ bool bx_local_apic_c::match_logical_addr(apic_dest_t address)
 
   if (dest_format == 0xf) {
     // flat model
-    match = ((address & ldr) != 0);
+    match = true;
     BX_DEBUG(("comparing MDA %02x to my LDR %02x -> %s", address,
       ldr, match ? "Match" : "Not a match"));
   } 
```

**Comment by Vort** [comment]
Here is the answer:
> "In both flat and clustered logical mode, a destination mask of all set bits indicates a broadcast. See AMD spec. 16.6.1 "Receiving System and IPI Interrupts"."

https://github.com/mirror/vbox/blob/74117a1cb257c00e2a92cf522e8e930bd1c4d64b/src/VBox/VMM/VMMAll/APICAll.cpp#L805-L808

So I suggest following change:
```diff
diff --git a/bochs/cpu/apic.cc b/bochs/cpu/apic.cc
index bedd06f18..3f90fe731 100644
--- a/bochs/cpu/apic.cc
+++ b/bochs/cpu/apic.cc
@@ -951,6 +951,8 @@ bool bx_local_apic_c::match_logical_addr(apic_dest_t address)
   }
 #endif
 
+  if (address == 0xff) // broadcast all
+    return true;
   if (dest_format == 0xf) {
     // flat model
     match = ((address & ldr) != 0);
@@ -959,9 +961,6 @@ bool bx_local_apic_c::match_logical_addr(apic_dest_t address)
   }
   else if (dest_format == 0) {
     // cluster model
-    if (address == 0xff) // broadcast all
-      return true;
-
     if ((unsigned)(address & 0xf0) == (unsigned)(ldr & 0xf0))
       match = ((address & ldr & 0x0f) != 0);
   } 
```

**Comment by stlintel** [comment]
Seems perfectly correct to me, pushing to master
