### ISSUE TITLE
Black screen in Destruction Derby 2 with CL-GD5446

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#409]
When Destruction Derby 2 is started by executing `dd2.exe` in Windows 95 with CL-GD5446, black screen appears and OS hangs.
![image](https://github.com/user-attachments/assets/fb7ca3fd-b86b-4b2f-8c8f-165a4ffe3e87)
If `dd2h.exe` is executed instead, game starts fine. Also game works fine, both with `dd2.exe` and `dd2h.exe` using Voodoo 3:
![image](https://github.com/user-attachments/assets/31ec3c64-bade-4ae5-b4f8-0db8ad0f43c3)

Test files: [DestructionDerby2.zip](https://github.com/user-attachments/files/18061471/DestructionDerby2.zip)
Version: f04b428

**Comment by Vort** [comment]
This problem appears with driver v1.41. Game works fine with default driver.
Probably, reason is just bugs in driver.
![image](https://github.com/user-attachments/assets/f9bbdf25-1fbf-45da-8620-e7f8e223a91a)

**Comment by Vort** [comment]
More info:
1. This is some kind of race condition. Hang happens when I launch game from Total Commander, but no hang appear when I launch game from desktop.
2. Hang happens because game repeatedly reads from specific memory location above 1 MB. However, `bx_svga_cirrus_c::mem_read` returns `0xff` instead of real data:
https://github.com/bochs-emu/Bochs/blob/ab954d7ddfee69946341270d1b53924d4a531a7f/bochs/iodev/display/svga_cirrus.cc#L556-L560
When I disable these lines, hang disappear.
Something is not right with this code.

**Comment by vruppert** [comment]
This code may be wrong, removing these lines doesn't fix the black screen with dd2.exe here. Then I tried with dd2h.exe, Voodoo3 and some Windows versions. All combinations show a black screen and return to Windows desktop when pressing a key.

**Comment by Vort** [comment]
Did you extracted `Dirinfo` file as well?
It is not enough to have just `exe` file.

**Comment by Vort** [comment]
Looks like I know where `if (offset >= 0x100000) {` check comes from:
![image](https://github.com/user-attachments/assets/6e22e099-0aff-477b-882c-313deffaeea4)
Documentation says about "first 1 Mbyte" of frame buffer.
But, if I understand correctly, MMIO addresses are not part of it.

In such case, these code blocks should be swapped:
```diff
diff --git a/bochs/iodev/display/svga_cirrus.cc b/bochs/iodev/display/svga_cirrus.cc
index 4c4c99b59..43c21c9a0 100644
--- a/bochs/iodev/display/svga_cirrus.cc
+++ b/bochs/iodev/display/svga_cirrus.cc
@@ -553,17 +553,17 @@ Bit8u bx_svga_cirrus_c::mem_read(bx_phy_address addr)
       Bit8u *ptr;
 
       Bit32u offset = addr & BX_CIRRUS_THIS memsize_mask;
+      if ((offset >= (BX_CIRRUS_THIS s.memsize - 256)) &&
+          ((BX_CIRRUS_THIS sequencer.reg[0x17] & 0x44) == 0x44)) {
+        return svga_mmio_blt_read(offset & 0xff);
+      }
+
       if ((BX_CIRRUS_THIS sequencer.reg[0x07] & 0x01) == CIRRUS_SR7_BPP_VGA) {
         if (offset >= 0x100000) {
           return 0xff;
         }
       }
 
-      if ((offset >= (BX_CIRRUS_THIS s.memsize - 256)) &&
-          ((BX_CIRRUS_THIS sequencer.reg[0x17] & 0x44) == 0x44)) {
-        return svga_mmio_blt_read(offset & 0xff);
-      }
-
       // video-to-cpu BLT
       if (BX_CIRRUS_THIS bitblt.memdst_needed != 0) {
         ptr = BX_CIRRUS_THIS bitblt.memdst_ptr; 
```

**Comment by vruppert** [comment]
Oh, I'm sorry, I really copied only the EXE files. Now I don't have a black screen at all tests. I don't have this specific driver version installed here. Your suggested changes look okay to me, so I could apply it if the issue is fixed then.

**Comment by Vort** [comment]
> Your suggested changes look okay to me, so I could apply it if the issue is fixed then.

This change fixes this problem: driver makes few reads from status register and game loading continues normally.

**Comment by vruppert** [comment]
Okay, applied.

**Comment by Vort** [comment]
Thanks.
