### ISSUE TITLE
Log flood in DX-Ball with Sound Blaster 16

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#410]
After DX-Ball game main screen is loaded in Windows 95 with Sound Blaster 16, log starts to be flooded with such messages:
`[DEV   ] read from port 0x0220 with len 2 returns 0xffff`

I checked `SB16.VXD` _(74331 bytes in size)_ and it indeed contains 2 byte reads.
So I assume this is normal thing for sb16 device.
![image](https://github.com/user-attachments/assets/2ebd52aa-f23e-435b-8cbb-efa25245de4d)

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/4404538e-dc19-4f72-b83a-eb6693a11332)
</details> 

Test files: [dx-ball.ver.1.07.English.zip](https://github.com/user-attachments/files/18083667/dx-ball.ver.1.07.English.zip)
Version: ccd4260

**Comment by vruppert** [comment]
I have now added support for 16-bit reads from even addresses. Since the odd address is reserved, the upper 8 bits return 0.

**Comment by Vort** [comment]
Log looks cleaner now. Thank you.
