### ISSUE TITLE
GUI debugger can't start on Fedora 41

### ISSUE THREAD

**Issue by fuel-pcbox** [bochs-emu/Bochs#413]
It always says it can't start the debugger, so it ignores the gui_debug option.

**Comment by vruppert** [comment]
Are you using current release or latest github sources? This message usually appears when using a binary without debugger support. In that case we recommend to use the latest sources and compile Bochs with --enable-debugger configure option and start it with the additional -dbg command line option to turn the debugger support on.

**Comment by fuel-pcbox** [comment]
Oh, you need to use the -dbg command line option? Why don't the docs say this? Ugh.

**Comment by fuel-pcbox** [comment]
Nope, still doesn't work. Also, I DID compile with --enable-debugger on the configure script, AND --enable-debugger-gui

**Comment by Vort** [comment]
> Why don't the docs say this?

It is there:

https://github.com/bochs-emu/Bochs/blob/adb6dbd8be9abb426d41a65a2b768c88ad3753ed/bochs/doc/docbook/user/user.dbk#L5410-L5413

> Also, I DID compile with --enable-debugger on the configure script, AND --enable-debugger-gui

What other configure options are you using?

> GUI debugger frontend is supported for Win32 and GTK2/GTK3 hosts.

https://github.com/bochs-emu/Bochs/blob/adb6dbd8be9abb426d41a65a2b768c88ad3753ed/bochs/doc/docbook/user/user.dbk#L371-L372

**Comment by vruppert** [comment]
The -dbg command is quite new and the manual page for Bochs needs an update. The latest code can be compiled with debugger support and you can run it without this option with a minimal performance loss compared with the "no debugger" build. Please have a look at the configure output and the generated config.h (BX_DEBUGGER and BX_DEBUGGER_GUI must be set to 1). On your platform you need to have GTK2 or GTK3 with the development package installed.

**Comment by fuel-pcbox** [comment]
Now I'm getting this error `>PANIC<< USB debugger does not yet support type 2`

**Comment by fuel-pcbox** [comment]
NVM, I got it working.
