### ISSUE TITLE
Virtua Chess fails to load from 800 MB partition

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#416]
When I try to load Virtua Chess from 800 MB partition with `BIOS-bochs-latest`, `16 bit code is too large` error appears. With `bios.bin-1.13.0`, game loads fine.

![bochs_vchess800](https://github.com/user-attachments/assets/348b95fe-0356-46c9-84de-618fefe660f5)

Test files: [VChess800.zip](https://github.com/user-attachments/files/18142240/VChess800.zip)
Version: be1a433

**Comment by vruppert** [comment]
I can confirm this issue when using Bochs BIOS. With Ben's new BIOS the game also loads fine.

**Comment by Vort** [comment]
Fixed with 908cea26ed18068594339805de8c5a3896408c20.
