### ISSUE TITLE
Wrong 3D output in 512x384 mode with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#418]
When Voodoo 3 is switched to displaying 3D with 512x384 resolution, half of the screen is not rendered correctly.
This is recent regression, this mode was working fine in Bochs 2.8.

![bochs_hl_512_384](https://github.com/user-attachments/assets/ee7eb849-bd2c-4398-800a-23377aba22c3)
Version: be1a433

**Comment by Vort** [comment]
Results of regression test point to commit 29b63b2cb34f534d3105edfc5a74ddd45ef90205.
```
25.08.2024 0138ad4 - good
19.10.2024 4ceb60f - good
28.10.2024 52a3963 - good
03.11.2024 0c33c61 - good
08.11.2024 365c45b - good
09.11.2024 29b63b2 - bad
12.11.2024 f101007 - bad
25.11.2024 0e51dc2 - bad
```

**Comment by vruppert** [comment]
I need a test case to reproduce this issue.

**Comment by Vort** [comment]
@vruppert here it is: [GlideTest512.zip](https://github.com/user-attachments/files/18218712/GlideTest512.zip).

**Comment by Vort** [comment]
I tested few games and results look good. Thanks.

![image](https://github.com/user-attachments/assets/bb872584-889a-46b5-8505-f037ea0b752d)
![image](https://github.com/user-attachments/assets/9ed912e9-7ef6-4be0-857f-afc2de399812)
