### ISSUE TITLE
Partial screen update in Wolfenstein 3-D

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#423]
After Wolfenstein 3-D game is started, screen with system information should be displayed.
However, with some configurations, image appear only partially:
![bochs_wolf_bad](https://github.com/user-attachments/assets/d844e623-8ee2-40a2-8eae-5e81953494c8)

This is how it should look:
![bochs_wolf_good](https://github.com/user-attachments/assets/a8c5b8c0-710d-41a8-b680-8c00d8971e91)

It is easy to make problem disappear by modification of these parameters:
`extension=vbe, update_freq=0, realtime=0`
So it looks like some sort of race condition in VGA code.

Test files: [Wolf3d.zip](https://github.com/user-attachments/files/18203838/Wolf3d.zip).
Version: 64702c0

**Comment by vruppert** [comment]
Start address change now handled correctly.

**Comment by Vort** [comment]
Works good now, thank you.
