### ISSUE TITLE
Intermittent sound in Raptor

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#425]
When Raptor game starts playing sound effects, parts of sound output becomes lost.
For example, here is how effects sound like during following animation: [bochs_raptor_sound.zip](https://github.com/user-attachments/files/18209082/bochs_raptor_sound.zip).

![image](https://github.com/user-attachments/assets/dc9f6e60-d66d-44dd-9ef5-fa4475fc621d)

Besides problems with sound itself, `sb16.log` file starts getting filled with `(3) Read access to 0x0389: unsupported port!` messages. May be related, may be not.

Test files: [Raptor.zip](https://github.com/user-attachments/files/18209045/Raptor.zip)
Version: 64702c0

**Comment by vruppert** [comment]
I had to fix two issues to make the file driver work correctly. Now I can confirm that this issue also exists in the output file. The output in the sb16.log is not related, since port 0x0389 is write-only. I guess the driver uses this read access to get some delay.

**Comment by vruppert** [comment]
Please check if it's okay now.

**Comment by Vort** [comment]
Sound in Raptor is fixed now, thanks.
What is, probably, more important is that sound in Doom works good now as well.
_(Classic question "Can it run Doom?" now have more definitive answer)_

However, commit 2d0daf58 makes Bochs crash when it is built with Visual Studio, because resampler thread tries to access uninitialized buffers, which in turn happen because of `audio_buffers[0] == NULL` check. Uninitialized data may be NULL, but proper code should not depend on it.
I was able to eliminate crash with such change, but I don't know if I broke something in the process:
```diff
diff --git a/bochs/iodev/sound/soundlow.cc b/bochs/iodev/sound/soundlow.cc
index 88b5cbfaf..bb6599060 100644
--- a/bochs/iodev/sound/soundlow.cc
+++ b/bochs/iodev/sound/soundlow.cc
@@ -247,10 +247,8 @@ BX_THREAD_FUNC(mixer_thread, indata)
 bx_soundlow_waveout_c::bx_soundlow_waveout_c()
 {
   put("waveout", "WAVOUT");
-  if (audio_buffers[0] == NULL) {
-    audio_buffers[0] = new bx_audio_buffer_c(BUFTYPE_FLOAT);
-    audio_buffers[1] = new bx_audio_buffer_c(BUFTYPE_UCHAR);
-  }
+  audio_buffers[0] = new bx_audio_buffer_c(BUFTYPE_FLOAT);
+  audio_buffers[1] = new bx_audio_buffer_c(BUFTYPE_UCHAR);
   real_pcm_param = default_pcm_param;
   cb_count = 0;
   pcm_callback_id = -1;
diff --git a/bochs/iodev/sound/soundlow.h b/bochs/iodev/sound/soundlow.h
index f9dfbdbe6..908473922 100644
--- a/bochs/iodev/sound/soundlow.h
+++ b/bochs/iodev/sound/soundlow.h
@@ -81,7 +81,6 @@ private:
   audio_buffer_t *root;
 };
 
-extern bx_audio_buffer_c *audio_buffers[2];
 void convert_float_to_s16le(float *src, unsigned srcsize, Bit8u *dst);
 BOCHSAPI_MSVCONLY Bit32u pcm_callback(void *dev, Bit16u rate, Bit8u *buffer, Bit32u len);
  
```

**Comment by vruppert** [comment]
Thanks for pointing this out. Since the changes look okay to me, I have applied them now. To make the SB16 wavemodes 2 and 3 work without seqfault I had to move the audio buffers to the waveout class. These were some leftovers from the old code.

**Comment by Vort** [comment]
Thanks!
