### ISSUE TITLE
Idea: Discord Server or something similar

### ISSUE THREAD

**Issue by VenomousSteam81** [bochs-emu/Bochs#43]
You guys should make a Discord server or something similar

**Comment by stlintel** [comment]
Why Bochs SF discussion boards are not enough ?

**Comment by qeeg** [comment]
Because it's not instant messaging. That's what this user, and I, want. You could also achieve the same thing with an IRC channel, which you guys also seem to not have.

**Comment by Vort** [comment]
GitHub updates discussions and issues pretty fast.
And it also have benefit of storing all messages for public access.
Discord messages are usually hidden from search engines and this is not good.

**Comment by qeeg** [comment]
Use an IRC channel and log it publicly then. Problem solved.
