### ISSUE TITLE
Build failure with MSVC

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#430]
53e67d4 introduced function `basename`, but it fails to build with MSVC:

![image](https://github.com/user-attachments/assets/134c963f-6683-4c4a-a109-7c17fefd6c0b)

Such change allowed build to finish, but I did not checked if it broke something:
```diff
diff --git a/bochs/gui/keymap.cc b/bochs/gui/keymap.cc
index bea2cf70b..d560928e6 100644
--- a/bochs/gui/keymap.cc
+++ b/bochs/gui/keymap.cc
@@ -97,9 +97,9 @@ bx_keymap_c::~bx_keymap_c(void)
 }
 
 #ifdef WIN32
-char* basename(const char *path)
+const char* basename(const char *path)
 {
-  char *ptr;
+  const char *ptr;
 
   ptr = strrchr(path, '/');
   if (ptr == NULL) { 
```

**Comment by vruppert** [comment]
I have now modified the basename function like it is on Linux and use a normal char buffer for the string. I wonder why there are no dirname and basename functions on Windows.

**Comment by Vort** [comment]
`basename` is not included in C/C++ standard, it comes from POSIX and GNU.
In Windows, [std::filesystem::path::filename](https://en.cppreference.com/w/cpp/filesystem/path/filename) from C++17 or [PathFindFileName](https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathfindfilenamea) from WinAPI can be used.
But I think your `basename` replacement should be fine as well. At least, for now.
