### ISSUE TITLE
Partial update of SDL window in full screen mode

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#435]
When guest OS is in text mode and SDL GUI is switched to full screen, part of the screen stops updating.

To reproduce this problem, start attached program with Bochs in windowed mode, then switch to full screen.
Optionally, you may need to press Esc few times.

Windowed:
![bochs_sdl_w](https://github.com/user-attachments/assets/edffdaee-dac3-4a71-a7f7-7733c89af66d)

Full screen:
![bochs_sdl_fs](https://github.com/user-attachments/assets/6b392d76-eab0-4a4d-85b9-bd323130205a)

Test files: [VC.ZIP](https://github.com/user-attachments/files/18261219/VC.ZIP).
Version: f35eacac

**Comment by vruppert** [comment]
On Linux both SDL 1.2.15 and SDL 2.28.5 builds of Bochs have no issues when entering fullscreen mode. Legacy SDL sometimes resizes window when leaving fullscreen mode. I'll do some tests on Windows soon.

**Comment by vruppert** [comment]
Since graphics mode is okay, I had to add the fullscreen offset for the fullscreen textmode to fix it.

**Comment by Vort** [comment]
I confirm it works correctly now. Thank you.
