### ISSUE TITLE
Crash during power off with Voodoo

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#436]
After I click "Turn power off" button in Bochs GUI when Tomb Raider demo main menu is displayed, most of the time I get crash.

It happens in FIFO thread, in `raster_function` of `voodoo_func.h`:
![image](https://github.com/user-attachments/assets/f7a25a63-fbdb-4852-9e23-bb9e30ca990a)

At the same time, main thread executes `bx_voodoo_base_c::~bx_voodoo_base_c()`:
![image](https://github.com/user-attachments/assets/63fe713e-288c-40d8-a821-b7cae4267691)

Looks like FIFO thread is not stopping properly for some reason.

Test files: [TR.ZIP](https://github.com/user-attachments/files/18263909/TR.ZIP).
Version: b14605d

**Comment by vruppert** [comment]
I cannot reproduce this issue here on Linux and I haven't tried it on Windows yet. I guess the thread is still busy and it needs more time to reach the voodoo_keep_alive check. You can try to add BX_MSLEEP() in destructor right after setting voodoo_keep_alive = 0. I suggest to start with sleep value 1 and increase it until the crash no longer appears.

**Comment by Vort** [comment]
> You can try to add BX_MSLEEP() in destructor right after setting voodoo_keep_alive = 0. I suggest to start with sleep value 1 and increase it until the crash no longer appears.

This is not how proper multithreaded programs should be made.

Looks like I know where problem is. I will look what function should be there.
https://github.com/bochs-emu/Bochs/blob/b14605d6c97570ba71ffe5a1d51e6b46006e3941/bochs/bxthread.h#L34

**Comment by Vort** [comment]
I think this is how it should be done. No crashes anymore for me at least.
```diff
diff --git a/bochs/bxthread.h b/bochs/bxthread.h
index 031d5e333..b8439fba3 100644
--- a/bochs/bxthread.h
+++ b/bochs/bxthread.h
@@ -31,7 +31,7 @@
 #define BX_THREAD_EXIT return 0
 #define BX_THREAD_CREATE(name,arg,var) do { var = CreateThread(NULL, 0, name, arg, 0, NULL); } while (0)
 #define BX_THREAD_KILL(var) TerminateThread(var, 0)
-#define BX_THREAD_JOIN(var)
+#define BX_THREAD_JOIN(var) WaitForSingleObject(var, INFINITE)
 #define BX_LOCK(mutex) EnterCriticalSection(&(mutex))
 #define BX_UNLOCK(mutex) LeaveCriticalSection(&(mutex))
 #define BX_MUTEX(mutex) CRITICAL_SECTION mutex 
```

**Comment by vruppert** [comment]
Thanks, I have now applied your fix to Bochs repository. Now we should review the other code using threads and use BX_THREAD_JOIN if necessary.

**Comment by Vort** [comment]
More threading-related problems need to be untangled, yeah.
