### ISSUE TITLE
Black stripes in Descent 3 with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#438]
After [Descent 3](https://archive.org/details/Descent3USA) with [1.4 patch](https://www.moddb.com/games/descent-3/downloads/descent-3-14-patch) is launched in 3dfx mode with Voodoo 3, black stripes appear in main menu:
![bochs_d3_3dfx](https://github.com/user-attachments/assets/7b6e6ef9-dfc3-4cb7-853e-479097b65677)

[Video](https://www.youtube.com/watch?v=aE1F2KT4ncE&t=1048) shows how it should look with real hardware:
![d3_3dfx_realhw](https://github.com/user-attachments/assets/8bcb2894-bc73-4f8e-b1f4-93c43f0c2108)

In Direct3D mode, menu is displayed fine:
![bochs_d3_d3d](https://github.com/user-attachments/assets/c2da244c-0c7c-4dd5-a33e-23bd17830118)

Version: 911e17f.

**Comment by Vort** [comment]
I don't know if this change is correct or not, but it allows to get correct output in this case:
```diff
diff --git a/bochs/iodev/display/banshee.cc b/bochs/iodev/display/banshee.cc
index f1a883baa..b243bdfc3 100644
--- a/bochs/iodev/display/banshee.cc
+++ b/bochs/iodev/display/banshee.cc
@@ -1536,6 +1536,7 @@ void bx_banshee_c::mem_write(bx_phy_address addr, unsigned len, void *data)
           mask = 0x0000ffff;
         } else {
           mask = 0xffff0000;
+          value <<= 16;
         }
       }
       lfb_w((offset & v->fbi.mask) >> 2, value, mask); 
```

**Comment by vruppert** [comment]
The change looks okay to me.

**Comment by Vort** [comment]
Ok, thanks.
