### ISSUE TITLE
USB mouse and keyboard does not work with Windows 2000 guest

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#48]
Mouse cursor is not moving and console window is flooded with messages
`[USBHID] DATA IN EP1: Packet Toggle indicator doesn't match Device Toggle indicator. 0 != 1`
It was working fine in release version (2.7).

I can provide additional information if needed.
_(And also now I can make binaries myself [with MSYS2])_

Ping @fysnet.

Versions: 571a961d9cb96f7238c45824f2d1bdf893472b47, 2a4dd19e5a26d6be13310efabfe29f1465095d4d _(same effect)_

**Comment by fysnet** [comment]
First, if you wish to ignore this warning, you can turn off the check by setting HANDLE_TOGGLE_CONTROL to zero in usb_common.h
Second, will you please post your bochsrc.txt file?

**Comment by Vort** [comment]
> First, if you wish to ignore this warning, you can turn off the check

Warning is not a problem, non working mouse is.
I thought that warning may be related and that's why told about it.

> Second, will you please post your bochsrc.txt file?

There are lots of things unrelated to this problem.
If it is needed, I can simplify this file:
```text
# configuration file generated by Bochs
plugin_ctrl: voodoo=false, unmapped=true, biosdev=true, speaker=true, extfpuirq=true, parallel=true, serial=true, busmouse=false, e1000=false, es1370=false, gameport=true, ne2k=false, sb16=false, usb_uhci=true, usb_ohci=false, usb_ehci=false, usb_xhci=false
config_interface: win32config
display_library: win32
memory: host=32, guest=32
romimage: file="d:\Bochs-2.7/BIOS-bochs-latest", address=0x00000000, options=none
vgaromimage: file="d:\Bochs-2.7/VGABIOS-lgpl-latest-cirrus"
boot: disk
floppy_bootsig_check: disabled=0
floppya: type=1_44
# no floppyb
ata0: enabled=true, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=disk, path="I:\__VirtualMachines\_Bochs\Windows2000\Windows 2000.vdi", mode=vbox, cylinders=0, heads=16, spt=63, sect_size=512, model="Generic 1234", biosdetect=auto, translation=auto
ata0-slave: type=none
ata1: enabled=true, ioaddr1=0x170, ioaddr2=0x370, irq=15
ata1-master: type=none
ata1-slave: type=none
ata2: enabled=false
ata3: enabled=false
optromimage1: file=none
optromimage2: file=none
optromimage3: file=none
optromimage4: file=none
optramimage1: file=none
optramimage2: file=none
optramimage3: file=none
optramimage4: file=none
pci: enabled=1, chipset=i440bx, slot1=cirrus, slot2=none, slot3=none, slot4=none, slot5=none
vga: extension=cirrus, update_freq=10, realtime=1, ddc=builtin
cpu: count=1, ips=40000000, model=bx_generic, reset_on_triple_fault=1, cpuid_limit_winnt=0, ignore_bad_msrs=1, mwait_is_nop=0
cpuid: level=6, stepping=3, model=3, family=6, vendor_string="GenuineIntel", brand_string="              Intel(R) Pentium(R) 4 CPU        "
cpuid: mmx=true, apic=xapic, simd=sse2, sse4a=false, misaligned_sse=false, sep=true
cpuid: movbe=false, adx=false, aes=false, sha=false, xsave=false, xsaveopt=false, x86_64=true
cpuid: 1g_pages=false, pcid=false, fsgsbase=false, smep=false, smap=false, mwait=true
cpuid: vmx=1
print_timestamps: enabled=0
port_e9_hack: enabled=0
private_colormap: enabled=0
clock: sync=slowdown, time0=local, rtc_sync=0
# no cmosimage
log: -
logprefix: %t%e%d
debug: action=ignore
info: action=report
error: action=report
panic: action=ask
keyboard: type=mf, serial_delay=250, paste_delay=100000, user_shortcut=none
mouse: type=ps2, enabled=false, toggle=ctrl+mbutton
sound: waveoutdrv=win, waveout=none, waveindrv=win, wavein=none, midioutdrv=win, midiout=none
speaker: enabled=true, mode=sound, volume=15
parport1: enabled=true, file=none
parport2: enabled=false
com1: enabled=true, mode=null
com2: enabled=false
com3: enabled=false
com4: enabled=false
usb_uhci: enabled=1, port1=mouse, options1=none, port2=keyboard, options2=none
```

**Comment by fysnet** [comment]
Maybe I should have used a different word that warning, sorry. If the Toggle isn't correct, the packet is not processed, hence the reason the mouse will not work.  Please set HANDLE_TOGGLE_CONTROL to zero, re-compile, and see if the mouse then works.

**Comment by Vort** [comment]
I confirm that setting this line
https://github.com/bochs-emu/Bochs/blob/24f988cf54b0252af6f0592df448df0358030dc7/bochs/iodev/usb/usb_common.h#L149
to `#define HANDLE_TOGGLE_CONTROL 0`
allows mouse and keyboard to work with Windows 2000.

**Comment by fysnet** [comment]
I tried:
```
mouse: type=ps2, enabled=false, toggle=ctrl+mbutton
usb_uhci: enabled=1, port1=mouse, options1=none, port2=keyboard, options2=none
```
and get a similar error as you describe using WinXP as a guest. It also takes a few movements of the mouse to get the HID code to see movement. 
Commenting out the `mouse:` line and the error goes away.
This tells me that the PS2 mouse code is filling its enqueue buffer before it sends movement to the HID mouse. Then since the HID mouse is a bit behind, the Toggle bit might be off.
Please try commenting out the `mouse:` line in your bochsrc.txt and try again, remembering to set `HANDLE_TOGGLE_CONTROL` back to 1.
Please let me know if this fixes the problem, and I will look into the PS2 enqueue code. Thanks for your help.

**Comment by Vort** [comment]
No, removing `mouse:` do not help, still the same message in console.

**Comment by fysnet** [comment]
Okay, thank you again for your help. I will see what I can find.

**Comment by fysnet** [comment]
Please try the following:
usb_hid.cc: at line 1442, please replace the following:
```
case EndpointOutRequest | USB_REQ_CLEAR_FEATURE:
      BX_DEBUG(("HID: CLEAR_FEATURE:"));
      if ((value == 0) && (index != 0x81)) { /* clear EP halt */
        goto fail;
      }
      break;
```
with:
```
    case EndpointOutRequest | USB_REQ_CLEAR_FEATURE:
      BX_DEBUG(("EndpointOutRequest | USB_REQ_CLEAR_FEATURE:"));
      // Value == 0 == Endpoint Halt (the Guest wants to reset the endpoint)
      if (value == 0) { /* clear ep halt */
#if HANDLE_TOGGLE_CONTROL
        set_toggle(index & 0x7F, 0);
#endif
        ret = 0;
      }
      break;
```
Please set the `HANDLE_TOGGLE_CONTROL` back to 1.

This should make Win2k work with the USB mouse and Toggle bits, *mostly*. There will still be a few Toggle bit errors in the log file.

However, it is my opinion that Win2k is a bit buggy when it comes to the USB, so feel free to set the `HANDLE_TOGGLE_CONTROL` back to zero after you get the results of this patch.

Please let me know the result of this change.

Thank you,
Ben

**Comment by Vort** [comment]
> Please let me know the result of this change.

`HANDLE_TOGGLE_CONTROL 1` + `usb_hid.cc` patch make mouse and keyboard work with Win 2000.
I also confirm that `Packet Toggle` messages still appear.

> However, it is my opinion that Win2k is a bit buggy when it comes to the USB

Bugs are bad, I know, but if it is possible for real hardware to work properly despite bugs, virtual hardware should be able to do the same.

**Comment by fysnet** [comment]
Thank you for your help on this. I appreciate it.

**Comment by stlintel** [comment]
Can the issue be closed ?

**Comment by fysnet** [comment]
I believe so. I have done some tests (https://www.fysnet.net/bochs/images/supported.htm) and WinXP still has a few issues with HID devices, but they work most of the time. I think it is a Win2k thing, not a Bochs thing. This is just my opinion though.
Vort, unless you find differently, I think it can be closed.

**Comment by Vort** [comment]
USB mouse and keyboard works with 221cac79720387b33a84c915a922af3c9527f04e in Win 2000 guest. Thank you.
