### ISSUE TITLE
bx_dbg_read_linear: physical memory read error

### ISSUE THREAD

**Issue by meilihao** [bochs-emu/Bochs#50]
env: Ubuntu 22.04

boot.asm:
````asm
org 07C00h                 
       mov ax, cs
       mov ds, ax
       mov es, ax
       call DispStr               
       jmp $       
DispStr:
       mov ax, BootMessage
       mov bp, ax               
       mov cx, 16               
       mov ax, 01301h         
       mov bx, 000Ch             
       mov dl, 0
       int 10h                   
       ret
BootMessage:  db "Hello,OS world!"
	times 510-($-$$)   db   0         
	dw 0xaa55
````
bochsrc:
```conf
# how much memorythe emulated machine will have  
megs: 32 
   
# filename of ROMimages  
romimage:file=/usr/share/bochs/BIOS-bochs-latest
vgaromimage:file=/usr/share/vgabios/vgabios.debug.bin
   
# what disk imageswill be used  
floppya:1_44=test.img, status=inserted  
   
# choose the bootdisk.  
boot: floppy  
   
# where do we sendlog messages?  
log: bochsout.txt  
   
# disable themouse  
mouse: enabled=0  
   
# enable keymapping, using Us layout as default  
keyboard:keymap=/usr/share/bochs/keymaps/x11-pc-us.map

display_library:x
```
bochs:
```bash
$ nasm boot.asm -o boot.bin
$ dd if=boot.bin of=test.img bs=512 count=1 conv=notrunc
$ bochs -f bochsrc.conf 
00000000000i[      ] LTDL_LIBRARY_PATH not set. using compile time default '/usr/lib/x86_64-linux-gnu/bochs/plugins'
========================================================================
                        Bochs x86 Emulator 2.7
              Built from SVN snapshot on August  1, 2021
                Timestamp: Sun Aug  1 10:07:00 CEST 2021
========================================================================
00000000000i[      ] BXSHARE not set. using compile time default '/usr/share/bochs'
00000000000i[      ] lt_dlhandle is 0x55def313df20
00000000000i[PLUGIN] loaded plugin libbx_iodebug.so
00000000000i[      ] lt_dlhandle is 0x55def313e1c0
00000000000i[PLUGIN] loaded plugin libbx_unmapped.so
00000000000i[      ] lt_dlhandle is 0x55def3116d80
00000000000i[PLUGIN] loaded plugin libbx_parallel.so
00000000000i[      ] lt_dlhandle is 0x55def30fabd0
00000000000i[PLUGIN] loaded plugin libbx_gameport.so
00000000000i[      ] lt_dlhandle is 0x55def30fb410
00000000000i[PLUGIN] loaded plugin libbx_extfpuirq.so
00000000000i[      ] lt_dlhandle is 0x55def30fbc50
00000000000i[PLUGIN] loaded plugin libbx_serial.so
00000000000i[      ] lt_dlhandle is 0x55def30ffe30
00000000000i[PLUGIN] loaded plugin libbx_biosdev.so
00000000000i[      ] lt_dlhandle is 0x55def3100810
00000000000i[PLUGIN] loaded plugin libbx_speaker.so
00000000000i[      ] reading configuration from 3.conf
00000000000i[      ] lt_dlhandle is 0x55def31416e0
00000000000i[PLUGIN] loaded plugin libbx_textconfig.so
00000000000i[      ] lt_dlhandle is 0x55def3141eb0
00000000000i[PLUGIN] loaded plugin libbx_x_gui.so
00000000000i[      ] installing x module as the Bochs GUI
00000000000i[      ] using log file bochsout.txt
Next at t=0
(0) [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:1> c
bx_dbg_read_linear: physical memory read error (phy=0x0000322f3130, lin=0x00000000322f3130)
Next at t=698966
(0) [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:2> exit
(0).[698966] [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
```
bochs can't print "Hello,OS world!". And 0x0000322f3130≈803M > megs(32M), what's wrong?

`qemu-system-x86_64 -fda test.img` is works.

**Comment by fysnet** [comment]
You use:
```
org 07C00h                 
       mov ax, cs
       mov ds, ax
       mov es, ax
```
but this assumes that CS is zero.  Change this to:
```
org 07C00h                 
       xor ax, ax
       mov ds, ax
       mov es, ax
```
and try again.

**Comment by meilihao** [comment]
`xor ax, ax` not work:
```log
$ bochs -f bochsrc.conf
...
Next at t=0
(0) [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:1> b 0x7c00
<bochs:2> c
bx_dbg_read_linear: physical memory read error (phy=0x0000322f3130, lin=0x00000000322f3130)
Next at t=689952
(0) [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:3> exit
(0).[689952] [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
```

**Comment by fysnet** [comment]
I tried your original code, works just fine. 
I tried with my `xor ax,ax` change (which you should do anyway), and it works just fine.

`vgaromimage:file=/usr/share/vgabios/vgabios.debug.bin`

My question is, why and where did you get that? You know that the `INT 10h` code is within the vgaromimage file you specified? 

Why not try:

`vgaromimage: file=/bochs/bios/VGABIOS-lgpl-latest-cirrus`

or just:

`vgaromimage: file=/bochs/bios/VGABIOS-lgpl-latest`

I am willing to bet that the error is within the `vgabios.debug.bin` you specified, not Bochs itself.

Also, you probably should change:
  `mov  dl,0`
to
  `mov dx,0   ; or even xor dx,dx`

**Comment by meilihao** [comment]
I tried `...xor ax,ax...mov dx,0...` + `/usr/share/vgabios/vgabios.debug.bin or /usr/share/vgabios/vgabios.cirrus.debug.bin` , got the same error:
```log
00000000000i[      ] using log file bochsout.txt
Next at t=0
(0) [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:1> c
bx_dbg_read_linear: physical memory read error (phy=0x0000322f3130, lin=0x00000000322f3130)
Next at t=689952
(0) [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
exiths:2> ^C
(0).[689952] [0x0000fffffff0] f000:fff0 (unk. ctxt): jmpf 0xf000:e05b          ; ea5be000f0
```

I also think maybe the problem is with the romimage.  my bochsbios/vgabios is from Ubuntu 22.04 apt repo.

I tried `/usr/share/seabios/bios.bin`+`/usr/share/vgabios/vgabios.bin` , found `bx_dbg_read_linear: physical memory read error`  disappeared, but bochs is a black screen.

I also self-compiled seabios 1.16.2 and found `bx_dbg_read_linear: physical memory read error`  disappeared, but bochs is a black screen.

**Comment by 18222901154** [comment]
I'm having the same problem, did you solve it?
![截图 2023-06-22 17-36-35](https://github.com/bochs-emu/Bochs/assets/15910582/511eb036-22cb-4aa8-a62d-2c2c4c8fcf3d)

**Comment by meilihao** [comment]
@18222901154 no, I'm using qemu-system-i386 now.

**Comment by nicklgw** [comment]
I solved the issue.
when config, append **--with-sdl2 --enable-debugger**

nvidia@nvidia-PC:~/Downloads/Bochs-REL_2_7_FINAL/bochs$ cat .conf.linux 
#!/bin/sh
#
# .conf.linux
#

#which_config=normal
which_config=plugins

CC="gcc"
CXX="c++"
CFLAGS="-Wall -O3 -fomit-frame-pointer -pipe"    # for speed
#CFLAGS="-Wall -g -pipe"                         # for development
CXXFLAGS="$CFLAGS"

export CC
export CXX
export CFLAGS
export CXXFLAGS


case $which_config in

  normal)

    #######################################################################
    # configuration 1 for release binary RPMs
    # Include a few standard options, speed optimizations, X11 only.
    #######################################################################
    ./configure **--with-sdl2 \
    		--enable-debugger \**
    		--enable-sb16 \
                --enable-ne2000 \
                --enable-all-optimizations \
                --enable-cpu-level=6 \
                --enable-x86-64 \
                --enable-vmx=2 \
                --enable-pci \
                --enable-clgd54xx \
                --enable-voodoo \
                --enable-usb \
                --enable-usb-ohci \
                --enable-usb-ehci \
                --enable-usb-xhci \
                --enable-busmouse \
                --enable-es1370 \
                --enable-e1000 \
                --enable-show-ips \
                ${CONFIGURE_ARGS}
    ;;

  plugins)
    #######################################################################
    # configuration 2 for release binary RPMs
    # Include plugins, every possible gui.
    #######################################################################
    ./configure **--with-sdl2 \
    		--enable-debugger \**
    		--enable-sb16 \
                --enable-ne2000 \
                --enable-all-optimizations \
                --enable-cpu-level=6 \
                --enable-x86-64 \
                --enable-vmx=2 \
                --enable-pci \
                --enable-clgd54xx \
                --enable-voodoo \
                --enable-usb \
                --enable-usb-ohci \
                --enable-usb-ehci \
                --enable-usb-xhci \
                --enable-busmouse \
                --enable-es1370 \
                --enable-e1000 \
                --enable-plugins \
                --enable-show-ips \
                --with-all-libs \
                ${CONFIGURE_ARGS}
    ;;

esac

**Comment by Jacky-zh-bit** [comment]
Maybe you can try change "romimage:file=/usr/share/bochs/BIOS-bochs-latest" to "romimage:file=/usr/share/bochs/BIOS-bochs-legacy" , but I don't know the reason either..

**Comment by xunathan** [comment]
> Maybe you can try change "romimage:file=/usr/share/bochs/BIOS-bochs-latest" to "romimage:file=/usr/share/bochs/BIOS-bochs-legacy" , but I don't know the reason either..

ubuntu 2204, bochs 2.7, I solved it using this method.
