### ISSUE TITLE
build failures for v2.7 under Leopard/PPC Macports

### ISSUE THREAD

**Issue by khepler** [bochs-emu/Bochs#57]
These seem generic enough to warrant an upstream issue.

First, there's a c++11 style const member initializer at `cpu/icache.h:31`.  Compiling on Leopard/PPC fails with the error "ISO C++ forbids initialization of member ‘PHY_MEM_PAGES’".  Patch follows.
```
--- cpu/icache.h.orig   2023-07-27 10:22:33.000000000 -0700
+++ cpu/icache.h        2023-07-27 10:25:55.000000000 -0700
@@ -28,11 +28,11 @@

 class bxPageWriteStampTable
 {
-  const Bit32u PHY_MEM_PAGES = 1024*1024;
+  const Bit32u PHY_MEM_PAGES;
   Bit32u *fineGranularityMapping;

 public:
-  bxPageWriteStampTable() {
+  bxPageWriteStampTable() : PHY_MEM_PAGES(1024*1024) {
     fineGranularityMapping = new Bit32u[PHY_MEM_PAGES];
     resetWriteStamps();
   }
```

Second, there's an `#if` directive at `iodev/display/voodoo_func.h:1630` that causes compilation to fail with "#if with no expression".  Should this instead be `#ifdefine`?

**Comment by stlintel** [comment]
Please provide a PR with suggested changes

**Comment by stlintel** [comment]
Resolved
