### ISSUE TITLE
Bochs hangs on Ubuntu 22.04.3 running on VirtualBox

### ISSUE THREAD

**Issue by cesarmg1980** [bochs-emu/Bochs#60]
Hello, just to put some context to it,  i'm trying to start up an OS on my own, i'm following a couple of guides like [The little book about OS development](http://littleosbook.github.io/#introduction) and [Roll your own toy UNIX-clone OS](https://web.archive.org/web/20160313134414/http://www.jamesmolloy.co.uk/tutorial_html/index.html) along with a couple of other resources, i have everything set up up to the point of having a basic bootable piece of code but the problem is that when i  try to run `bochs` it opens up and hangs indefinitely with no message, the weird thing is that if don't  touch anything it stays there, but when try to move the window it shows an error like the one in the screenshot:
![Screenshot 2023-08-21 at 23 20 42](https://github.com/bochs-emu/Bochs/assets/38872121/dd3445be-7781-491e-a0b9-5c1b1fbf7013)
[here](https://github.com/cesarmg1980/atomOS/tree/booting) is the repo where i have everything uploaded, maybe somebody is able to reproduce the error (i really hope is something that i'm doing wrong)
Note: i'm running `bochs` under Ubuntu 22.04.3 that's running in a Virtual Machine (VirtualBox) with 4GB RAM, 2 Processors, 25GB Disk.
Thanks in advance to anyone that takes some time to take a look at this

**Comment by cesarmg1980** [comment]
`bochs` version `2.7`

**Comment by cesarmg1980** [comment]
i've just pushed some slightly different code to a new branch `booting_2` and i still get the same issue

**Comment by fysnet** [comment]
Have you had a chance to look at the log file?
I just booted your os.iso image on Win10 and got a few errors with your kernel code:

```
00166702227e[CPU0  ] interrupt(): gate.type(9) != {5,6,7,14,15}
00166702227e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x0d)
00166702227e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x08)
```
and then finally an exception because you tried to execute code at `cs:0x000B` which was invalid.

It looks like your kernel code is not setting up the gate correctly.

Ben

**Comment by cesarmg1980** [comment]
I looked at the logs and I don't see any errors as far as I can see (they were pushed to the repo if you want to take a look) I also splitted the logs in "before-gui" and "after-gui", also I changed from `sdl2` to `x` and this time the window stays there blank, it doesn't tell you to force-quitting but it doesn't show anything at all and to exit the window you have to type `exit` in bochs's console.

if you take a look at the logs when the window is open you will see what's in `bochslog_before_gui.txt` once you type `exit` the logs are what's in `bochslog_after_gui.txt`

Branch: `booting`

**Comment by fysnet** [comment]
Per your logs, Bochs didn't even make it to the 0xF000:0000FFF0 start code. You are also using plugins. Are you able to compile without plugins and see if the same error occurs? I ran your OS.ISO w/o plugins.

**Comment by cesarmg1980** [comment]
I don't know if this is what you mean but I'm seeing `0000000000i[CPU0  ] | EIP=0000fff0 (0000fff0)` in the logs, on the other hand, is it ok that I'm not seeing any errors? (I know that you see it in W10, but I am not in Ubuntu).

**Comment by stlintel** [comment]
it means you stuck on reset before starting to execute first instruction. 
Which is exactly as on the picture, the Bochs is on command line interface waiting for first command.
If you never enter a command (like 'c') - it will never run.
If it is frozen -> probably command line interface is frozen.
I don't know how VBox handles console interface.
Anyway doesn't seems like problem within Bochs itself.

**Comment by cesarmg1980** [comment]
ok, thanks anyway, I'll keep on trying

**Comment by stlintel** [comment]
Closing the issue, no sign of Bochs problem
