### ISSUE TITLE
Does not build with `.conf.win64-vcpp` and Visual Studio

### ISSUE THREAD

**Issue by tandasat** [bochs-emu/Bochs#8]
The steps to build x64 Bochs executable on Windows is running the those commands
```
$ sh .conf.win64-vcpp
$ make win32_snap
```
followed by opening `vs2019\bochs.sln` on VS and building the solution.

This does not work with this error, due to `_M_X64` not being defined.
```
config.h(94,1): fatal error C1189: #error:  Bochs not configured for MSVC WIN32
```
The issue is that the VS projects are not configured for AMD64.

A quick fix is to add an x64 build configuration, based on x86 build configuration on VS GUI.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/1620923/187036224-a936cc7c-47d3-4ee3-8541-75506eeaa296.png">
[x64_config.patch.txt](https://github.com/bochs-emu/Bochs/files/9438227/x64_config.patch.txt)
I confirmed this let us build x64 bochs.exe, and it worked fine.  

The diff is mess, as it duplicating the settings. We might want to delete all `Condition=` attribute and unity the settings. 

If we are okay to PR as the patch does (duplicating settings), I could do fairly soon (then we could clean up projects as a separate PR as I find time).

**Comment by stlintel** [comment]
I am fine with the patch as is.

**Comment by stlintel** [comment]
What about [vs2019-plugins-workspace.zip](https://github.com/bochs-emu/Bochs/blob/master/bochs/build/win32/vs2019-plugins-workspace.zip) ?

**Comment by tandasat** [comment]
Good call out about deprecation. I agree. It is bigger work including doc updates but worth it. 

that ZIP file most likely have the problem. No instruction referred to it and I personally had no reason to build them, but it should get the same treatment as the main ZIP file.

**Comment by stlintel** [comment]
> Good call out about deprecation. I agree. It is bigger work including doc updates but worth it.
> 
> that ZIP file most likely has the same problem. No instruction referred to it and I never tried to use it, but it should get the same treatment as the main ZIP file.

Can you have a PR with the same treatment as main ZIP file, please ?

**Comment by tandasat** [comment]
No commitment but I will take a look this or next weekend.

**Comment by vruppert** [comment]
This issue is fixed now and we should think about removing the legacy win32 configuration for VS.
