### ISSUE TITLE
error in sha1rnds4 implementation?

### ISSUE THREAD

**Issue by bonzini** [bochs-emu/Bochs#85]
The final assignment of A/B/C/D to the destination is

```
  op1.xmm32u(0) = A[4];
  op1.xmm32u(1) = B[4];
  op1.xmm32u(2) = C[4];
  op1.xmm32u(3) = D[4];
```

According to Intel manuals it should be in the opposite direction (A in `op1.xmm32u(3)`, all the way down to D in `op1.xmm32u(0)`), similar to the initial assignment:

```
  A[0] = op1.xmm32u(3);
  B[0] = op1.xmm32u(2);
  C[0] = op1.xmm32u(1);
  D[0] = op1.xmm32u(0);
```

**Comment by stlintel** [comment]
According to the Intel manual 

DEST[127:96] := A_4;
DEST[95:64] := B_4;
DEST[63:32] := C_4;
DEST[31:0] := D_4;

this is exactly what is done. op1 is written to the destination.

if done your way no destination register will be updated at all.
don't understand what you mean

**Comment by stlintel** [comment]
Want to show any example of miscalculation ?

**Comment by bonzini** [comment]
Sorry for the confusion, I quoted the initial move into A/B/C/D to show that bits 127:96 correspond to `op1.xmm32u(3)`, not `op1.xmm32u(0)`. The fix would be:

```
   op1.xmm32u(3) = A[4];
   op1.xmm32u(2) = B[4];
   op1.xmm32u(1) = C[4];
   op1.xmm32u(0) = D[4];
```

> Want to show any example of miscalculation ?

I am setting up Bochs right now to reproduce, as for now I only found this by code inspection. After doing an [implementation of SHA instructions in QEMU](https://gitlab.com/bonzini/qemu/-/commit/4db774b627962c33bc51f47323849d71f8982593), I was curious if there were any differences between my approach and Bochs; which led me to find this one.

You can use the following C program to validate all SHA-NI instructions:

```
#include <immintrin.h>
#include <assert.h>
#include <string.h>

/* Based on https://github.com/rust-lang/stdarch/blob/master/crates/core_arch/src/x86/sha.rs */

#define assert_eq_m128i(a, b) assert(!memcmp(&(a), &(b), 16))

int main()
{
    __m128i a, b, expected, r, k;

    a = _mm_set_epi64x(0xe9b5dba5b5c0fbcf, 0x71374491428a2f98);
    b = _mm_set_epi64x(0xab1c5ed5923f82a4, 0x59f111f13956c25b);
    k = _mm_set_epi64x(0, 0x12835b01d807aa98);

    expected = _mm_set_epi64x(0x2589d5be923f82a4, 0x59f111f13956c25b);
    r = _mm_sha1nexte_epu32(a, b);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0x98829f34f74ad457, 0xda2b1a44d0b5ad3c);
    r = _mm_sha1msg1_epu32(a, b);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0xf714b202d863d47d, 0x90c30d946b3d3b35);
    r = _mm_sha1msg2_epu32(a, b);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0x32b13cd8322f5268, 0xc54420862bd9246f);
    r = _mm_sha1rnds4_epu32(a, b, 0);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0x6d4c43e56a3c25d9, 0xa7e00fb775cbd3fe);
    r = _mm_sha1rnds4_epu32(a, b, 1);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0xb304e383c01222f4, 0x66f6b3b1f89d8001);
    r = _mm_sha1rnds4_epu32(a, b, 2);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0x8189b758bfabfa79, 0xdb08f6e78cae098b);
    r = _mm_sha1rnds4_epu32(a, b, 3);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0xeb84973fd5cda67d, 0x2857b88f406b09ee);
    r = _mm_sha256msg1_epu32(a, b);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0xb58777ce887fd851, 0x15d1ec8b73ac8450);
    r = _mm_sha256msg2_epu32(a, b);
    assert_eq_m128i(r, expected);

    expected = _mm_set_epi64x(0xd3063037effb15ea, 0x187ee3db0d6d1d19);
    r = _mm_sha256rnds2_epu32(a, b, k);
    assert_eq_m128i(r, expected);
}
```

**Comment by stlintel** [comment]
Let's compare to the book:
```
A := SRC1[127:96];
B := SRC1[95:64];
C := SRC1[63:32];
D := SRC1[31:0];

  A[0] = op1.xmm32u(3);
  B[0] = op1.xmm32u(2);
  C[0] = op1.xmm32u(1);
  D[0] = op1.xmm32u(0);
  E[0] = 0;

W0E := SRC2[127:96];
W1 := SRC2[95:64];
W2 := SRC2[63:32];
W3 := SRC2[31:0]; 

  Bit32u W[4] = { op2.xmm32u(3), op2.xmm32u(2), op2.xmm32u(1), op2.xmm32u(0) };
```

```
Round i = 0 operation:
A_1 := f (B, C, D) + (A ROL 5) +W0E +K;
B_1 := A;
C_1 := B ROL 30;
D_1 := C;
E_1 := D;
FOR i = 1 to 3
  A_(i +1) := f (B_i, C_i, D_i) + (A_i ROL 5) +Wi + E_i +K;
  B_(i +1) := A_i;
  C_(i +1) := B_i ROL 30;
  D_(i +1) := C_i;
  E_(i +1) := D_i;
ENDFOR
```
You may see round 0 is the same as round 1 assuming E[0] = 0 as done above
`
  for (unsigned n=0; n < 4; n++) {
    A[n+1] = sha_f(B[n], C[n], D[n], imm) + rotate_l(A[n], 5) + W[n] + E[n] + K;
    B[n+1] = A[n];
    C[n+1] = rotate_l(B[n], 30);
    D[n+1] = C[n];
    E[n+1] = D[n];
  }
`

And at the end:

```
DEST[127:96] := A_4;
DEST[95:64] := B_4;
DEST[63:32] := C_4;
DEST[31:0] := D_4; 
```

matching :

```
  op1.xmm32u(0) = A[4];
  op1.xmm32u(1) = B[4];
  op1.xmm32u(2) = C[4];
  op1.xmm32u(3) = D[4];

```

**Comment by stlintel** [comment]
I am re-using op1 as dest, it has same name by co-incedence and there is no correlation between 
beginning
 A[0] = op1.xmm32u(3);
and end 
  op1.xmm32u(0) = A[4];
these are not the same op1

**Comment by bonzini** [comment]
> You may see round 0 is the same as round 1 assuming E[0] = 0 as done above

Yep I did the same in my QEMU code.

> I am re-using op1 as dest,

I understand but why is Intel doing

```
A <- SRC1[127:96];
...
DEST[127:96] <- A_4;
```

versus this in Bochs:

```
  253   A[0] = op1.xmm32u(3);
...
  267   op1.xmm32u(0) = A[4];
```

Yes it's not the same op1, but it's the same A and each sha1rnds4 will feed into the next four rounds, so why swap the "endianness" of A/B/C/D? Besides this would be the only place in the code where 127:96 becomes `xmm32u(0)`, and I can't see a justification. I haven't yet managed to test my code above inside Bochs to be fully honest... but it's very iffy.

**Comment by stlintel** [comment]
Now I got you. Had to look on it 3 times with fresh eye to catch it !

So the fix should be 

```
  op1.xmm32u(3) = A[4];
  op1.xmm32u(2) = B[4];
  op1.xmm32u(1) = C[4];
  op1.xmm32u(0) = D[4];
```

agree ?

**Comment by bonzini** [comment]
Yes, exactly. It happens to everybody! :)
