### ISSUE TITLE
Crash during suspend with USB keyboard enabled

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#97]
If I enable `usb_uhci` plugin and enable USB keyboard, when I click on Suspend and select directory, crash happens:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/de3e20b8-36f8-4cc4-b8f9-f01e5bc2e333)

Version: 221cac79720387b33a84c915a922af3c9527f04e

**Comment by fysnet** [comment]
There are two lines in usb_hid.cc that are in error.
[Line 1306](https://github.com/bochs-emu/Bochs/blob/master/bochs/iodev/usb/usb_hid.cc#L1306) & 1307:
```
    new bx_shadow_data_c(list, "bx_mouse_hid_report_descriptor", (Bit8u *) s.bx_mouse_hid_report_descriptor, sizeof(s.bx_mouse_hid_report_descriptor), 1);
    new bx_shadow_data_c(list, "model", (Bit8u *) s.model, sizeof(s.model), 1);
```
They should be:
```
    new bx_shadow_data_c(list, "bx_mouse_hid_report_descriptor", (Bit8u *) s.bx_mouse_hid_report_descriptor, s.bx_mouse_hid_report_descriptor_len, 0);
    new bx_shadow_data_c(list, "model", (Bit8u *) &s.model, sizeof(s.model), 0);
```
I will create a pull request for the fix.

Thank you,
Ben

**Comment by stlintel** [comment]
@Vort, can you confirm the fix solve the issue ?

BTW, thanks for so deep testing, this really helps !

**Comment by Vort** [comment]
No more crash with 2b873eb6655eefc826f40633deba9c402413cbe1. Thanks.
